// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_MAINMENU_H
#define UI_MAINMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainMenu
extern void ui_MainMenu_screen_init(void);
extern void ui_MainMenu_screen_destroy(void);
extern lv_obj_t * ui_MainMenu;
extern lv_obj_t * ui_MainMenuPanel;
extern void ui_event_WIFI(lv_event_t * e);
extern lv_obj_t * ui_WIFI;
extern lv_obj_t * ui_Label1;
extern void ui_event_SUBGHZ(lv_event_t * e);
extern lv_obj_t * ui_SUBGHZ;
extern lv_obj_t * ui_Label2;
extern void ui_event_RFIDNFC(lv_event_t * e);
extern lv_obj_t * ui_RFIDNFC;
extern lv_obj_t * ui_Label9;
extern void ui_event_NRF24(lv_event_t * e);
extern lv_obj_t * ui_NRF24;
extern lv_obj_t * ui_Label42;
extern void ui_event_IREC(lv_event_t * e);
extern lv_obj_t * ui_IREC;
extern lv_obj_t * ui_Label48;
extern void ui_event_GPS(lv_event_t * e);
extern lv_obj_t * ui_GPS;
extern lv_obj_t * ui_Label53;
extern void ui_event_BLUETOOTHMenu(lv_event_t * e);
extern lv_obj_t * ui_BLUETOOTHMenu;
extern lv_obj_t * ui_Label54;
extern void ui_event_BADUSBMenu(lv_event_t * e);
extern lv_obj_t * ui_BADUSBMenu;
extern lv_obj_t * ui_Label55;
extern void ui_event_SDCARDMenu(lv_event_t * e);
extern lv_obj_t * ui_SDCARDMenu;
extern lv_obj_t * ui_Label56;
extern void ui_event_SYSTEMMenu(lv_event_t * e);
extern lv_obj_t * ui_SYSTEMMenu;
extern lv_obj_t * ui_Label57;
extern lv_obj_t * ui_battery;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_SDCONNECTION;
extern lv_obj_t * ui_FirmwareProject;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Label1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

