// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_NMEACONSOLE_H
#define UI_NMEACONSOLE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_NmeaConsole
extern void ui_NmeaConsole_screen_init(void);
extern void ui_NmeaConsole_screen_destroy(void);
extern lv_obj_t * ui_NmeaConsole;
extern void ui_event_BACKToGPS3(lv_event_t * e);
extern lv_obj_t * ui_BACKToGPS3;
extern lv_obj_t * ui_Label140;
extern lv_obj_t * ui_NmeaConsoleTextArea;
extern lv_obj_t * ui_NmeaConsolePAUSE;
extern lv_obj_t * ui_Label189;
extern lv_obj_t * ui_Label190;
extern lv_obj_t * ui_NmeaConsoleCLEAR;
extern lv_obj_t * ui_Label191;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

