// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_PcapManager = NULL;
lv_obj_t * ui_BACKToSD = NULL;
lv_obj_t * ui_Label134 = NULL;
lv_obj_t * ui_PcapManagerRoller = NULL;
// event funtions
void ui_event_BACKToSD(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SDCard, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SDCard_screen_init);
    }
}

// build funtions

void ui_PcapManager_screen_init(void)
{
    ui_PcapManager = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PcapManager, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PcapManager, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PcapManager, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACKToSD = lv_btn_create(ui_PcapManager);
    lv_obj_set_width(ui_BACKToSD, 69);
    lv_obj_set_height(ui_BACKToSD, 25);
    lv_obj_set_y(ui_BACKToSD, -100);
    lv_obj_set_x(ui_BACKToSD, lv_pct(-37));
    lv_obj_set_align(ui_BACKToSD, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACKToSD, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACKToSD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACKToSD, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACKToSD, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACKToSD, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACKToSD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BACKToSD, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BACKToSD, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BACKToSD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BACKToSD, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BACKToSD, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BACKToSD, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BACKToSD, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BACKToSD, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BACKToSD, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label134 = lv_label_create(ui_BACKToSD);
    lv_obj_set_width(ui_Label134, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label134, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label134, -1);
    lv_obj_set_y(ui_Label134, 1);
    lv_obj_set_align(ui_Label134, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label134, "BACK");
    lv_obj_set_style_text_font(ui_Label134, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label134, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label134, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_PcapManagerRoller = lv_roller_create(ui_PcapManager);
    lv_roller_set_options(ui_PcapManagerRoller, "odposlech.pcap\nOption 2\nOption 3\nOption4", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_PcapManagerRoller, 249);
    lv_obj_set_height(ui_PcapManagerRoller, lv_pct(74));
    lv_obj_set_x(ui_PcapManagerRoller, 1);
    lv_obj_set_y(ui_PcapManagerRoller, -12);
    lv_obj_set_align(ui_PcapManagerRoller, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_text_color(ui_PcapManagerRoller, lv_color_hex(0x6D00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PcapManagerRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PcapManagerRoller, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PcapManagerRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PcapManagerRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PcapManagerRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PcapManagerRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PcapManagerRoller, lv_color_hex(0x0700FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PcapManagerRoller, 440, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_PcapManagerRoller, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_PcapManagerRoller, 255, LV_PART_SELECTED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_PcapManagerRoller, lv_color_hex(0xB026FF), LV_PART_SELECTED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_PcapManagerRoller, 255, LV_PART_SELECTED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_PcapManagerRoller, lv_color_hex(0xB026FF),
                              LV_PART_SELECTED | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_PcapManagerRoller, 255, LV_PART_SELECTED | LV_STATE_CHECKED | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_BACKToSD, ui_event_BACKToSD, LV_EVENT_ALL, NULL);

}

void ui_PcapManager_screen_destroy(void)
{
    if(ui_PcapManager) lv_obj_del(ui_PcapManager);

    // NULL screen variables
    ui_PcapManager = NULL;
    ui_BACKToSD = NULL;
    ui_Label134 = NULL;
    ui_PcapManagerRoller = NULL;

}
