// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_POWERSLEEP_H
#define UI_POWERSLEEP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PowerSleep
extern void ui_PowerSleep_screen_init(void);
extern void ui_PowerSleep_screen_destroy(void);
extern lv_obj_t * ui_PowerSleep;
extern void ui_event_BACKToSYSTEM2(lv_event_t * e);
extern lv_obj_t * ui_BACKToSYSTEM2;
extern lv_obj_t * ui_Label318;
extern lv_obj_t * ui_STARTIRAttackUni9;
extern lv_obj_t * ui_Label324;
extern lv_obj_t * ui_STARTIRAttackUni10;
extern lv_obj_t * ui_Label325;
extern lv_obj_t * ui_STARTIRAttackUni11;
extern lv_obj_t * ui_Label326;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

