// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_PortalSelectScreen = NULL;
lv_obj_t * ui_BACKToEvilTwin = NULL;
lv_obj_t * ui_Label330 = NULL;
lv_obj_t * ui_PortalSelectScreenRoller = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label347 = NULL;
lv_obj_t * ui_PortalSelectScreenMode = NULL;
// event funtions
void ui_event_BACKToEvilTwin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_EvilTwin, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_EvilTwin_screen_init);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScanAPs, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScanAPs_screen_init);
    }
}

// build funtions

void ui_PortalSelectScreen_screen_init(void)
{
    ui_PortalSelectScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PortalSelectScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PortalSelectScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PortalSelectScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACKToEvilTwin = lv_btn_create(ui_PortalSelectScreen);
    lv_obj_set_width(ui_BACKToEvilTwin, 69);
    lv_obj_set_height(ui_BACKToEvilTwin, 25);
    lv_obj_set_y(ui_BACKToEvilTwin, -100);
    lv_obj_set_x(ui_BACKToEvilTwin, lv_pct(-37));
    lv_obj_set_align(ui_BACKToEvilTwin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACKToEvilTwin, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACKToEvilTwin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACKToEvilTwin, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACKToEvilTwin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACKToEvilTwin, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACKToEvilTwin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BACKToEvilTwin, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BACKToEvilTwin, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BACKToEvilTwin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BACKToEvilTwin, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BACKToEvilTwin, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BACKToEvilTwin, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BACKToEvilTwin, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BACKToEvilTwin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BACKToEvilTwin, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label330 = lv_label_create(ui_BACKToEvilTwin);
    lv_obj_set_width(ui_Label330, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label330, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label330, 0);
    lv_obj_set_y(ui_Label330, 1);
    lv_obj_set_align(ui_Label330, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label330, "BACK");
    lv_obj_set_style_text_font(ui_Label330, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label330, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label330, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_PortalSelectScreenRoller = lv_roller_create(ui_PortalSelectScreen);
    lv_roller_set_options(ui_PortalSelectScreenRoller, "GOOGLE LOGIN\nFACEBOOK LOGIN\nCAPTIVE PORTAL\nKFC FREE\nCUSTOM SD",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_PortalSelectScreenRoller, 249);
    lv_obj_set_height(ui_PortalSelectScreenRoller, lv_pct(72));
    lv_obj_set_x(ui_PortalSelectScreenRoller, 2);
    lv_obj_set_y(ui_PortalSelectScreenRoller, -17);
    lv_obj_set_align(ui_PortalSelectScreenRoller, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_text_color(ui_PortalSelectScreenRoller, lv_color_hex(0x6D00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PortalSelectScreenRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PortalSelectScreenRoller, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PortalSelectScreenRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PortalSelectScreenRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PortalSelectScreenRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PortalSelectScreenRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PortalSelectScreenRoller, lv_color_hex(0x0700FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PortalSelectScreenRoller, 440, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_PortalSelectScreenRoller, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_PortalSelectScreenRoller, 255, LV_PART_SELECTED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_PortalSelectScreenRoller, lv_color_hex(0xB026FF), LV_PART_SELECTED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_PortalSelectScreenRoller, 255, LV_PART_SELECTED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_PortalSelectScreenRoller, lv_color_hex(0xB026FF),
                              LV_PART_SELECTED | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_PortalSelectScreenRoller, 255, LV_PART_SELECTED | LV_STATE_CHECKED | LV_STATE_PRESSED);

    ui_Button4 = lv_btn_create(ui_PortalSelectScreen);
    lv_obj_set_width(ui_Button4, 194);
    lv_obj_set_height(ui_Button4, 25);
    lv_obj_set_y(ui_Button4, -101);
    lv_obj_set_x(ui_Button4, lv_pct(13));
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button4, lv_color_hex(0xF800FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button4, lv_color_hex(0xB900E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label347 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label347, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label347, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label347, -58);
    lv_obj_set_y(ui_Label347, 0);
    lv_obj_set_align(ui_Label347, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label347, "MODE:");
    lv_obj_set_style_text_color(ui_Label347, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label347, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label347, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label347, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label347, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_PortalSelectScreenMode = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_PortalSelectScreenMode, 115);
    lv_obj_set_height(ui_PortalSelectScreenMode, 13);
    lv_obj_set_x(ui_PortalSelectScreenMode, 56);
    lv_obj_set_y(ui_PortalSelectScreenMode, -4);
    lv_obj_set_align(ui_PortalSelectScreenMode, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_PortalSelectScreenMode, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_PortalSelectScreenMode, "NONE");
    lv_obj_set_style_text_font(ui_PortalSelectScreenMode, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_PortalSelectScreenMode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_PortalSelectScreenMode, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_BACKToEvilTwin, ui_event_BACKToEvilTwin, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}

void ui_PortalSelectScreen_screen_destroy(void)
{
    if(ui_PortalSelectScreen) lv_obj_del(ui_PortalSelectScreen);

    // NULL screen variables
    ui_PortalSelectScreen = NULL;
    ui_BACKToEvilTwin = NULL;
    ui_Label330 = NULL;
    ui_PortalSelectScreenRoller = NULL;
    ui_Button4 = NULL;
    ui_Label347 = NULL;
    ui_PortalSelectScreenMode = NULL;

}
