// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_RADIOCONFIG_H
#define UI_RADIOCONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RadioConfig
extern void ui_RadioConfig_screen_init(void);
extern void ui_RadioConfig_screen_destroy(void);
extern lv_obj_t * ui_RadioConfig;
extern void ui_event_BackToSubGHzMenu(lv_event_t * e);
extern lv_obj_t * ui_BackToSubGHzMenu;
extern lv_obj_t * ui_Label99;
extern lv_obj_t * ui_RadioConfigFREQ;
extern lv_obj_t * ui_RadioConfigMOD;
extern lv_obj_t * ui_RadioConfigFREQLabel;
extern lv_obj_t * ui_RadioConfigMODLabel;
extern lv_obj_t * ui_RadioConfigAPPLY;
extern lv_obj_t * ui_Label311;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

