// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_SELECTTARGETBEACON_H
#define UI_SELECTTARGETBEACON_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SelectTargetBeacon
extern void ui_SelectTargetBeacon_screen_init(void);
extern void ui_SelectTargetBeacon_screen_destroy(void);
extern lv_obj_t * ui_SelectTargetBeacon;
extern void ui_event_BACKBeaconModes1(lv_event_t * e);
extern lv_obj_t * ui_BACKBeaconModes1;
extern lv_obj_t * ui_Label327;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label328;
extern lv_obj_t * ui_SelectTargetBeaconSSID;
extern lv_obj_t * ui_WIFINetworks1;
extern lv_obj_t * ui_Network6;
extern lv_obj_t * ui_SSID25;
extern lv_obj_t * ui_SCANAPsButton1;
extern lv_obj_t * ui_Label341;
extern lv_obj_t * ui_FoundAPsPanel1;
extern lv_obj_t * ui_APsFound1;
extern lv_obj_t * ui_Label342;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

