// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_SAVEDREMOTES_H
#define UI_SAVEDREMOTES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SavedRemotes
extern void ui_SavedRemotes_screen_init(void);
extern void ui_SavedRemotes_screen_destroy(void);
extern lv_obj_t * ui_SavedRemotes;
extern void ui_event_BackToIR2(lv_event_t * e);
extern lv_obj_t * ui_BackToIR2;
extern lv_obj_t * ui_Label172;
extern lv_obj_t * ui_SavedRemotesRoller;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

