// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_BLESpam = NULL;
lv_obj_t * ui_BACKToBLE = NULL;
lv_obj_t * ui_Label228 = NULL;
lv_obj_t * ui_Label236 = NULL;
lv_obj_t * ui_BLESpamSTATUS = NULL;
lv_obj_t * ui_BLESpamRoller = NULL;
// event funtions
void ui_event_BACKToBLE(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Bluetooth, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Bluetooth_screen_init);
    }
}

// build funtions

void ui_BLESpam_screen_init(void)
{
    ui_BLESpam = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BLESpam, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLESpam, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLESpam, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACKToBLE = lv_btn_create(ui_BLESpam);
    lv_obj_set_width(ui_BACKToBLE, 69);
    lv_obj_set_height(ui_BACKToBLE, 25);
    lv_obj_set_y(ui_BACKToBLE, -100);
    lv_obj_set_x(ui_BACKToBLE, lv_pct(-37));
    lv_obj_set_align(ui_BACKToBLE, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACKToBLE, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACKToBLE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACKToBLE, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACKToBLE, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACKToBLE, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACKToBLE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BACKToBLE, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BACKToBLE, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BACKToBLE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BACKToBLE, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BACKToBLE, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BACKToBLE, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BACKToBLE, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BACKToBLE, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BACKToBLE, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label228 = lv_label_create(ui_BACKToBLE);
    lv_obj_set_width(ui_Label228, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label228, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label228, -1);
    lv_obj_set_y(ui_Label228, 1);
    lv_obj_set_align(ui_Label228, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label228, "BACK");
    lv_obj_set_style_text_font(ui_Label228, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label228, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label228, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label236 = lv_label_create(ui_BLESpam);
    lv_obj_set_width(ui_Label236, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label236, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label236, 5);
    lv_obj_set_y(ui_Label236, -60);
    lv_obj_set_align(ui_Label236, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label236, "STATUS:");
    lv_obj_set_style_text_color(ui_Label236, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label236, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label236, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label236, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label236, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BLESpamSTATUS = lv_label_create(ui_BLESpam);
    lv_obj_set_width(ui_BLESpamSTATUS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BLESpamSTATUS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BLESpamSTATUS, 84);
    lv_obj_set_y(ui_BLESpamSTATUS, -60);
    lv_obj_set_align(ui_BLESpamSTATUS, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BLESpamSTATUS, "READY");
    lv_obj_set_style_text_color(ui_BLESpamSTATUS, lv_color_hex(0xFF9E00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLESpamSTATUS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BLESpamSTATUS, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BLESpamSTATUS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BLESpamSTATUS, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BLESpamRoller = lv_roller_create(ui_BLESpam);
    lv_roller_set_options(ui_BLESpamRoller, "Windows Swift Pair\nAndroid Fast Pair\nSamsung Earbuds",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_BLESpamRoller, 249);
    lv_obj_set_height(ui_BLESpamRoller, lv_pct(47));
    lv_obj_set_x(ui_BLESpamRoller, 1);
    lv_obj_set_y(ui_BLESpamRoller, -16);
    lv_obj_set_align(ui_BLESpamRoller, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_text_color(ui_BLESpamRoller, lv_color_hex(0x6D00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLESpamRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BLESpamRoller, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BLESpamRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLESpamRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BLESpamRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BLESpamRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BLESpamRoller, lv_color_hex(0x0700FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLESpamRoller, 440, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BLESpamRoller, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_BLESpamRoller, 255, LV_PART_SELECTED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BLESpamRoller, lv_color_hex(0xB026FF), LV_PART_SELECTED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BLESpamRoller, 255, LV_PART_SELECTED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BLESpamRoller, lv_color_hex(0xB026FF),
                              LV_PART_SELECTED | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BLESpamRoller, 255, LV_PART_SELECTED | LV_STATE_CHECKED | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_BACKToBLE, ui_event_BACKToBLE, LV_EVENT_ALL, NULL);
    

}

void ui_BLESpam_screen_destroy(void)
{
    if(ui_BLESpam) lv_obj_del(ui_BLESpam);

    // NULL screen variables
    ui_BLESpam = NULL;
    ui_BACKToBLE = NULL;
    ui_Label228 = NULL;
    ui_Label236 = NULL;
    ui_BLESpamSTATUS = NULL;
    ui_BLESpamRoller = NULL;

}
