// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_Bluetooth = NULL;
lv_obj_t * ui_BackToMainMenu7 = NULL;
lv_obj_t * ui_Label58 = NULL;
lv_obj_t * ui_BLESpamSelect = NULL;
lv_obj_t * ui_Label59 = NULL;
lv_obj_t * ui_BLESnifferSelect = NULL;
lv_obj_t * ui_Label60 = NULL;
lv_obj_t * ui_SourAppleSelect = NULL;
lv_obj_t * ui_Label61 = NULL;
// event funtions
void ui_event_BackToMainMenu7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainMenu_screen_init);
    }
}

void ui_event_BLESpamSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_BLESpam, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_BLESpam_screen_init);
    }
}

void ui_event_BLESnifferSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_BLESniffer, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_BLESniffer_screen_init);
    }
}

void ui_event_SourAppleSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SourApple, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SourApple_screen_init);
    }
}

// build funtions

void ui_Bluetooth_screen_init(void)
{
    ui_Bluetooth = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Bluetooth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Bluetooth, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bluetooth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackToMainMenu7 = lv_btn_create(ui_Bluetooth);
    lv_obj_set_width(ui_BackToMainMenu7, 69);
    lv_obj_set_height(ui_BackToMainMenu7, 25);
    lv_obj_set_y(ui_BackToMainMenu7, -100);
    lv_obj_set_x(ui_BackToMainMenu7, lv_pct(-37));
    lv_obj_set_align(ui_BackToMainMenu7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackToMainMenu7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackToMainMenu7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackToMainMenu7, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackToMainMenu7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BackToMainMenu7, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BackToMainMenu7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BackToMainMenu7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BackToMainMenu7, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackToMainMenu7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackToMainMenu7, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BackToMainMenu7, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BackToMainMenu7, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BackToMainMenu7, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BackToMainMenu7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BackToMainMenu7, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label58 = lv_label_create(ui_BackToMainMenu7);
    lv_obj_set_width(ui_Label58, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label58, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label58, -1);
    lv_obj_set_y(ui_Label58, 1);
    lv_obj_set_align(ui_Label58, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label58, "BACK");
    lv_obj_set_style_text_font(ui_Label58, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label58, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label58, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BLESpamSelect = lv_btn_create(ui_Bluetooth);
    lv_obj_set_height(ui_BLESpamSelect, 24);
    lv_obj_set_width(ui_BLESpamSelect, lv_pct(97));
    lv_obj_set_y(ui_BLESpamSelect, 11);
    lv_obj_set_x(ui_BLESpamSelect, lv_pct(0));
    lv_obj_set_align(ui_BLESpamSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLESpamSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BLESpamSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BLESpamSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BLESpamSelect, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLESpamSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BLESpamSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BLESpamSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BLESpamSelect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BLESpamSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLESpamSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BLESpamSelect, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BLESpamSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BLESpamSelect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BLESpamSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label59 = lv_label_create(ui_BLESpamSelect);
    lv_obj_set_width(ui_Label59, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label59, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label59, -11);
    lv_obj_set_y(ui_Label59, 0);
    lv_obj_set_align(ui_Label59, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label59, "BLE SPAM");
    lv_obj_set_style_text_font(ui_Label59, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label59, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label59, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BLESnifferSelect = lv_btn_create(ui_Bluetooth);
    lv_obj_set_height(ui_BLESnifferSelect, 24);
    lv_obj_set_width(ui_BLESnifferSelect, lv_pct(97));
    lv_obj_set_y(ui_BLESnifferSelect, 46);
    lv_obj_set_x(ui_BLESnifferSelect, lv_pct(0));
    lv_obj_set_align(ui_BLESnifferSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLESnifferSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BLESnifferSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BLESnifferSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BLESnifferSelect, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLESnifferSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BLESnifferSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BLESnifferSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BLESnifferSelect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BLESnifferSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLESnifferSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BLESnifferSelect, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BLESnifferSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BLESnifferSelect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BLESnifferSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label60 = lv_label_create(ui_BLESnifferSelect);
    lv_obj_set_width(ui_Label60, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label60, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label60, -11);
    lv_obj_set_y(ui_Label60, 0);
    lv_obj_set_align(ui_Label60, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label60, "BLE SNIFFER");
    lv_obj_set_style_text_font(ui_Label60, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label60, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label60, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SourAppleSelect = lv_btn_create(ui_Bluetooth);
    lv_obj_set_height(ui_SourAppleSelect, 24);
    lv_obj_set_width(ui_SourAppleSelect, lv_pct(97));
    lv_obj_set_y(ui_SourAppleSelect, 82);
    lv_obj_set_x(ui_SourAppleSelect, lv_pct(0));
    lv_obj_set_align(ui_SourAppleSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SourAppleSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SourAppleSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SourAppleSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SourAppleSelect, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SourAppleSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SourAppleSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SourAppleSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SourAppleSelect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SourAppleSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SourAppleSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SourAppleSelect, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_SourAppleSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_SourAppleSelect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SourAppleSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label61 = lv_label_create(ui_SourAppleSelect);
    lv_obj_set_width(ui_Label61, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label61, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label61, -11);
    lv_obj_set_y(ui_Label61, 0);
    lv_obj_set_align(ui_Label61, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label61, "SOUR APPLE");
    lv_obj_set_style_text_font(ui_Label61, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label61, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label61, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_BackToMainMenu7, ui_event_BackToMainMenu7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BLESpamSelect, ui_event_BLESpamSelect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BLESnifferSelect, ui_event_BLESnifferSelect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SourAppleSelect, ui_event_SourAppleSelect, LV_EVENT_ALL, NULL);

}

void ui_Bluetooth_screen_destroy(void)
{
    if(ui_Bluetooth) lv_obj_del(ui_Bluetooth);

    // NULL screen variables
    ui_Bluetooth = NULL;
    ui_BackToMainMenu7 = NULL;
    ui_Label58 = NULL;
    ui_BLESpamSelect = NULL;
    ui_Label59 = NULL;
    ui_BLESnifferSelect = NULL;
    ui_Label60 = NULL;
    ui_SourAppleSelect = NULL;
    ui_Label61 = NULL;

}
