// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_BLESNIFFER_H
#define UI_BLESNIFFER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BLESniffer
extern void ui_BLESniffer_screen_init(void);
extern void ui_BLESniffer_screen_destroy(void);
extern lv_obj_t * ui_BLESniffer;
extern void ui_event_BACKToBLE1(lv_event_t * e);
extern lv_obj_t * ui_BACKToBLE1;
extern lv_obj_t * ui_Label229;
extern lv_obj_t * ui_Label239;
extern lv_obj_t * ui_BLESnifferDevicesFound;
extern lv_obj_t * ui_BLESnifferTEXTAREA;
extern lv_obj_t * ui_BLESnifferSCAN;
extern lv_obj_t * ui_Label241;
extern lv_obj_t * ui_BLESnifferCLEAR;
extern lv_obj_t * ui_Label242;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

