// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_BadUsb = NULL;
lv_obj_t * ui_BackToMainMenu8 = NULL;
lv_obj_t * ui_Label62 = NULL;
lv_obj_t * ui_BADScriptSelect = NULL;
lv_obj_t * ui_Label77 = NULL;
lv_obj_t * ui_QUICKRunSelect = NULL;
lv_obj_t * ui_Label76 = NULL;
// event funtions
void ui_event_BackToMainMenu8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScanAPs, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScanAPs_screen_init);
    }
}

void ui_event_BADScriptSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SavedScripts, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SavedScripts_screen_init);
    }
}

// build funtions

void ui_BadUsb_screen_init(void)
{
    ui_BadUsb = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BadUsb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BadUsb, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BadUsb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackToMainMenu8 = lv_btn_create(ui_BadUsb);
    lv_obj_set_width(ui_BackToMainMenu8, 69);
    lv_obj_set_height(ui_BackToMainMenu8, 25);
    lv_obj_set_y(ui_BackToMainMenu8, -100);
    lv_obj_set_x(ui_BackToMainMenu8, lv_pct(-37));
    lv_obj_set_align(ui_BackToMainMenu8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackToMainMenu8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackToMainMenu8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackToMainMenu8, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackToMainMenu8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BackToMainMenu8, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BackToMainMenu8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BackToMainMenu8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BackToMainMenu8, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackToMainMenu8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackToMainMenu8, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BackToMainMenu8, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BackToMainMenu8, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BackToMainMenu8, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BackToMainMenu8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BackToMainMenu8, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label62 = lv_label_create(ui_BackToMainMenu8);
    lv_obj_set_width(ui_Label62, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label62, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label62, -1);
    lv_obj_set_y(ui_Label62, 1);
    lv_obj_set_align(ui_Label62, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label62, "BACK");
    lv_obj_set_style_text_font(ui_Label62, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label62, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label62, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BADScriptSelect = lv_btn_create(ui_BadUsb);
    lv_obj_set_height(ui_BADScriptSelect, 45);
    lv_obj_set_width(ui_BADScriptSelect, lv_pct(97));
    lv_obj_set_y(ui_BADScriptSelect, 75);
    lv_obj_set_x(ui_BADScriptSelect, lv_pct(0));
    lv_obj_set_align(ui_BADScriptSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BADScriptSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BADScriptSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BADScriptSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BADScriptSelect, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BADScriptSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BADScriptSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BADScriptSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BADScriptSelect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BADScriptSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BADScriptSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BADScriptSelect, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BADScriptSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BADScriptSelect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BADScriptSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label77 = lv_label_create(ui_BADScriptSelect);
    lv_obj_set_width(ui_Label77, 257);
    lv_obj_set_height(ui_Label77, 36);
    lv_obj_set_x(ui_Label77, 0);
    lv_obj_set_y(ui_Label77, 1);
    lv_obj_set_align(ui_Label77, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label77, "SELECT SCRIPT");
    lv_obj_set_style_text_font(ui_Label77, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label77, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label77, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_QUICKRunSelect = lv_btn_create(ui_BadUsb);
    lv_obj_set_height(ui_QUICKRunSelect, 45);
    lv_obj_set_width(ui_QUICKRunSelect, lv_pct(97));
    lv_obj_set_y(ui_QUICKRunSelect, 9);
    lv_obj_set_x(ui_QUICKRunSelect, lv_pct(-1));
    lv_obj_set_align(ui_QUICKRunSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_QUICKRunSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_QUICKRunSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_QUICKRunSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_QUICKRunSelect, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_QUICKRunSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_QUICKRunSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_QUICKRunSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_QUICKRunSelect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_QUICKRunSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_QUICKRunSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_QUICKRunSelect, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_QUICKRunSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_QUICKRunSelect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_QUICKRunSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label76 = lv_label_create(ui_QUICKRunSelect);
    lv_obj_set_width(ui_Label76, 193);
    lv_obj_set_height(ui_Label76, 36);
    lv_obj_set_x(ui_Label76, 1);
    lv_obj_set_y(ui_Label76, 1);
    lv_obj_set_align(ui_Label76, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label76, "QUICK RUN");
    lv_obj_set_style_text_font(ui_Label76, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label76, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label76, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_BackToMainMenu8, ui_event_BackToMainMenu8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BADScriptSelect, ui_event_BADScriptSelect, LV_EVENT_ALL, NULL);

}

void ui_BadUsb_screen_destroy(void)
{
    if(ui_BadUsb) lv_obj_del(ui_BadUsb);

    // NULL screen variables
    ui_BadUsb = NULL;
    ui_BackToMainMenu8 = NULL;
    ui_Label62 = NULL;
    ui_BADScriptSelect = NULL;
    ui_Label77 = NULL;
    ui_QUICKRunSelect = NULL;
    ui_Label76 = NULL;

}
