// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_BEACONMODES_H
#define UI_BEACONMODES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BeaconModes
extern void ui_BeaconModes_screen_init(void);
extern void ui_BeaconModes_screen_destroy(void);
extern lv_obj_t * ui_BeaconModes;
extern void ui_event_BACKBeaconSpam(lv_event_t * e);
extern lv_obj_t * ui_BACKBeaconSpam;
extern lv_obj_t * ui_Label148;
extern lv_obj_t * ui_Button82;
extern lv_obj_t * ui_Label149;
extern lv_obj_t * ui_Button83;
extern lv_obj_t * ui_Label150;
extern void ui_event_Button84(lv_event_t * e);
extern lv_obj_t * ui_Button84;
extern lv_obj_t * ui_Label151;
extern void ui_event_Button85(lv_event_t * e);
extern lv_obj_t * ui_Button85;
extern lv_obj_t * ui_Label152;
extern void ui_event_Button86(lv_event_t * e);
extern lv_obj_t * ui_Button86;
extern lv_obj_t * ui_Label153;
extern lv_obj_t * ui_BeaconSpamMode2;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label346;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

