// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_BeaconSpam = NULL;
lv_obj_t * ui_BACKWifi2 = NULL;
lv_obj_t * ui_Label101 = NULL;
lv_obj_t * ui_Label128 = NULL;
lv_obj_t * ui_BeaconSpamSTATUS = NULL;
lv_obj_t * ui_Label132 = NULL;
lv_obj_t * ui_BeaconSpamSTART = NULL;
lv_obj_t * ui_Label133 = NULL;
lv_obj_t * ui_Label141 = NULL;
lv_obj_t * ui_BeaconSpamBEACONS = NULL;
lv_obj_t * ui_Label143 = NULL;
lv_obj_t * ui_BeaconSpamTIMER = NULL;
lv_obj_t * ui_BeaconSpamSSIDs = NULL;
lv_obj_t * ui_Button81 = NULL;
lv_obj_t * ui_Label146 = NULL;
lv_obj_t * ui_BeaconSpamMode = NULL;
// event funtions
void ui_event_BACKWifi2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WiFiMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WiFiMenu_screen_init);
    }
}

void ui_event_Button81(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_BeaconModes, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_BeaconModes_screen_init);
    }
}

// build funtions

void ui_BeaconSpam_screen_init(void)
{
    ui_BeaconSpam = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BeaconSpam, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BeaconSpam, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BeaconSpam, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACKWifi2 = lv_btn_create(ui_BeaconSpam);
    lv_obj_set_width(ui_BACKWifi2, 69);
    lv_obj_set_height(ui_BACKWifi2, 25);
    lv_obj_set_y(ui_BACKWifi2, -100);
    lv_obj_set_x(ui_BACKWifi2, lv_pct(-37));
    lv_obj_set_align(ui_BACKWifi2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACKWifi2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACKWifi2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACKWifi2, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACKWifi2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACKWifi2, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACKWifi2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BACKWifi2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BACKWifi2, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BACKWifi2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BACKWifi2, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BACKWifi2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BACKWifi2, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BACKWifi2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BACKWifi2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BACKWifi2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label101 = lv_label_create(ui_BACKWifi2);
    lv_obj_set_width(ui_Label101, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label101, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label101, 0);
    lv_obj_set_y(ui_Label101, 1);
    lv_obj_set_align(ui_Label101, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label101, "BACK");
    lv_obj_set_style_text_font(ui_Label101, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label101, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label101, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label128 = lv_label_create(ui_BeaconSpam);
    lv_obj_set_width(ui_Label128, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label128, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label128, 8);
    lv_obj_set_y(ui_Label128, -69);
    lv_obj_set_align(ui_Label128, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label128, "STATUS:");
    lv_obj_set_style_text_color(ui_Label128, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label128, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label128, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label128, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label128, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BeaconSpamSTATUS = lv_label_create(ui_BeaconSpam);
    lv_obj_set_width(ui_BeaconSpamSTATUS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BeaconSpamSTATUS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BeaconSpamSTATUS, 140);
    lv_obj_set_y(ui_BeaconSpamSTATUS, -68);
    lv_obj_set_align(ui_BeaconSpamSTATUS, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BeaconSpamSTATUS, "STANDBY");
    lv_obj_set_style_text_color(ui_BeaconSpamSTATUS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BeaconSpamSTATUS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BeaconSpamSTATUS, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BeaconSpamSTATUS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BeaconSpamSTATUS, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label132 = lv_label_create(ui_BeaconSpam);
    lv_obj_set_width(ui_Label132, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label132, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label132, 8);
    lv_obj_set_y(ui_Label132, -39);
    lv_obj_set_align(ui_Label132, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label132, "BEACONS:");
    lv_obj_set_style_text_color(ui_Label132, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label132, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label132, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label132, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label132, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BeaconSpamSTART = lv_btn_create(ui_BeaconSpam);
    lv_obj_set_height(ui_BeaconSpamSTART, 31);
    lv_obj_set_width(ui_BeaconSpamSTART, lv_pct(40));
    lv_obj_set_y(ui_BeaconSpamSTART, 59);
    lv_obj_set_x(ui_BeaconSpamSTART, lv_pct(0));
    lv_obj_set_align(ui_BeaconSpamSTART, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BeaconSpamSTART, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BeaconSpamSTART, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BeaconSpamSTART, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BeaconSpamSTART, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BeaconSpamSTART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BeaconSpamSTART, lv_color_hex(0x00FF48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BeaconSpamSTART, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BeaconSpamSTART, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BeaconSpamSTART, lv_color_hex(0x94FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BeaconSpamSTART, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BeaconSpamSTART, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BeaconSpamSTART, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BeaconSpamSTART, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BeaconSpamSTART, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label133 = lv_label_create(ui_BeaconSpamSTART);
    lv_obj_set_width(ui_Label133, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label133, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label133, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label133, "START");
    lv_obj_set_style_text_font(ui_Label133, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label133, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label133, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label141 = lv_label_create(ui_BeaconSpam);
    lv_obj_set_width(ui_Label141, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label141, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label141, 8);
    lv_obj_set_y(ui_Label141, 7);
    lv_obj_set_align(ui_Label141, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label141, "SSIDs:");
    lv_obj_set_style_text_color(ui_Label141, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label141, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label141, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label141, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label141, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BeaconSpamBEACONS = lv_label_create(ui_BeaconSpam);
    lv_obj_set_width(ui_BeaconSpamBEACONS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BeaconSpamBEACONS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BeaconSpamBEACONS, 108);
    lv_obj_set_y(ui_BeaconSpamBEACONS, -38);
    lv_obj_set_align(ui_BeaconSpamBEACONS, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BeaconSpamBEACONS, "500000");
    lv_obj_set_style_text_color(ui_BeaconSpamBEACONS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BeaconSpamBEACONS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BeaconSpamBEACONS, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BeaconSpamBEACONS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BeaconSpamBEACONS, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label143 = lv_label_create(ui_BeaconSpam);
    lv_obj_set_width(ui_Label143, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label143, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label143, 4);
    lv_obj_set_y(ui_Label143, 98);
    lv_obj_set_align(ui_Label143, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label143, "TIMER:");
    lv_obj_set_style_text_color(ui_Label143, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label143, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label143, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label143, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label143, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BeaconSpamTIMER = lv_label_create(ui_BeaconSpam);
    lv_obj_set_width(ui_BeaconSpamTIMER, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BeaconSpamTIMER, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BeaconSpamTIMER, 130);
    lv_obj_set_y(ui_BeaconSpamTIMER, 99);
    lv_obj_set_align(ui_BeaconSpamTIMER, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BeaconSpamTIMER, "00:00");
    lv_obj_set_style_text_color(ui_BeaconSpamTIMER, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BeaconSpamTIMER, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BeaconSpamTIMER, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BeaconSpamTIMER, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BeaconSpamTIMER, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BeaconSpamSSIDs = lv_label_create(ui_BeaconSpam);
    lv_obj_set_width(ui_BeaconSpamSSIDs, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BeaconSpamSSIDs, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BeaconSpamSSIDs, 75);
    lv_obj_set_y(ui_BeaconSpamSSIDs, 8);
    lv_obj_set_align(ui_BeaconSpamSSIDs, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BeaconSpamSSIDs, "42");
    lv_obj_set_style_text_color(ui_BeaconSpamSSIDs, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BeaconSpamSSIDs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BeaconSpamSSIDs, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BeaconSpamSSIDs, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BeaconSpamSSIDs, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Button81 = lv_btn_create(ui_BeaconSpam);
    lv_obj_set_width(ui_Button81, 194);
    lv_obj_set_height(ui_Button81, 25);
    lv_obj_set_y(ui_Button81, -101);
    lv_obj_set_x(ui_Button81, lv_pct(13));
    lv_obj_set_align(ui_Button81, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button81, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button81, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button81, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button81, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button81, lv_color_hex(0xF800FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button81, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button81, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button81, lv_color_hex(0xB900E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button81, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button81, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Button81, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_Button81, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Button81, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label146 = lv_label_create(ui_Button81);
    lv_obj_set_width(ui_Label146, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label146, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label146, -58);
    lv_obj_set_y(ui_Label146, 0);
    lv_obj_set_align(ui_Label146, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label146, "MODE:");
    lv_obj_set_style_text_color(ui_Label146, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label146, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label146, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label146, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label146, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BeaconSpamMode = lv_label_create(ui_Button81);
    lv_obj_set_width(ui_BeaconSpamMode, 114);
    lv_obj_set_height(ui_BeaconSpamMode, 15);
    lv_obj_set_x(ui_BeaconSpamMode, 56);
    lv_obj_set_y(ui_BeaconSpamMode, -3);
    lv_obj_set_align(ui_BeaconSpamMode, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_BeaconSpamMode, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_BeaconSpamMode, "NONE");
    lv_obj_set_style_text_font(ui_BeaconSpamMode, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BeaconSpamMode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BeaconSpamMode, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_BACKWifi2, ui_event_BACKWifi2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button81, ui_event_Button81, LV_EVENT_ALL, NULL);

}

void ui_BeaconSpam_screen_destroy(void)
{
    if(ui_BeaconSpam) lv_obj_del(ui_BeaconSpam);

    // NULL screen variables
    ui_BeaconSpam = NULL;
    ui_BACKWifi2 = NULL;
    ui_Label101 = NULL;
    ui_Label128 = NULL;
    ui_BeaconSpamSTATUS = NULL;
    ui_Label132 = NULL;
    ui_BeaconSpamSTART = NULL;
    ui_Label133 = NULL;
    ui_Label141 = NULL;
    ui_BeaconSpamBEACONS = NULL;
    ui_Label143 = NULL;
    ui_BeaconSpamTIMER = NULL;
    ui_BeaconSpamSSIDs = NULL;
    ui_Button81 = NULL;
    ui_Label146 = NULL;
    ui_BeaconSpamMode = NULL;

}
