// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_BEACONSNIFFING_H
#define UI_BEACONSNIFFING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BeaconSniffing
extern void ui_BeaconSniffing_screen_init(void);
extern void ui_BeaconSniffing_screen_destroy(void);
extern lv_obj_t * ui_BeaconSniffing;
extern void ui_event_BACKWifi7(lv_event_t * e);
extern lv_obj_t * ui_BACKWifi7;
extern lv_obj_t * ui_Label332;
extern lv_obj_t * ui_BeaconSniffingSTART;
extern lv_obj_t * ui_Label354;
extern lv_obj_t * ui_BeaconSniffingCLEAR;
extern lv_obj_t * ui_Label355;
extern lv_obj_t * ui_Label344;
extern lv_obj_t * ui_BeaconSniffingBEACONS;
extern lv_obj_t * ui_BeaconSniffingTEXTAREA;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

