// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_BEACONSPAM_H
#define UI_BEACONSPAM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BeaconSpam
extern void ui_BeaconSpam_screen_init(void);
extern void ui_BeaconSpam_screen_destroy(void);
extern lv_obj_t * ui_BeaconSpam;
extern void ui_event_BACKWifi2(lv_event_t * e);
extern lv_obj_t * ui_BACKWifi2;
extern lv_obj_t * ui_Label101;
extern lv_obj_t * ui_Label128;
extern lv_obj_t * ui_BeaconSpamSTATUS;
extern lv_obj_t * ui_Label132;
extern lv_obj_t * ui_BeaconSpamSTART;
extern lv_obj_t * ui_Label133;
extern lv_obj_t * ui_Label141;
extern lv_obj_t * ui_BeaconSpamBEACONS;
extern lv_obj_t * ui_Label143;
extern lv_obj_t * ui_BeaconSpamTIMER;
extern lv_obj_t * ui_BeaconSpamSSIDs;
extern void ui_event_Button81(lv_event_t * e);
extern lv_obj_t * ui_Button81;
extern lv_obj_t * ui_Label146;
extern lv_obj_t * ui_BeaconSpamMode;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

