// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_BLESpamAction = NULL;
lv_obj_t * ui_BACKToBLESpam = NULL;
lv_obj_t * ui_Label238 = NULL;
lv_obj_t * ui_BLESpamActionSTART = NULL;
lv_obj_t * ui_Label243 = NULL;
lv_obj_t * ui_Label290 = NULL;
lv_obj_t * ui_BLESpamActionTARGET = NULL;
lv_obj_t * ui_Label294 = NULL;
lv_obj_t * ui_BLESpamActionSTATUS = NULL;
lv_obj_t * ui_Label296 = NULL;
lv_obj_t * ui_BLESpamActionPACKETS = NULL;
// event funtions
void ui_event_BACKToBLESpam(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainMenu_screen_init);
    }
}

// build funtions

void ui_BLESpamAction_screen_init(void)
{
    ui_BLESpamAction = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BLESpamAction, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLESpamAction, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLESpamAction, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACKToBLESpam = lv_btn_create(ui_BLESpamAction);
    lv_obj_set_width(ui_BACKToBLESpam, 69);
    lv_obj_set_height(ui_BACKToBLESpam, 25);
    lv_obj_set_y(ui_BACKToBLESpam, -100);
    lv_obj_set_x(ui_BACKToBLESpam, lv_pct(-37));
    lv_obj_set_align(ui_BACKToBLESpam, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACKToBLESpam, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACKToBLESpam, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACKToBLESpam, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACKToBLESpam, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACKToBLESpam, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACKToBLESpam, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BACKToBLESpam, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BACKToBLESpam, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BACKToBLESpam, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BACKToBLESpam, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BACKToBLESpam, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BACKToBLESpam, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BACKToBLESpam, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BACKToBLESpam, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BACKToBLESpam, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label238 = lv_label_create(ui_BACKToBLESpam);
    lv_obj_set_width(ui_Label238, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label238, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label238, -1);
    lv_obj_set_y(ui_Label238, 1);
    lv_obj_set_align(ui_Label238, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label238, "BACK");
    lv_obj_set_style_text_font(ui_Label238, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label238, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label238, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BLESpamActionSTART = lv_btn_create(ui_BLESpamAction);
    lv_obj_set_height(ui_BLESpamActionSTART, 61);
    lv_obj_set_width(ui_BLESpamActionSTART, lv_pct(88));
    lv_obj_set_y(ui_BLESpamActionSTART, 51);
    lv_obj_set_x(ui_BLESpamActionSTART, lv_pct(-1));
    lv_obj_set_align(ui_BLESpamActionSTART, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLESpamActionSTART, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BLESpamActionSTART, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BLESpamActionSTART, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BLESpamActionSTART, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLESpamActionSTART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BLESpamActionSTART, lv_color_hex(0x00FF48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BLESpamActionSTART, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BLESpamActionSTART, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BLESpamActionSTART, lv_color_hex(0x94FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLESpamActionSTART, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BLESpamActionSTART, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BLESpamActionSTART, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BLESpamActionSTART, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BLESpamActionSTART, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_BLESpamActionSTART, lv_color_hex(0xFF0000),
                              LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BLESpamActionSTART, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_BLESpamActionSTART, lv_color_hex(0x4FFF00),
                              LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BLESpamActionSTART, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    ui_Label243 = lv_label_create(ui_BLESpamActionSTART);
    lv_obj_set_width(ui_Label243, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label243, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label243, 0);
    lv_obj_set_y(ui_Label243, -1);
    lv_obj_set_align(ui_Label243, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label243, "START SPAM");
    lv_obj_set_style_text_font(ui_Label243, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label243, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label243, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label290 = lv_label_create(ui_BLESpamAction);
    lv_obj_set_width(ui_Label290, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label290, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label290, 6);
    lv_obj_set_y(ui_Label290, -67);
    lv_obj_set_align(ui_Label290, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label290, "TARGET:");
    lv_obj_set_style_text_color(ui_Label290, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label290, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label290, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label290, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label290, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BLESpamActionTARGET = lv_label_create(ui_BLESpamAction);
    lv_obj_set_width(ui_BLESpamActionTARGET, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BLESpamActionTARGET, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BLESpamActionTARGET, 87);
    lv_obj_set_y(ui_BLESpamActionTARGET, -67);
    lv_obj_set_align(ui_BLESpamActionTARGET, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BLESpamActionTARGET, "Android Fast Pair");
    lv_obj_set_style_text_color(ui_BLESpamActionTARGET, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLESpamActionTARGET, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BLESpamActionTARGET, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BLESpamActionTARGET, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BLESpamActionTARGET, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label294 = lv_label_create(ui_BLESpamAction);
    lv_obj_set_width(ui_Label294, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label294, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label294, 5);
    lv_obj_set_y(ui_Label294, -38);
    lv_obj_set_align(ui_Label294, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label294, "STATUS:");
    lv_obj_set_style_text_color(ui_Label294, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label294, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label294, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label294, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label294, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BLESpamActionSTATUS = lv_label_create(ui_BLESpamAction);
    lv_obj_set_width(ui_BLESpamActionSTATUS, 189);
    lv_obj_set_height(ui_BLESpamActionSTATUS, 18);
    lv_obj_set_x(ui_BLESpamActionSTATUS, 36);
    lv_obj_set_y(ui_BLESpamActionSTATUS, -38);
    lv_obj_set_align(ui_BLESpamActionSTATUS, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_BLESpamActionSTATUS, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_BLESpamActionSTATUS, "READY");
    lv_obj_set_style_text_color(ui_BLESpamActionSTATUS, lv_color_hex(0xFF9E00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLESpamActionSTATUS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BLESpamActionSTATUS, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BLESpamActionSTATUS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BLESpamActionSTATUS, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label296 = lv_label_create(ui_BLESpamAction);
    lv_obj_set_width(ui_Label296, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label296, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label296, 5);
    lv_obj_set_y(ui_Label296, -13);
    lv_obj_set_align(ui_Label296, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label296, "PACKETS SENT:");
    lv_obj_set_style_text_color(ui_Label296, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label296, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label296, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label296, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label296, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BLESpamActionPACKETS = lv_label_create(ui_BLESpamAction);
    lv_obj_set_width(ui_BLESpamActionPACKETS, 125);
    lv_obj_set_height(ui_BLESpamActionPACKETS, 18);
    lv_obj_set_x(ui_BLESpamActionPACKETS, 149);
    lv_obj_set_y(ui_BLESpamActionPACKETS, -14);
    lv_obj_set_align(ui_BLESpamActionPACKETS, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_BLESpamActionPACKETS, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_BLESpamActionPACKETS, "0");
    lv_obj_set_style_text_color(ui_BLESpamActionPACKETS, lv_color_hex(0xFF9E00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLESpamActionPACKETS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BLESpamActionPACKETS, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BLESpamActionPACKETS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BLESpamActionPACKETS, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_BACKToBLESpam, ui_event_BACKToBLESpam, LV_EVENT_ALL, NULL);

}

void ui_BLESpamAction_screen_destroy(void)
{
    if(ui_BLESpamAction) lv_obj_del(ui_BLESpamAction);

    // NULL screen variables
    ui_BLESpamAction = NULL;
    ui_BACKToBLESpam = NULL;
    ui_Label238 = NULL;
    ui_BLESpamActionSTART = NULL;
    ui_Label243 = NULL;
    ui_Label290 = NULL;
    ui_BLESpamActionTARGET = NULL;
    ui_Label294 = NULL;
    ui_BLESpamActionSTATUS = NULL;
    ui_Label296 = NULL;
    ui_BLESpamActionPACKETS = NULL;

}
