// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_BeaconSniffing = NULL;
lv_obj_t * ui_BACKWifi7 = NULL;
lv_obj_t * ui_Label332 = NULL;
lv_obj_t * ui_BeaconSniffingSTART = NULL;
lv_obj_t * ui_Label354 = NULL;
lv_obj_t * ui_BeaconSniffingCLEAR = NULL;
lv_obj_t * ui_Label355 = NULL;
lv_obj_t * ui_Label344 = NULL;
lv_obj_t * ui_BeaconSniffingBEACONS = NULL;
lv_obj_t * ui_BeaconSniffingTEXTAREA = NULL;
// event funtions
void ui_event_BACKWifi7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SniffMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SniffMenu_screen_init);
    }
}

// build funtions

void ui_BeaconSniffing_screen_init(void)
{
    ui_BeaconSniffing = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BeaconSniffing, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BeaconSniffing, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BeaconSniffing, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACKWifi7 = lv_btn_create(ui_BeaconSniffing);
    lv_obj_set_width(ui_BACKWifi7, 69);
    lv_obj_set_height(ui_BACKWifi7, 25);
    lv_obj_set_y(ui_BACKWifi7, -100);
    lv_obj_set_x(ui_BACKWifi7, lv_pct(-37));
    lv_obj_set_align(ui_BACKWifi7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACKWifi7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACKWifi7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACKWifi7, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACKWifi7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACKWifi7, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACKWifi7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BACKWifi7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BACKWifi7, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BACKWifi7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BACKWifi7, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BACKWifi7, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BACKWifi7, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BACKWifi7, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BACKWifi7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BACKWifi7, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label332 = lv_label_create(ui_BACKWifi7);
    lv_obj_set_width(ui_Label332, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label332, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label332, 0);
    lv_obj_set_y(ui_Label332, 1);
    lv_obj_set_align(ui_Label332, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label332, "BACK");
    lv_obj_set_style_text_font(ui_Label332, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label332, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label332, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BeaconSniffingSTART = lv_btn_create(ui_BeaconSniffing);
    lv_obj_set_height(ui_BeaconSniffingSTART, 31);
    lv_obj_set_width(ui_BeaconSniffingSTART, lv_pct(40));
    lv_obj_set_y(ui_BeaconSniffingSTART, 98);
    lv_obj_set_x(ui_BeaconSniffingSTART, lv_pct(-27));
    lv_obj_set_align(ui_BeaconSniffingSTART, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BeaconSniffingSTART, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BeaconSniffingSTART, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BeaconSniffingSTART, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BeaconSniffingSTART, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BeaconSniffingSTART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BeaconSniffingSTART, lv_color_hex(0x00FF48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BeaconSniffingSTART, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BeaconSniffingSTART, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BeaconSniffingSTART, lv_color_hex(0x94FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BeaconSniffingSTART, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BeaconSniffingSTART, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BeaconSniffingSTART, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BeaconSniffingSTART, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BeaconSniffingSTART, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label354 = lv_label_create(ui_BeaconSniffingSTART);
    lv_obj_set_width(ui_Label354, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label354, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label354, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label354, "START");
    lv_obj_set_style_text_font(ui_Label354, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label354, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label354, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BeaconSniffingCLEAR = lv_btn_create(ui_BeaconSniffing);
    lv_obj_set_height(ui_BeaconSniffingCLEAR, 31);
    lv_obj_set_width(ui_BeaconSniffingCLEAR, lv_pct(40));
    lv_obj_set_y(ui_BeaconSniffingCLEAR, 98);
    lv_obj_set_x(ui_BeaconSniffingCLEAR, lv_pct(27));
    lv_obj_set_align(ui_BeaconSniffingCLEAR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BeaconSniffingCLEAR, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BeaconSniffingCLEAR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BeaconSniffingCLEAR, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BeaconSniffingCLEAR, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BeaconSniffingCLEAR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BeaconSniffingCLEAR, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BeaconSniffingCLEAR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BeaconSniffingCLEAR, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BeaconSniffingCLEAR, lv_color_hex(0x94FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BeaconSniffingCLEAR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BeaconSniffingCLEAR, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BeaconSniffingCLEAR, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BeaconSniffingCLEAR, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BeaconSniffingCLEAR, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label355 = lv_label_create(ui_BeaconSniffingCLEAR);
    lv_obj_set_width(ui_Label355, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label355, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label355, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label355, "CLEAR");
    lv_obj_set_style_text_color(ui_Label355, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label355, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label355, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label355, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label355, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label344 = lv_label_create(ui_BeaconSniffing);
    lv_obj_set_width(ui_Label344, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label344, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label344, 5);
    lv_obj_set_y(ui_Label344, -70);
    lv_obj_set_align(ui_Label344, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label344, "BEACONS:");
    lv_obj_set_style_text_color(ui_Label344, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label344, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label344, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label344, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label344, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BeaconSniffingBEACONS = lv_label_create(ui_BeaconSniffing);
    lv_obj_set_width(ui_BeaconSniffingBEACONS, 169);
    lv_obj_set_height(ui_BeaconSniffingBEACONS, 19);
    lv_obj_set_x(ui_BeaconSniffingBEACONS, 105);
    lv_obj_set_y(ui_BeaconSniffingBEACONS, -71);
    lv_obj_set_align(ui_BeaconSniffingBEACONS, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BeaconSniffingBEACONS, "0");
    lv_obj_set_style_text_color(ui_BeaconSniffingBEACONS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BeaconSniffingBEACONS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BeaconSniffingBEACONS, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BeaconSniffingBEACONS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BeaconSniffingBEACONS, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BeaconSniffingTEXTAREA = lv_textarea_create(ui_BeaconSniffing);
    lv_obj_set_width(ui_BeaconSniffingTEXTAREA, 264);
    lv_obj_set_height(ui_BeaconSniffingTEXTAREA, 125);
    lv_obj_set_x(ui_BeaconSniffingTEXTAREA, 7);
    lv_obj_set_y(ui_BeaconSniffingTEXTAREA, -47);
    lv_obj_set_align(ui_BeaconSniffingTEXTAREA, LV_ALIGN_BOTTOM_LEFT);
    lv_textarea_set_text(ui_BeaconSniffingTEXTAREA,
                         "[CH 6] -85dBm - MA:CA:DR:ES:SA - MojeWifi\n[CH 6] -82dBm - MA:CA:DR:ES:SA - MojeWifi\n[CH 1] -40dBm - BE:EF:BE:EF:00 -\n <HIDDEN>\n[CH 6] -85dBm - MA:CA:DR:ES:SA - MojeWifi\n[CH 6] -82dBm - MA:CA:DR:ES:SA - MojeWifi\n[CH 1] -40dBm - BE:EF:BE:EF:00 - <HIDDEN>");
    lv_textarea_set_placeholder_text(ui_BeaconSniffingTEXTAREA, "Placeholder...");
    lv_obj_set_style_text_color(ui_BeaconSniffingTEXTAREA, lv_color_hex(0x00FF30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BeaconSniffingTEXTAREA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BeaconSniffingTEXTAREA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BeaconSniffingTEXTAREA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BeaconSniffingTEXTAREA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BeaconSniffingTEXTAREA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BACKWifi7, ui_event_BACKWifi7, LV_EVENT_ALL, NULL);

}

void ui_BeaconSniffing_screen_destroy(void)
{
    if(ui_BeaconSniffing) lv_obj_del(ui_BeaconSniffing);

    // NULL screen variables
    ui_BeaconSniffing = NULL;
    ui_BACKWifi7 = NULL;
    ui_Label332 = NULL;
    ui_BeaconSniffingSTART = NULL;
    ui_Label354 = NULL;
    ui_BeaconSniffingCLEAR = NULL;
    ui_Label355 = NULL;
    ui_Label344 = NULL;
    ui_BeaconSniffingBEACONS = NULL;
    ui_BeaconSniffingTEXTAREA = NULL;

}
