// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_BLESniffer = NULL;
lv_obj_t * ui_BACKToBLE1 = NULL;
lv_obj_t * ui_Label229 = NULL;
lv_obj_t * ui_Label239 = NULL;
lv_obj_t * ui_BLESnifferDevicesFound = NULL;
lv_obj_t * ui_BLESnifferTEXTAREA = NULL;
lv_obj_t * ui_BLESnifferSCAN = NULL;
lv_obj_t * ui_Label241 = NULL;
lv_obj_t * ui_BLESnifferCLEAR = NULL;
lv_obj_t * ui_Label242 = NULL;
// event funtions
void ui_event_BACKToBLE1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Bluetooth, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Bluetooth_screen_init);
    }
}

// build funtions

void ui_BLESniffer_screen_init(void)
{
    ui_BLESniffer = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BLESniffer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLESniffer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLESniffer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACKToBLE1 = lv_btn_create(ui_BLESniffer);
    lv_obj_set_width(ui_BACKToBLE1, 69);
    lv_obj_set_height(ui_BACKToBLE1, 25);
    lv_obj_set_y(ui_BACKToBLE1, -100);
    lv_obj_set_x(ui_BACKToBLE1, lv_pct(-37));
    lv_obj_set_align(ui_BACKToBLE1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACKToBLE1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACKToBLE1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACKToBLE1, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACKToBLE1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACKToBLE1, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACKToBLE1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BACKToBLE1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BACKToBLE1, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BACKToBLE1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BACKToBLE1, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BACKToBLE1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BACKToBLE1, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BACKToBLE1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BACKToBLE1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BACKToBLE1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label229 = lv_label_create(ui_BACKToBLE1);
    lv_obj_set_width(ui_Label229, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label229, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label229, -1);
    lv_obj_set_y(ui_Label229, 1);
    lv_obj_set_align(ui_Label229, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label229, "BACK");
    lv_obj_set_style_text_font(ui_Label229, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label229, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label229, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label239 = lv_label_create(ui_BLESniffer);
    lv_obj_set_width(ui_Label239, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label239, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label239, 5);
    lv_obj_set_y(ui_Label239, -72);
    lv_obj_set_align(ui_Label239, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label239, "Devices Found:");
    lv_obj_set_style_text_color(ui_Label239, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label239, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label239, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label239, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label239, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BLESnifferDevicesFound = lv_label_create(ui_BLESniffer);
    lv_obj_set_width(ui_BLESnifferDevicesFound, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BLESnifferDevicesFound, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BLESnifferDevicesFound, 148);
    lv_obj_set_y(ui_BLESnifferDevicesFound, -72);
    lv_obj_set_align(ui_BLESnifferDevicesFound, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BLESnifferDevicesFound, "0");
    lv_obj_set_style_text_color(ui_BLESnifferDevicesFound, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLESnifferDevicesFound, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BLESnifferDevicesFound, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BLESnifferDevicesFound, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BLESnifferDevicesFound, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BLESnifferTEXTAREA = lv_textarea_create(ui_BLESniffer);
    lv_obj_set_width(ui_BLESnifferTEXTAREA, 264);
    lv_obj_set_height(ui_BLESnifferTEXTAREA, 136);
    lv_obj_set_x(ui_BLESnifferTEXTAREA, 7);
    lv_obj_set_y(ui_BLESnifferTEXTAREA, -43);
    lv_obj_set_align(ui_BLESnifferTEXTAREA, LV_ALIGN_BOTTOM_LEFT);
    lv_textarea_set_text(ui_BLESnifferTEXTAREA,
                         "[MAC: AA:BB:CC:DD:EE] RSSI: -65dBm 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
    lv_textarea_set_placeholder_text(ui_BLESnifferTEXTAREA, "Placeholder...");
    lv_obj_set_style_text_color(ui_BLESnifferTEXTAREA, lv_color_hex(0x00FF30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLESnifferTEXTAREA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BLESnifferTEXTAREA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLESnifferTEXTAREA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BLESnifferTEXTAREA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BLESnifferTEXTAREA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLESnifferSCAN = lv_btn_create(ui_BLESniffer);
    lv_obj_set_height(ui_BLESnifferSCAN, 31);
    lv_obj_set_width(ui_BLESnifferSCAN, lv_pct(40));
    lv_obj_set_y(ui_BLESnifferSCAN, 98);
    lv_obj_set_x(ui_BLESnifferSCAN, lv_pct(-27));
    lv_obj_set_align(ui_BLESnifferSCAN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLESnifferSCAN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BLESnifferSCAN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BLESnifferSCAN, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BLESnifferSCAN, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLESnifferSCAN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BLESnifferSCAN, lv_color_hex(0x00FF48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BLESnifferSCAN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BLESnifferSCAN, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BLESnifferSCAN, lv_color_hex(0x94FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLESnifferSCAN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BLESnifferSCAN, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BLESnifferSCAN, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BLESnifferSCAN, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BLESnifferSCAN, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label241 = lv_label_create(ui_BLESnifferSCAN);
    lv_obj_set_width(ui_Label241, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label241, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label241, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label241, "SCAN");
    lv_obj_set_style_text_font(ui_Label241, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label241, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label241, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BLESnifferCLEAR = lv_btn_create(ui_BLESniffer);
    lv_obj_set_height(ui_BLESnifferCLEAR, 31);
    lv_obj_set_width(ui_BLESnifferCLEAR, lv_pct(40));
    lv_obj_set_y(ui_BLESnifferCLEAR, 98);
    lv_obj_set_x(ui_BLESnifferCLEAR, lv_pct(27));
    lv_obj_set_align(ui_BLESnifferCLEAR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLESnifferCLEAR, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BLESnifferCLEAR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BLESnifferCLEAR, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BLESnifferCLEAR, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLESnifferCLEAR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BLESnifferCLEAR, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BLESnifferCLEAR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BLESnifferCLEAR, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BLESnifferCLEAR, lv_color_hex(0x94FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLESnifferCLEAR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BLESnifferCLEAR, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BLESnifferCLEAR, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BLESnifferCLEAR, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BLESnifferCLEAR, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label242 = lv_label_create(ui_BLESnifferCLEAR);
    lv_obj_set_width(ui_Label242, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label242, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label242, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label242, "CLEAR");
    lv_obj_set_style_text_color(ui_Label242, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label242, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label242, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label242, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label242, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_BACKToBLE1, ui_event_BACKToBLE1, LV_EVENT_ALL, NULL);

}

void ui_BLESniffer_screen_destroy(void)
{
    if(ui_BLESniffer) lv_obj_del(ui_BLESniffer);

    // NULL screen variables
    ui_BLESniffer = NULL;
    ui_BACKToBLE1 = NULL;
    ui_Label229 = NULL;
    ui_Label239 = NULL;
    ui_BLESnifferDevicesFound = NULL;
    ui_BLESnifferTEXTAREA = NULL;
    ui_BLESnifferSCAN = NULL;
    ui_Label241 = NULL;
    ui_BLESnifferCLEAR = NULL;
    ui_Label242 = NULL;

}
