// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_CCSendSavedAction = NULL;
lv_obj_t * ui_Button91 = NULL;
lv_obj_t * ui_Label301 = NULL;
lv_obj_t * ui_STARTIRAttackUni7 = NULL;
lv_obj_t * ui_Label302 = NULL;
lv_obj_t * ui_STARTIRAttackUni8 = NULL;
lv_obj_t * ui_Label303 = NULL;
// event funtions
void ui_event_Button91(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SavedSignals, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SavedSignals_screen_init);
    }
}

// build funtions

void ui_CCSendSavedAction_screen_init(void)
{
    ui_CCSendSavedAction = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CCSendSavedAction, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CCSendSavedAction, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CCSendSavedAction, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button91 = lv_btn_create(ui_CCSendSavedAction);
    lv_obj_set_width(ui_Button91, 69);
    lv_obj_set_height(ui_Button91, 25);
    lv_obj_set_y(ui_Button91, -100);
    lv_obj_set_x(ui_Button91, lv_pct(-37));
    lv_obj_set_align(ui_Button91, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button91, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button91, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button91, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button91, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button91, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button91, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button91, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button91, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button91, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button91, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Button91, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Button91, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Button91, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_Button91, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Button91, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label301 = lv_label_create(ui_Button91);
    lv_obj_set_width(ui_Label301, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label301, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label301, -1);
    lv_obj_set_y(ui_Label301, 1);
    lv_obj_set_align(ui_Label301, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label301, "BACK");
    lv_obj_set_style_text_font(ui_Label301, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label301, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label301, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_STARTIRAttackUni7 = lv_btn_create(ui_CCSendSavedAction);
    lv_obj_set_height(ui_STARTIRAttackUni7, 61);
    lv_obj_set_width(ui_STARTIRAttackUni7, lv_pct(88));
    lv_obj_set_y(ui_STARTIRAttackUni7, -6);
    lv_obj_set_x(ui_STARTIRAttackUni7, lv_pct(-1));
    lv_obj_set_align(ui_STARTIRAttackUni7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_STARTIRAttackUni7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_STARTIRAttackUni7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_STARTIRAttackUni7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_STARTIRAttackUni7, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_STARTIRAttackUni7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_STARTIRAttackUni7, lv_color_hex(0x00FF48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_STARTIRAttackUni7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_STARTIRAttackUni7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_STARTIRAttackUni7, lv_color_hex(0x94FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_STARTIRAttackUni7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_STARTIRAttackUni7, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_STARTIRAttackUni7, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_STARTIRAttackUni7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_STARTIRAttackUni7, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_STARTIRAttackUni7, lv_color_hex(0xFF0000),
                              LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_STARTIRAttackUni7, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_STARTIRAttackUni7, lv_color_hex(0x4FFF00),
                              LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_STARTIRAttackUni7, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    ui_Label302 = lv_label_create(ui_STARTIRAttackUni7);
    lv_obj_set_width(ui_Label302, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label302, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label302, 0);
    lv_obj_set_y(ui_Label302, -1);
    lv_obj_set_align(ui_Label302, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label302, "TRANSMITT");
    lv_obj_set_style_text_font(ui_Label302, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label302, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label302, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_STARTIRAttackUni8 = lv_btn_create(ui_CCSendSavedAction);
    lv_obj_set_height(ui_STARTIRAttackUni8, 61);
    lv_obj_set_width(ui_STARTIRAttackUni8, lv_pct(88));
    lv_obj_set_y(ui_STARTIRAttackUni8, 70);
    lv_obj_set_x(ui_STARTIRAttackUni8, lv_pct(-1));
    lv_obj_set_align(ui_STARTIRAttackUni8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_STARTIRAttackUni8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_STARTIRAttackUni8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_STARTIRAttackUni8, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_STARTIRAttackUni8, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_STARTIRAttackUni8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_STARTIRAttackUni8, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_STARTIRAttackUni8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_STARTIRAttackUni8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_STARTIRAttackUni8, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_STARTIRAttackUni8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_STARTIRAttackUni8, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_STARTIRAttackUni8, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_STARTIRAttackUni8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_STARTIRAttackUni8, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_STARTIRAttackUni8, lv_color_hex(0xFF0000),
                              LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_STARTIRAttackUni8, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_STARTIRAttackUni8, lv_color_hex(0x4FFF00),
                              LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_STARTIRAttackUni8, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    ui_Label303 = lv_label_create(ui_STARTIRAttackUni8);
    lv_obj_set_width(ui_Label303, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label303, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label303, 0);
    lv_obj_set_y(ui_Label303, -1);
    lv_obj_set_align(ui_Label303, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label303, "DELETE");
    lv_obj_set_style_text_font(ui_Label303, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label303, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label303, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_Button91, ui_event_Button91, LV_EVENT_ALL, NULL);

}

void ui_CCSendSavedAction_screen_destroy(void)
{
    if(ui_CCSendSavedAction) lv_obj_del(ui_CCSendSavedAction);

    // NULL screen variables
    ui_CCSendSavedAction = NULL;
    ui_Button91 = NULL;
    ui_Label301 = NULL;
    ui_STARTIRAttackUni7 = NULL;
    ui_Label302 = NULL;
    ui_STARTIRAttackUni8 = NULL;
    ui_Label303 = NULL;

}
