// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_Display = NULL;
lv_obj_t * ui_BACKToSYSTEM3 = NULL;
lv_obj_t * ui_Label319 = NULL;
lv_obj_t * ui_Label320 = NULL;
lv_obj_t * ui_Label322 = NULL;
lv_obj_t * ui_ScreenTimeout = NULL;
lv_obj_t * ui_APPLYDISPLAYSETTINGS = NULL;
lv_obj_t * ui_Label323 = NULL;
lv_obj_t * ui_BrightnessDropdown = NULL;
// event funtions
void ui_event_BACKToSYSTEM3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainMenu_screen_init);
    }
}

// build funtions

void ui_Display_screen_init(void)
{
    ui_Display = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Display, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Display, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Display, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACKToSYSTEM3 = lv_btn_create(ui_Display);
    lv_obj_set_width(ui_BACKToSYSTEM3, 69);
    lv_obj_set_height(ui_BACKToSYSTEM3, 25);
    lv_obj_set_y(ui_BACKToSYSTEM3, -100);
    lv_obj_set_x(ui_BACKToSYSTEM3, lv_pct(-37));
    lv_obj_set_align(ui_BACKToSYSTEM3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACKToSYSTEM3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACKToSYSTEM3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACKToSYSTEM3, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACKToSYSTEM3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACKToSYSTEM3, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACKToSYSTEM3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BACKToSYSTEM3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BACKToSYSTEM3, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BACKToSYSTEM3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BACKToSYSTEM3, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BACKToSYSTEM3, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BACKToSYSTEM3, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BACKToSYSTEM3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BACKToSYSTEM3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BACKToSYSTEM3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label319 = lv_label_create(ui_BACKToSYSTEM3);
    lv_obj_set_width(ui_Label319, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label319, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label319, -1);
    lv_obj_set_y(ui_Label319, 1);
    lv_obj_set_align(ui_Label319, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label319, "BACK");
    lv_obj_set_style_text_font(ui_Label319, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label319, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label319, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label320 = lv_label_create(ui_Display);
    lv_obj_set_width(ui_Label320, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label320, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label320, 5);
    lv_obj_set_y(ui_Label320, -61);
    lv_obj_set_align(ui_Label320, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label320, "BRIGHTNESS:");
    lv_obj_set_style_text_color(ui_Label320, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label320, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label320, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label320, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label320, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label322 = lv_label_create(ui_Display);
    lv_obj_set_width(ui_Label322, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label322, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label322, 6);
    lv_obj_set_y(ui_Label322, 2);
    lv_obj_set_align(ui_Label322, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label322, "SCREEN TIMEOUT:");
    lv_obj_set_style_text_color(ui_Label322, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label322, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label322, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label322, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label322, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_ScreenTimeout = lv_dropdown_create(ui_Display);
    lv_dropdown_set_options(ui_ScreenTimeout, "1 min\n5 min\nNever");
    lv_obj_set_width(ui_ScreenTimeout, 252);
    lv_obj_set_height(ui_ScreenTimeout, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScreenTimeout, 1);
    lv_obj_set_y(ui_ScreenTimeout, 36);
    lv_obj_set_align(ui_ScreenTimeout, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScreenTimeout, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_bg_color(ui_ScreenTimeout, lv_color_hex(0x0B00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenTimeout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ScreenTimeout, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScreenTimeout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenTimeout, lv_color_hex(0xA600FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_ScreenTimeout, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_ScreenTimeout, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_ScreenTimeout, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_APPLYDISPLAYSETTINGS = lv_btn_create(ui_Display);
    lv_obj_set_height(ui_APPLYDISPLAYSETTINGS, 31);
    lv_obj_set_width(ui_APPLYDISPLAYSETTINGS, lv_pct(40));
    lv_obj_set_y(ui_APPLYDISPLAYSETTINGS, 90);
    lv_obj_set_x(ui_APPLYDISPLAYSETTINGS, lv_pct(0));
    lv_obj_set_align(ui_APPLYDISPLAYSETTINGS, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_APPLYDISPLAYSETTINGS, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_APPLYDISPLAYSETTINGS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_APPLYDISPLAYSETTINGS, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_APPLYDISPLAYSETTINGS, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_APPLYDISPLAYSETTINGS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_APPLYDISPLAYSETTINGS, lv_color_hex(0x00FF48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_APPLYDISPLAYSETTINGS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_APPLYDISPLAYSETTINGS, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_APPLYDISPLAYSETTINGS, lv_color_hex(0x94FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_APPLYDISPLAYSETTINGS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_APPLYDISPLAYSETTINGS, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_APPLYDISPLAYSETTINGS, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_APPLYDISPLAYSETTINGS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_APPLYDISPLAYSETTINGS, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label323 = lv_label_create(ui_APPLYDISPLAYSETTINGS);
    lv_obj_set_width(ui_Label323, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label323, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label323, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label323, "APPLY");
    lv_obj_set_style_text_font(ui_Label323, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label323, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label323, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BrightnessDropdown = lv_dropdown_create(ui_Display);
    lv_dropdown_set_options(ui_BrightnessDropdown, "100%\n75%\n50%");
    lv_obj_set_width(ui_BrightnessDropdown, 252);
    lv_obj_set_height(ui_BrightnessDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrightnessDropdown, 0);
    lv_obj_set_y(ui_BrightnessDropdown, -31);
    lv_obj_set_align(ui_BrightnessDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrightnessDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_bg_color(ui_BrightnessDropdown, lv_color_hex(0x0B00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessDropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BrightnessDropdown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BrightnessDropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrightnessDropdown, lv_color_hex(0xA600FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BrightnessDropdown, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_BrightnessDropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_BrightnessDropdown, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_BACKToSYSTEM3, ui_event_BACKToSYSTEM3, LV_EVENT_ALL, NULL);

}

void ui_Display_screen_destroy(void)
{
    if(ui_Display) lv_obj_del(ui_Display);

    // NULL screen variables
    ui_Display = NULL;
    ui_BACKToSYSTEM3 = NULL;
    ui_Label319 = NULL;
    ui_Label320 = NULL;
    ui_Label322 = NULL;
    ui_ScreenTimeout = NULL;
    ui_APPLYDISPLAYSETTINGS = NULL;
    ui_Label323 = NULL;
    ui_BrightnessDropdown = NULL;

}
