// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_DeviceInfo = NULL;
lv_obj_t * ui_BACKToSYSTEM1 = NULL;
lv_obj_t * ui_Label78 = NULL;
lv_obj_t * ui_Label79 = NULL;
lv_obj_t * ui_Label80 = NULL;
lv_obj_t * ui_Label81 = NULL;
lv_obj_t * ui_Label82 = NULL;
lv_obj_t * ui_DeviceInfoFirmware = NULL;
lv_obj_t * ui_DeviceInfoTemp = NULL;
lv_obj_t * ui_DeviceInfoBattery = NULL;
lv_obj_t * ui_DeviceInfoPSRAMFREE = NULL;
// event funtions
void ui_event_BACKToSYSTEM1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SYSTEM, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SYSTEM_screen_init);
    }
}

// build funtions

void ui_DeviceInfo_screen_init(void)
{
    ui_DeviceInfo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DeviceInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DeviceInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DeviceInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACKToSYSTEM1 = lv_btn_create(ui_DeviceInfo);
    lv_obj_set_width(ui_BACKToSYSTEM1, 69);
    lv_obj_set_height(ui_BACKToSYSTEM1, 25);
    lv_obj_set_y(ui_BACKToSYSTEM1, -100);
    lv_obj_set_x(ui_BACKToSYSTEM1, lv_pct(-37));
    lv_obj_set_align(ui_BACKToSYSTEM1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACKToSYSTEM1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACKToSYSTEM1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACKToSYSTEM1, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACKToSYSTEM1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACKToSYSTEM1, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACKToSYSTEM1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BACKToSYSTEM1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BACKToSYSTEM1, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BACKToSYSTEM1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BACKToSYSTEM1, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BACKToSYSTEM1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BACKToSYSTEM1, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BACKToSYSTEM1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BACKToSYSTEM1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BACKToSYSTEM1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label78 = lv_label_create(ui_BACKToSYSTEM1);
    lv_obj_set_width(ui_Label78, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label78, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label78, -1);
    lv_obj_set_y(ui_Label78, 1);
    lv_obj_set_align(ui_Label78, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label78, "BACK");
    lv_obj_set_style_text_font(ui_Label78, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label78, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label78, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label79 = lv_label_create(ui_DeviceInfo);
    lv_obj_set_width(ui_Label79, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label79, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label79, 9);
    lv_obj_set_y(ui_Label79, -50);
    lv_obj_set_align(ui_Label79, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label79, "FIRMWARE:");
    lv_obj_set_style_text_color(ui_Label79, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label79, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label79, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label79, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label79, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label80 = lv_label_create(ui_DeviceInfo);
    lv_obj_set_width(ui_Label80, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label80, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label80, 9);
    lv_obj_set_y(ui_Label80, -17);
    lv_obj_set_align(ui_Label80, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label80, "CPU TEMP:");
    lv_obj_set_style_text_color(ui_Label80, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label80, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label80, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label80, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label80, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label81 = lv_label_create(ui_DeviceInfo);
    lv_obj_set_width(ui_Label81, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label81, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label81, 9);
    lv_obj_set_y(ui_Label81, 17);
    lv_obj_set_align(ui_Label81, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label81, "BATTERY:");
    lv_obj_set_style_text_color(ui_Label81, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label81, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label81, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label81, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label81, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label82 = lv_label_create(ui_DeviceInfo);
    lv_obj_set_width(ui_Label82, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label82, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label82, 9);
    lv_obj_set_y(ui_Label82, 54);
    lv_obj_set_align(ui_Label82, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label82, "PSRAM FREE:");
    lv_obj_set_style_text_color(ui_Label82, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label82, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label82, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label82, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label82, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_DeviceInfoFirmware = lv_label_create(ui_DeviceInfo);
    lv_obj_set_width(ui_DeviceInfoFirmware, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DeviceInfoFirmware, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DeviceInfoFirmware, 138);
    lv_obj_set_y(ui_DeviceInfoFirmware, -51);
    lv_obj_set_align(ui_DeviceInfoFirmware, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DeviceInfoFirmware, "Fliphack v1.0");
    lv_obj_set_style_text_color(ui_DeviceInfoFirmware, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DeviceInfoFirmware, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DeviceInfoFirmware, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_DeviceInfoFirmware, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_DeviceInfoFirmware, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_DeviceInfoTemp = lv_label_create(ui_DeviceInfo);
    lv_obj_set_width(ui_DeviceInfoTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DeviceInfoTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DeviceInfoTemp, 126);
    lv_obj_set_y(ui_DeviceInfoTemp, -16);
    lv_obj_set_align(ui_DeviceInfoTemp, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DeviceInfoTemp, "45°C");
    lv_obj_set_style_text_color(ui_DeviceInfoTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DeviceInfoTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DeviceInfoTemp, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_DeviceInfoTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_DeviceInfoTemp, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_DeviceInfoBattery = lv_label_create(ui_DeviceInfo);
    lv_obj_set_width(ui_DeviceInfoBattery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DeviceInfoBattery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DeviceInfoBattery, 112);
    lv_obj_set_y(ui_DeviceInfoBattery, 17);
    lv_obj_set_align(ui_DeviceInfoBattery, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DeviceInfoBattery, "87% (3.9V)");
    lv_obj_set_style_text_color(ui_DeviceInfoBattery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DeviceInfoBattery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DeviceInfoBattery, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_DeviceInfoBattery, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_DeviceInfoBattery, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_DeviceInfoPSRAMFREE = lv_label_create(ui_DeviceInfo);
    lv_obj_set_width(ui_DeviceInfoPSRAMFREE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DeviceInfoPSRAMFREE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DeviceInfoPSRAMFREE, 151);
    lv_obj_set_y(ui_DeviceInfoPSRAMFREE, 54);
    lv_obj_set_align(ui_DeviceInfoPSRAMFREE, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DeviceInfoPSRAMFREE, "7.8 MB");
    lv_obj_set_style_text_color(ui_DeviceInfoPSRAMFREE, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DeviceInfoPSRAMFREE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DeviceInfoPSRAMFREE, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_DeviceInfoPSRAMFREE, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_DeviceInfoPSRAMFREE, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_BACKToSYSTEM1, ui_event_BACKToSYSTEM1, LV_EVENT_ALL, NULL);

}

void ui_DeviceInfo_screen_destroy(void)
{
    if(ui_DeviceInfo) lv_obj_del(ui_DeviceInfo);

    // NULL screen variables
    ui_DeviceInfo = NULL;
    ui_BACKToSYSTEM1 = NULL;
    ui_Label78 = NULL;
    ui_Label79 = NULL;
    ui_Label80 = NULL;
    ui_Label81 = NULL;
    ui_Label82 = NULL;
    ui_DeviceInfoFirmware = NULL;
    ui_DeviceInfoTemp = NULL;
    ui_DeviceInfoBattery = NULL;
    ui_DeviceInfoPSRAMFREE = NULL;

}
