// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_DISPLAY_H
#define UI_DISPLAY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Display
extern void ui_Display_screen_init(void);
extern void ui_Display_screen_destroy(void);
extern lv_obj_t * ui_Display;
extern void ui_event_BACKToSYSTEM3(lv_event_t * e);
extern lv_obj_t * ui_BACKToSYSTEM3;
extern lv_obj_t * ui_Label319;
extern lv_obj_t * ui_Label320;
extern lv_obj_t * ui_Label322;
extern lv_obj_t * ui_ScreenTimeout;
extern lv_obj_t * ui_APPLYDISPLAYSETTINGS;
extern lv_obj_t * ui_Label323;
extern lv_obj_t * ui_BrightnessDropdown;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

