// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_DeauthAttack = NULL;
lv_obj_t * ui_Label120 = NULL;
lv_obj_t * ui_BACKWifi1 = NULL;
lv_obj_t * ui_Label100 = NULL;
lv_obj_t * ui_WifiTargetSelect5 = NULL;
lv_obj_t * ui_Label118 = NULL;
lv_obj_t * ui_DeauthAttackTarget = NULL;
lv_obj_t * ui_DeauthAttackSTATUS = NULL;
lv_obj_t * ui_Label122 = NULL;
lv_obj_t * ui_DeauthAttackPKTS = NULL;
lv_obj_t * ui_DeauthAttackSTART = NULL;
lv_obj_t * ui_Label124 = NULL;
lv_obj_t * ui_DeauthAttackCAPTUREHANDSHAKE = NULL;
lv_obj_t * ui_Label125 = NULL;
lv_obj_t * ui_Label126 = NULL;
lv_obj_t * ui_Label127 = NULL;
lv_obj_t * ui_DeauthAttackClientMac = NULL;
lv_obj_t * ui_Label129 = NULL;
lv_obj_t * ui_DeauthAttackTIMER = NULL;
// event funtions
void ui_event_BACKWifi1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WiFiMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WiFiMenu_screen_init);
    }
}

void ui_event_WifiTargetSelect5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScanAPs, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScanAPs_screen_init);
    }
}

// build funtions

void ui_DeauthAttack_screen_init(void)
{
    ui_DeauthAttack = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DeauthAttack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DeauthAttack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DeauthAttack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label120 = lv_label_create(ui_DeauthAttack);
    lv_obj_set_width(ui_Label120, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label120, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label120, -98);
    lv_obj_set_y(ui_Label120, -68);
    lv_obj_set_align(ui_Label120, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label120, "STATUS:");
    lv_obj_set_style_text_color(ui_Label120, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label120, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label120, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label120, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label120, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BACKWifi1 = lv_btn_create(ui_DeauthAttack);
    lv_obj_set_width(ui_BACKWifi1, 69);
    lv_obj_set_height(ui_BACKWifi1, 25);
    lv_obj_set_y(ui_BACKWifi1, -100);
    lv_obj_set_x(ui_BACKWifi1, lv_pct(-37));
    lv_obj_set_align(ui_BACKWifi1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACKWifi1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACKWifi1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACKWifi1, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACKWifi1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACKWifi1, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACKWifi1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BACKWifi1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BACKWifi1, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BACKWifi1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BACKWifi1, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BACKWifi1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BACKWifi1, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BACKWifi1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BACKWifi1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BACKWifi1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label100 = lv_label_create(ui_BACKWifi1);
    lv_obj_set_width(ui_Label100, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label100, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label100, 0);
    lv_obj_set_y(ui_Label100, 1);
    lv_obj_set_align(ui_Label100, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label100, "BACK");
    lv_obj_set_style_text_font(ui_Label100, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label100, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label100, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_WifiTargetSelect5 = lv_btn_create(ui_DeauthAttack);
    lv_obj_set_width(ui_WifiTargetSelect5, 194);
    lv_obj_set_height(ui_WifiTargetSelect5, 25);
    lv_obj_set_y(ui_WifiTargetSelect5, -101);
    lv_obj_set_x(ui_WifiTargetSelect5, lv_pct(13));
    lv_obj_set_align(ui_WifiTargetSelect5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiTargetSelect5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WifiTargetSelect5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiTargetSelect5, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiTargetSelect5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WifiTargetSelect5, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WifiTargetSelect5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WifiTargetSelect5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_WifiTargetSelect5, lv_color_hex(0xE90000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiTargetSelect5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiTargetSelect5, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_WifiTargetSelect5, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_WifiTargetSelect5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_WifiTargetSelect5, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label118 = lv_label_create(ui_WifiTargetSelect5);
    lv_obj_set_width(ui_Label118, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label118, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label118, -53);
    lv_obj_set_y(ui_Label118, 0);
    lv_obj_set_align(ui_Label118, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label118, "TARGET: ");
    lv_obj_set_style_text_color(ui_Label118, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label118, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label118, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label118, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label118, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_DeauthAttackTarget = lv_label_create(ui_WifiTargetSelect5);
    lv_obj_set_width(ui_DeauthAttackTarget, 107);
    lv_obj_set_height(ui_DeauthAttackTarget, 15);
    lv_obj_set_x(ui_DeauthAttackTarget, 65);
    lv_obj_set_y(ui_DeauthAttackTarget, -2);
    lv_obj_set_align(ui_DeauthAttackTarget, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_DeauthAttackTarget, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_DeauthAttackTarget, "NONE");
    lv_obj_set_style_text_font(ui_DeauthAttackTarget, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_DeauthAttackTarget, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_DeauthAttackTarget, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_DeauthAttackSTATUS = lv_label_create(ui_DeauthAttack);
    lv_obj_set_width(ui_DeauthAttackSTATUS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DeauthAttackSTATUS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DeauthAttackSTATUS, 140);
    lv_obj_set_y(ui_DeauthAttackSTATUS, -68);
    lv_obj_set_align(ui_DeauthAttackSTATUS, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DeauthAttackSTATUS, "STANDBY");
    lv_obj_set_style_text_color(ui_DeauthAttackSTATUS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DeauthAttackSTATUS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DeauthAttackSTATUS, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_DeauthAttackSTATUS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_DeauthAttackSTATUS, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label122 = lv_label_create(ui_DeauthAttack);
    lv_obj_set_width(ui_Label122, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label122, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label122, -84);
    lv_obj_set_y(ui_Label122, -39);
    lv_obj_set_align(ui_Label122, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label122, "PKTS SENT:");
    lv_obj_set_style_text_color(ui_Label122, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label122, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label122, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label122, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label122, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_DeauthAttackPKTS = lv_label_create(ui_DeauthAttack);
    lv_obj_set_width(ui_DeauthAttackPKTS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DeauthAttackPKTS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DeauthAttackPKTS, 50);
    lv_obj_set_y(ui_DeauthAttackPKTS, -40);
    lv_obj_set_align(ui_DeauthAttackPKTS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DeauthAttackPKTS, "0");
    lv_obj_set_style_text_color(ui_DeauthAttackPKTS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DeauthAttackPKTS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DeauthAttackPKTS, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_DeauthAttackPKTS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_DeauthAttackPKTS, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_DeauthAttackSTART = lv_btn_create(ui_DeauthAttack);
    lv_obj_set_height(ui_DeauthAttackSTART, 31);
    lv_obj_set_width(ui_DeauthAttackSTART, lv_pct(40));
    lv_obj_set_y(ui_DeauthAttackSTART, 32);
    lv_obj_set_x(ui_DeauthAttackSTART, lv_pct(-1));
    lv_obj_set_align(ui_DeauthAttackSTART, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DeauthAttackSTART, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DeauthAttackSTART, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DeauthAttackSTART, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DeauthAttackSTART, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DeauthAttackSTART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DeauthAttackSTART, lv_color_hex(0x00FF48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DeauthAttackSTART, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DeauthAttackSTART, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_DeauthAttackSTART, lv_color_hex(0x94FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DeauthAttackSTART, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DeauthAttackSTART, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_DeauthAttackSTART, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_DeauthAttackSTART, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_DeauthAttackSTART, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label124 = lv_label_create(ui_DeauthAttackSTART);
    lv_obj_set_width(ui_Label124, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label124, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label124, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label124, "START");
    lv_obj_set_style_text_font(ui_Label124, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label124, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label124, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_DeauthAttackCAPTUREHANDSHAKE = lv_btn_create(ui_DeauthAttack);
    lv_obj_set_height(ui_DeauthAttackCAPTUREHANDSHAKE, 31);
    lv_obj_set_width(ui_DeauthAttackCAPTUREHANDSHAKE, lv_pct(18));
    lv_obj_set_y(ui_DeauthAttackCAPTUREHANDSHAKE, -6);
    lv_obj_set_x(ui_DeauthAttackCAPTUREHANDSHAKE, lv_pct(40));
    lv_obj_set_align(ui_DeauthAttackCAPTUREHANDSHAKE, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DeauthAttackCAPTUREHANDSHAKE, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DeauthAttackCAPTUREHANDSHAKE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DeauthAttackCAPTUREHANDSHAKE, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DeauthAttackCAPTUREHANDSHAKE, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DeauthAttackCAPTUREHANDSHAKE, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DeauthAttackCAPTUREHANDSHAKE, lv_color_hex(0xB20D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DeauthAttackCAPTUREHANDSHAKE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DeauthAttackCAPTUREHANDSHAKE, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_DeauthAttackCAPTUREHANDSHAKE, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DeauthAttackCAPTUREHANDSHAKE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DeauthAttackCAPTUREHANDSHAKE, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_DeauthAttackCAPTUREHANDSHAKE, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_DeauthAttackCAPTUREHANDSHAKE, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_DeauthAttackCAPTUREHANDSHAKE, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label125 = lv_label_create(ui_DeauthAttackCAPTUREHANDSHAKE);
    lv_obj_set_width(ui_Label125, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label125, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label125, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label125, "OFF");
    lv_obj_set_style_text_font(ui_Label125, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label125, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label125, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label126 = lv_label_create(ui_DeauthAttack);
    lv_obj_set_width(ui_Label126, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label126, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label126, 5);
    lv_obj_set_y(ui_Label126, -6);
    lv_obj_set_align(ui_Label126, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label126, "CAPTURE HANDSHAKE:");
    lv_obj_set_style_text_color(ui_Label126, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label126, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label126, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label126, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label126, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label127 = lv_label_create(ui_DeauthAttack);
    lv_obj_set_width(ui_Label127, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label127, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label127, 4);
    lv_obj_set_y(ui_Label127, 68);
    lv_obj_set_align(ui_Label127, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label127, "CLIENT:");
    lv_obj_set_style_text_color(ui_Label127, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label127, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label127, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label127, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label127, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_DeauthAttackClientMac = lv_label_create(ui_DeauthAttack);
    lv_obj_set_height(ui_DeauthAttackClientMac, 23);
    lv_obj_set_width(ui_DeauthAttackClientMac, lv_pct(70));
    lv_obj_set_x(ui_DeauthAttackClientMac, 80);
    lv_obj_set_y(ui_DeauthAttackClientMac, 70);
    lv_obj_set_align(ui_DeauthAttackClientMac, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DeauthAttackClientMac, "FF:FF:FF:FF:FF:FF");
    lv_obj_set_style_text_color(ui_DeauthAttackClientMac, lv_color_hex(0x26FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DeauthAttackClientMac, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DeauthAttackClientMac, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_DeauthAttackClientMac, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_DeauthAttackClientMac, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label129 = lv_label_create(ui_DeauthAttack);
    lv_obj_set_width(ui_Label129, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label129, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label129, 4);
    lv_obj_set_y(ui_Label129, 98);
    lv_obj_set_align(ui_Label129, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label129, "TIMER:");
    lv_obj_set_style_text_color(ui_Label129, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label129, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label129, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label129, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label129, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_DeauthAttackTIMER = lv_label_create(ui_DeauthAttack);
    lv_obj_set_width(ui_DeauthAttackTIMER, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DeauthAttackTIMER, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DeauthAttackTIMER, 130);
    lv_obj_set_y(ui_DeauthAttackTIMER, 99);
    lv_obj_set_align(ui_DeauthAttackTIMER, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DeauthAttackTIMER, "00:00");
    lv_obj_set_style_text_color(ui_DeauthAttackTIMER, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DeauthAttackTIMER, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DeauthAttackTIMER, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_DeauthAttackTIMER, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_DeauthAttackTIMER, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_BACKWifi1, ui_event_BACKWifi1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiTargetSelect5, ui_event_WifiTargetSelect5, LV_EVENT_ALL, NULL);

}

void ui_DeauthAttack_screen_destroy(void)
{
    if(ui_DeauthAttack) lv_obj_del(ui_DeauthAttack);

    // NULL screen variables
    ui_DeauthAttack = NULL;
    ui_Label120 = NULL;
    ui_BACKWifi1 = NULL;
    ui_Label100 = NULL;
    ui_WifiTargetSelect5 = NULL;
    ui_Label118 = NULL;
    ui_DeauthAttackTarget = NULL;
    ui_DeauthAttackSTATUS = NULL;
    ui_Label122 = NULL;
    ui_DeauthAttackPKTS = NULL;
    ui_DeauthAttackSTART = NULL;
    ui_Label124 = NULL;
    ui_DeauthAttackCAPTUREHANDSHAKE = NULL;
    ui_Label125 = NULL;
    ui_Label126 = NULL;
    ui_Label127 = NULL;
    ui_DeauthAttackClientMac = NULL;
    ui_Label129 = NULL;
    ui_DeauthAttackTIMER = NULL;

}
