// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_EVILTWIN_H
#define UI_EVILTWIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_EvilTwin
extern void ui_EvilTwin_screen_init(void);
extern void ui_EvilTwin_screen_destroy(void);
extern lv_obj_t * ui_EvilTwin;
extern void ui_event_BACKWifi3(lv_event_t * e);
extern lv_obj_t * ui_BACKWifi3;
extern lv_obj_t * ui_Label102;
extern lv_obj_t * ui_Label155;
extern lv_obj_t * ui_EvilTwinSTART;
extern lv_obj_t * ui_Label156;
extern void ui_event_WifiTargetSelect4(lv_event_t * e);
extern lv_obj_t * ui_WifiTargetSelect4;
extern lv_obj_t * ui_Label157;
extern lv_obj_t * ui_EvilTwinTarget;
extern void ui_event_Button88(lv_event_t * e);
extern lv_obj_t * ui_Button88;
extern lv_obj_t * ui_Label160;
extern lv_obj_t * ui_EVILTwinPortal;
extern lv_obj_t * ui_Label159;
extern lv_obj_t * ui_Label162;
extern lv_obj_t * ui_Label163;
extern lv_obj_t * ui_EvilTwinTIMER;
extern lv_obj_t * ui_EvilTwinSTATUS;
extern lv_obj_t * ui_EvilTwinCLIENTS;
extern lv_obj_t * ui_EvilTwinCREDS;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

