// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_FREQANALYZER_H
#define UI_FREQANALYZER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_FREQAnalyzer
extern void ui_FREQAnalyzer_screen_init(void);
extern void ui_FREQAnalyzer_screen_destroy(void);
extern lv_obj_t * ui_FREQAnalyzer;
extern void ui_event_BackToSubGHzMenu2(lv_event_t * e);
extern lv_obj_t * ui_BackToSubGHzMenu2;
extern lv_obj_t * ui_Label98;
extern lv_obj_t * ui_FREQAnalyzerCHART;
extern lv_obj_t * ui_Label304;
extern lv_obj_t * ui_FREQAnalyzerPEAK;
extern lv_obj_t * ui_Label306;
extern lv_obj_t * ui_FREQAnalyzerCENTERFREQ;
extern lv_obj_t * ui_Label308;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

