// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_FREQAnalyzer = NULL;
lv_obj_t * ui_BackToSubGHzMenu2 = NULL;
lv_obj_t * ui_Label98 = NULL;
lv_obj_t * ui_FREQAnalyzerCHART = NULL;
lv_obj_t * ui_Label304 = NULL;
lv_obj_t * ui_FREQAnalyzerPEAK = NULL;
lv_obj_t * ui_Label306 = NULL;
lv_obj_t * ui_FREQAnalyzerCENTERFREQ = NULL;
lv_obj_t * ui_Label308 = NULL;
// event funtions
void ui_event_BackToSubGHzMenu2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SubGhzMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SubGhzMenu_screen_init);
    }
}

// build funtions

void ui_FREQAnalyzer_screen_init(void)
{
    ui_FREQAnalyzer = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_FREQAnalyzer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_FREQAnalyzer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FREQAnalyzer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackToSubGHzMenu2 = lv_btn_create(ui_FREQAnalyzer);
    lv_obj_set_width(ui_BackToSubGHzMenu2, 69);
    lv_obj_set_height(ui_BackToSubGHzMenu2, 25);
    lv_obj_set_y(ui_BackToSubGHzMenu2, -100);
    lv_obj_set_x(ui_BackToSubGHzMenu2, lv_pct(-37));
    lv_obj_set_align(ui_BackToSubGHzMenu2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackToSubGHzMenu2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackToSubGHzMenu2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackToSubGHzMenu2, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackToSubGHzMenu2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BackToSubGHzMenu2, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BackToSubGHzMenu2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BackToSubGHzMenu2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BackToSubGHzMenu2, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackToSubGHzMenu2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackToSubGHzMenu2, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BackToSubGHzMenu2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BackToSubGHzMenu2, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BackToSubGHzMenu2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BackToSubGHzMenu2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BackToSubGHzMenu2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label98 = lv_label_create(ui_BackToSubGHzMenu2);
    lv_obj_set_width(ui_Label98, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label98, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label98, -1);
    lv_obj_set_y(ui_Label98, 1);
    lv_obj_set_align(ui_Label98, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label98, "BACK");
    lv_obj_set_style_text_font(ui_Label98, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label98, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label98, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_FREQAnalyzerCHART = lv_chart_create(ui_FREQAnalyzer);
    lv_obj_set_width(ui_FREQAnalyzerCHART, 207);
    lv_obj_set_height(ui_FREQAnalyzerCHART, 121);
    lv_obj_set_x(ui_FREQAnalyzerCHART, 0);
    lv_obj_set_y(ui_FREQAnalyzerCHART, 31);
    lv_obj_set_align(ui_FREQAnalyzerCHART, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_FREQAnalyzerCHART, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_FREQAnalyzerCHART, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_FREQAnalyzerCHART, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_FREQAnalyzerCHART, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_FREQAnalyzerCHART_series_1 = lv_chart_add_series(ui_FREQAnalyzerCHART, lv_color_hex(0xFFB200),
                                                                            LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_FREQAnalyzerCHART_series_1_array[] = { 0, 10, 20, 60, 80, 80, 40, 20, 100 };
    lv_chart_set_ext_y_array(ui_FREQAnalyzerCHART, ui_FREQAnalyzerCHART_series_1, ui_FREQAnalyzerCHART_series_1_array);
    lv_obj_set_style_bg_color(ui_FREQAnalyzerCHART, lv_color_hex(0x000DFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FREQAnalyzerCHART, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_FREQAnalyzerCHART, lv_color_hex(0x2400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_FREQAnalyzerCHART, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_color(ui_FREQAnalyzerCHART, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_FREQAnalyzerCHART, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_FREQAnalyzerCHART, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_FREQAnalyzerCHART, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_FREQAnalyzerCHART, lv_color_hex(0x40FF42), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_FREQAnalyzerCHART, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_FREQAnalyzerCHART, lv_color_hex(0xE6FF00), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FREQAnalyzerCHART, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Label304 = lv_label_create(ui_FREQAnalyzer);
    lv_obj_set_width(ui_Label304, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label304, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label304, 8);
    lv_obj_set_y(ui_Label304, -46);
    lv_obj_set_align(ui_Label304, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label304, "Peak:");
    lv_obj_set_style_text_color(ui_Label304, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label304, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label304, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label304, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label304, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_FREQAnalyzerPEAK = lv_label_create(ui_FREQAnalyzer);
    lv_obj_set_width(ui_FREQAnalyzerPEAK, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FREQAnalyzerPEAK, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FREQAnalyzerPEAK, 132);
    lv_obj_set_y(ui_FREQAnalyzerPEAK, -46);
    lv_obj_set_align(ui_FREQAnalyzerPEAK, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_FREQAnalyzerPEAK, "-70dBm");
    lv_obj_set_style_text_color(ui_FREQAnalyzerPEAK, lv_color_hex(0x08FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FREQAnalyzerPEAK, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FREQAnalyzerPEAK, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_FREQAnalyzerPEAK, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_FREQAnalyzerPEAK, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label306 = lv_label_create(ui_FREQAnalyzer);
    lv_obj_set_width(ui_Label306, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label306, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label306, 8);
    lv_obj_set_y(ui_Label306, -69);
    lv_obj_set_align(ui_Label306, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label306, "Center Freq:");
    lv_obj_set_style_text_color(ui_Label306, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label306, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label306, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label306, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label306, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_FREQAnalyzerCENTERFREQ = lv_label_create(ui_FREQAnalyzer);
    lv_obj_set_width(ui_FREQAnalyzerCENTERFREQ, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FREQAnalyzerCENTERFREQ, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FREQAnalyzerCENTERFREQ, 125);
    lv_obj_set_y(ui_FREQAnalyzerCENTERFREQ, -69);
    lv_obj_set_align(ui_FREQAnalyzerCENTERFREQ, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_FREQAnalyzerCENTERFREQ, "433.92MHz");
    lv_obj_set_style_text_color(ui_FREQAnalyzerCENTERFREQ, lv_color_hex(0x00FF0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FREQAnalyzerCENTERFREQ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FREQAnalyzerCENTERFREQ, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_FREQAnalyzerCENTERFREQ, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_FREQAnalyzerCENTERFREQ, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label308 = lv_label_create(ui_FREQAnalyzer);
    lv_obj_set_width(ui_Label308, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label308, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label308, 84);
    lv_obj_set_y(ui_Label308, -99);
    lv_obj_set_align(ui_Label308, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label308, "Frequency Analyzer");
    lv_obj_set_style_text_color(ui_Label308, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label308, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label308, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label308, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label308, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_BackToSubGHzMenu2, ui_event_BackToSubGHzMenu2, LV_EVENT_ALL, NULL);

}

void ui_FREQAnalyzer_screen_destroy(void)
{
    if(ui_FREQAnalyzer) lv_obj_del(ui_FREQAnalyzer);

    // NULL screen variables
    ui_FREQAnalyzer = NULL;
    ui_BackToSubGHzMenu2 = NULL;
    ui_Label98 = NULL;
    ui_FREQAnalyzerCHART = NULL;
    ui_Label304 = NULL;
    ui_FREQAnalyzerPEAK = NULL;
    ui_Label306 = NULL;
    ui_FREQAnalyzerCENTERFREQ = NULL;
    ui_Label308 = NULL;

}
