// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_FORMATSD_H
#define UI_FORMATSD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_FormatSD
extern void ui_FormatSD_screen_init(void);
extern void ui_FormatSD_screen_destroy(void);
extern lv_obj_t * ui_FormatSD;
extern void ui_event_BACKToSD2(lv_event_t * e);
extern lv_obj_t * ui_BACKToSD2;
extern lv_obj_t * ui_Label136;
extern lv_obj_t * ui_Label216;
extern lv_obj_t * ui_Label217;
extern lv_obj_t * ui_FORMATSDFORMAT;
extern lv_obj_t * ui_Label218;
extern lv_obj_t * ui_FormatSDCANCEL;
extern lv_obj_t * ui_Label219;
extern lv_obj_t * ui_Label220;
extern lv_obj_t * ui_FormatSDStatus;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

