// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_FormatSD = NULL;
lv_obj_t * ui_BACKToSD2 = NULL;
lv_obj_t * ui_Label136 = NULL;
lv_obj_t * ui_Label216 = NULL;
lv_obj_t * ui_Label217 = NULL;
lv_obj_t * ui_FORMATSDFORMAT = NULL;
lv_obj_t * ui_Label218 = NULL;
lv_obj_t * ui_FormatSDCANCEL = NULL;
lv_obj_t * ui_Label219 = NULL;
lv_obj_t * ui_Label220 = NULL;
lv_obj_t * ui_FormatSDStatus = NULL;
// event funtions
void ui_event_BACKToSD2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SDCard, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SDCard_screen_init);
    }
}

// build funtions

void ui_FormatSD_screen_init(void)
{
    ui_FormatSD = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_FormatSD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_FormatSD, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FormatSD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACKToSD2 = lv_btn_create(ui_FormatSD);
    lv_obj_set_width(ui_BACKToSD2, 69);
    lv_obj_set_height(ui_BACKToSD2, 25);
    lv_obj_set_y(ui_BACKToSD2, -100);
    lv_obj_set_x(ui_BACKToSD2, lv_pct(-37));
    lv_obj_set_align(ui_BACKToSD2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACKToSD2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACKToSD2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACKToSD2, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACKToSD2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACKToSD2, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACKToSD2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BACKToSD2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BACKToSD2, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BACKToSD2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BACKToSD2, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BACKToSD2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BACKToSD2, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BACKToSD2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BACKToSD2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BACKToSD2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label136 = lv_label_create(ui_BACKToSD2);
    lv_obj_set_width(ui_Label136, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label136, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label136, -1);
    lv_obj_set_y(ui_Label136, 1);
    lv_obj_set_align(ui_Label136, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label136, "BACK");
    lv_obj_set_style_text_font(ui_Label136, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label136, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label136, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label216 = lv_label_create(ui_FormatSD);
    lv_obj_set_width(ui_Label216, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label216, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label216, 84);
    lv_obj_set_y(ui_Label216, -66);
    lv_obj_set_align(ui_Label216, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label216, "WARNING:");
    lv_obj_set_style_text_color(ui_Label216, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label216, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label216, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label216, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label216, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label217 = lv_label_create(ui_FormatSD);
    lv_obj_set_width(ui_Label217, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label217, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label217, 34);
    lv_obj_set_y(ui_Label217, -30);
    lv_obj_set_align(ui_Label217, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label217, "All data will be erased!");
    lv_obj_set_style_text_color(ui_Label217, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label217, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label217, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label217, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label217, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_FORMATSDFORMAT = lv_btn_create(ui_FormatSD);
    lv_obj_set_height(ui_FORMATSDFORMAT, 31);
    lv_obj_set_width(ui_FORMATSDFORMAT, lv_pct(40));
    lv_obj_set_y(ui_FORMATSDFORMAT, 58);
    lv_obj_set_x(ui_FORMATSDFORMAT, lv_pct(-1));
    lv_obj_set_align(ui_FORMATSDFORMAT, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FORMATSDFORMAT, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_FORMATSDFORMAT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FORMATSDFORMAT, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FORMATSDFORMAT, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FORMATSDFORMAT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_FORMATSDFORMAT, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_FORMATSDFORMAT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_FORMATSDFORMAT, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_FORMATSDFORMAT, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FORMATSDFORMAT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FORMATSDFORMAT, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_FORMATSDFORMAT, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_FORMATSDFORMAT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_FORMATSDFORMAT, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label218 = lv_label_create(ui_FORMATSDFORMAT);
    lv_obj_set_width(ui_Label218, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label218, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label218, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label218, "FORMAT");
    lv_obj_set_style_text_font(ui_Label218, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label218, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label218, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_FormatSDCANCEL = lv_btn_create(ui_FormatSD);
    lv_obj_set_height(ui_FormatSDCANCEL, 31);
    lv_obj_set_width(ui_FormatSDCANCEL, lv_pct(40));
    lv_obj_set_y(ui_FormatSDCANCEL, 9);
    lv_obj_set_x(ui_FormatSDCANCEL, lv_pct(-1));
    lv_obj_set_align(ui_FormatSDCANCEL, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FormatSDCANCEL, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_FormatSDCANCEL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FormatSDCANCEL, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FormatSDCANCEL, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FormatSDCANCEL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_FormatSDCANCEL, lv_color_hex(0x00FF48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_FormatSDCANCEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_FormatSDCANCEL, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_FormatSDCANCEL, lv_color_hex(0x94FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FormatSDCANCEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FormatSDCANCEL, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_FormatSDCANCEL, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_FormatSDCANCEL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_FormatSDCANCEL, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label219 = lv_label_create(ui_FormatSDCANCEL);
    lv_obj_set_width(ui_Label219, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label219, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label219, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label219, "CANCEL");
    lv_obj_set_style_text_font(ui_Label219, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label219, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label219, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label220 = lv_label_create(ui_FormatSD);
    lv_obj_set_width(ui_Label220, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label220, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label220, 9);
    lv_obj_set_y(ui_Label220, 99);
    lv_obj_set_align(ui_Label220, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label220, "STATUS:");
    lv_obj_set_style_text_color(ui_Label220, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label220, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label220, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label220, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label220, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_FormatSDStatus = lv_label_create(ui_FormatSD);
    lv_obj_set_width(ui_FormatSDStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FormatSDStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FormatSDStatus, 99);
    lv_obj_set_y(ui_FormatSDStatus, 100);
    lv_obj_set_align(ui_FormatSDStatus, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_FormatSDStatus, "Waiting...");
    lv_obj_set_style_text_color(ui_FormatSDStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FormatSDStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FormatSDStatus, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_FormatSDStatus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_FormatSDStatus, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_BACKToSD2, ui_event_BACKToSD2, LV_EVENT_ALL, NULL);

}

void ui_FormatSD_screen_destroy(void)
{
    if(ui_FormatSD) lv_obj_del(ui_FormatSD);

    // NULL screen variables
    ui_FormatSD = NULL;
    ui_BACKToSD2 = NULL;
    ui_Label136 = NULL;
    ui_Label216 = NULL;
    ui_Label217 = NULL;
    ui_FORMATSDFORMAT = NULL;
    ui_Label218 = NULL;
    ui_FormatSDCANCEL = NULL;
    ui_Label219 = NULL;
    ui_Label220 = NULL;
    ui_FormatSDStatus = NULL;

}
