// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_GPSMENU_H
#define UI_GPSMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_GPSMenu
extern void ui_GPSMenu_screen_init(void);
extern void ui_GPSMenu_screen_destroy(void);
extern lv_obj_t * ui_GPSMenu;
extern void ui_event_BackToMainMenu6(lv_event_t * e);
extern lv_obj_t * ui_BackToMainMenu6;
extern lv_obj_t * ui_Label67;
extern void ui_event_StartWardrivingSelect(lv_event_t * e);
extern lv_obj_t * ui_StartWardrivingSelect;
extern lv_obj_t * ui_Label68;
extern void ui_event_SateliteInfoSelect(lv_event_t * e);
extern lv_obj_t * ui_SateliteInfoSelect;
extern lv_obj_t * ui_Label69;
extern void ui_event_SyncRTCTimeSelect(lv_event_t * e);
extern lv_obj_t * ui_SyncRTCTimeSelect;
extern lv_obj_t * ui_Label70;
extern void ui_event_NMEAConsoleSelect(lv_event_t * e);
extern lv_obj_t * ui_NMEAConsoleSelect;
extern lv_obj_t * ui_Label71;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

