// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_GPSMenu = NULL;
lv_obj_t * ui_BackToMainMenu6 = NULL;
lv_obj_t * ui_Label67 = NULL;
lv_obj_t * ui_StartWardrivingSelect = NULL;
lv_obj_t * ui_Label68 = NULL;
lv_obj_t * ui_SateliteInfoSelect = NULL;
lv_obj_t * ui_Label69 = NULL;
lv_obj_t * ui_SyncRTCTimeSelect = NULL;
lv_obj_t * ui_Label70 = NULL;
lv_obj_t * ui_NMEAConsoleSelect = NULL;
lv_obj_t * ui_Label71 = NULL;
// event funtions
void ui_event_BackToMainMenu6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainMenu_screen_init);
    }
}

void ui_event_StartWardrivingSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_StartWardriving, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_StartWardriving_screen_init);
    }
}

void ui_event_SateliteInfoSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SateliteInfo, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SateliteInfo_screen_init);
    }
}

void ui_event_SyncRTCTimeSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SyncRTCTime, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SyncRTCTime_screen_init);
    }
}

void ui_event_NMEAConsoleSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_NmeaConsole, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_NmeaConsole_screen_init);
    }
}

// build funtions

void ui_GPSMenu_screen_init(void)
{
    ui_GPSMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_GPSMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GPSMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GPSMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackToMainMenu6 = lv_btn_create(ui_GPSMenu);
    lv_obj_set_width(ui_BackToMainMenu6, 69);
    lv_obj_set_height(ui_BackToMainMenu6, 25);
    lv_obj_set_y(ui_BackToMainMenu6, -100);
    lv_obj_set_x(ui_BackToMainMenu6, lv_pct(-37));
    lv_obj_set_align(ui_BackToMainMenu6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackToMainMenu6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackToMainMenu6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackToMainMenu6, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackToMainMenu6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BackToMainMenu6, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BackToMainMenu6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BackToMainMenu6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BackToMainMenu6, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackToMainMenu6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackToMainMenu6, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BackToMainMenu6, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BackToMainMenu6, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BackToMainMenu6, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BackToMainMenu6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BackToMainMenu6, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label67 = lv_label_create(ui_BackToMainMenu6);
    lv_obj_set_width(ui_Label67, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label67, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label67, -1);
    lv_obj_set_y(ui_Label67, 1);
    lv_obj_set_align(ui_Label67, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label67, "BACK");
    lv_obj_set_style_text_font(ui_Label67, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label67, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label67, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_StartWardrivingSelect = lv_btn_create(ui_GPSMenu);
    lv_obj_set_height(ui_StartWardrivingSelect, 24);
    lv_obj_set_width(ui_StartWardrivingSelect, lv_pct(97));
    lv_obj_set_y(ui_StartWardrivingSelect, -9);
    lv_obj_set_x(ui_StartWardrivingSelect, lv_pct(0));
    lv_obj_set_align(ui_StartWardrivingSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StartWardrivingSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_StartWardrivingSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StartWardrivingSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StartWardrivingSelect, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StartWardrivingSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StartWardrivingSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StartWardrivingSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StartWardrivingSelect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_StartWardrivingSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StartWardrivingSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StartWardrivingSelect, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_StartWardrivingSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_StartWardrivingSelect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_StartWardrivingSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label68 = lv_label_create(ui_StartWardrivingSelect);
    lv_obj_set_width(ui_Label68, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label68, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label68, -11);
    lv_obj_set_y(ui_Label68, 0);
    lv_obj_set_align(ui_Label68, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label68, "START WARDRIVING");
    lv_obj_set_style_text_font(ui_Label68, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label68, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label68, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SateliteInfoSelect = lv_btn_create(ui_GPSMenu);
    lv_obj_set_height(ui_SateliteInfoSelect, 24);
    lv_obj_set_width(ui_SateliteInfoSelect, lv_pct(97));
    lv_obj_set_y(ui_SateliteInfoSelect, 26);
    lv_obj_set_x(ui_SateliteInfoSelect, lv_pct(0));
    lv_obj_set_align(ui_SateliteInfoSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SateliteInfoSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SateliteInfoSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SateliteInfoSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SateliteInfoSelect, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SateliteInfoSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SateliteInfoSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SateliteInfoSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SateliteInfoSelect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SateliteInfoSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SateliteInfoSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SateliteInfoSelect, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_SateliteInfoSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_SateliteInfoSelect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SateliteInfoSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label69 = lv_label_create(ui_SateliteInfoSelect);
    lv_obj_set_width(ui_Label69, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label69, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label69, -11);
    lv_obj_set_y(ui_Label69, 0);
    lv_obj_set_align(ui_Label69, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label69, "SATELITE INFO");
    lv_obj_set_style_text_font(ui_Label69, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label69, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label69, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SyncRTCTimeSelect = lv_btn_create(ui_GPSMenu);
    lv_obj_set_height(ui_SyncRTCTimeSelect, 24);
    lv_obj_set_width(ui_SyncRTCTimeSelect, lv_pct(97));
    lv_obj_set_y(ui_SyncRTCTimeSelect, 60);
    lv_obj_set_x(ui_SyncRTCTimeSelect, lv_pct(0));
    lv_obj_set_align(ui_SyncRTCTimeSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SyncRTCTimeSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SyncRTCTimeSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SyncRTCTimeSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SyncRTCTimeSelect, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SyncRTCTimeSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SyncRTCTimeSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SyncRTCTimeSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SyncRTCTimeSelect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SyncRTCTimeSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SyncRTCTimeSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SyncRTCTimeSelect, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_SyncRTCTimeSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_SyncRTCTimeSelect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SyncRTCTimeSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label70 = lv_label_create(ui_SyncRTCTimeSelect);
    lv_obj_set_width(ui_Label70, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label70, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label70, -11);
    lv_obj_set_y(ui_Label70, 0);
    lv_obj_set_align(ui_Label70, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label70, "SYNC RTC TIME");
    lv_obj_set_style_text_font(ui_Label70, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label70, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label70, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_NMEAConsoleSelect = lv_btn_create(ui_GPSMenu);
    lv_obj_set_height(ui_NMEAConsoleSelect, 24);
    lv_obj_set_width(ui_NMEAConsoleSelect, lv_pct(97));
    lv_obj_set_y(ui_NMEAConsoleSelect, 93);
    lv_obj_set_x(ui_NMEAConsoleSelect, lv_pct(0));
    lv_obj_set_align(ui_NMEAConsoleSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NMEAConsoleSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_NMEAConsoleSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NMEAConsoleSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NMEAConsoleSelect, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NMEAConsoleSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_NMEAConsoleSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NMEAConsoleSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NMEAConsoleSelect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_NMEAConsoleSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NMEAConsoleSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NMEAConsoleSelect, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_NMEAConsoleSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_NMEAConsoleSelect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_NMEAConsoleSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label71 = lv_label_create(ui_NMEAConsoleSelect);
    lv_obj_set_width(ui_Label71, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label71, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label71, -11);
    lv_obj_set_y(ui_Label71, 0);
    lv_obj_set_align(ui_Label71, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label71, "NMEA CONSOLE");
    lv_obj_set_style_text_font(ui_Label71, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label71, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label71, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_BackToMainMenu6, ui_event_BackToMainMenu6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StartWardrivingSelect, ui_event_StartWardrivingSelect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SateliteInfoSelect, ui_event_SateliteInfoSelect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SyncRTCTimeSelect, ui_event_SyncRTCTimeSelect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NMEAConsoleSelect, ui_event_NMEAConsoleSelect, LV_EVENT_ALL, NULL);

}

void ui_GPSMenu_screen_destroy(void)
{
    if(ui_GPSMenu) lv_obj_del(ui_GPSMenu);

    // NULL screen variables
    ui_GPSMenu = NULL;
    ui_BackToMainMenu6 = NULL;
    ui_Label67 = NULL;
    ui_StartWardrivingSelect = NULL;
    ui_Label68 = NULL;
    ui_SateliteInfoSelect = NULL;
    ui_Label69 = NULL;
    ui_SyncRTCTimeSelect = NULL;
    ui_Label70 = NULL;
    ui_NMEAConsoleSelect = NULL;
    ui_Label71 = NULL;

}
