// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_IRMenu = NULL;
lv_obj_t * ui_BackToMainMenu5 = NULL;
lv_obj_t * ui_Label49 = NULL;
lv_obj_t * ui_UniversalRemoteSelect = NULL;
lv_obj_t * ui_Label50 = NULL;
lv_obj_t * ui_LearnSignalSelect = NULL;
lv_obj_t * ui_Label51 = NULL;
lv_obj_t * ui_SavedRemotesSelect = NULL;
lv_obj_t * ui_Label52 = NULL;
// event funtions
void ui_event_BackToMainMenu5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainMenu_screen_init);
    }
}

void ui_event_UniversalRemoteSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_UniversalRemote, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_UniversalRemote_screen_init);
    }
}

void ui_event_LearnSignalSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_LearnSignal, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_LearnSignal_screen_init);
    }
}

void ui_event_SavedRemotesSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SavedRemotes, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SavedRemotes_screen_init);
    }
}

// build funtions

void ui_IRMenu_screen_init(void)
{
    ui_IRMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_IRMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IRMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IRMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackToMainMenu5 = lv_btn_create(ui_IRMenu);
    lv_obj_set_width(ui_BackToMainMenu5, 69);
    lv_obj_set_height(ui_BackToMainMenu5, 25);
    lv_obj_set_y(ui_BackToMainMenu5, -100);
    lv_obj_set_x(ui_BackToMainMenu5, lv_pct(-37));
    lv_obj_set_align(ui_BackToMainMenu5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackToMainMenu5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackToMainMenu5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackToMainMenu5, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackToMainMenu5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BackToMainMenu5, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BackToMainMenu5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BackToMainMenu5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BackToMainMenu5, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackToMainMenu5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackToMainMenu5, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BackToMainMenu5, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BackToMainMenu5, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BackToMainMenu5, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BackToMainMenu5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BackToMainMenu5, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label49 = lv_label_create(ui_BackToMainMenu5);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label49, -1);
    lv_obj_set_y(ui_Label49, 1);
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, "BACK");
    lv_obj_set_style_text_font(ui_Label49, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label49, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label49, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_UniversalRemoteSelect = lv_btn_create(ui_IRMenu);
    lv_obj_set_height(ui_UniversalRemoteSelect, 24);
    lv_obj_set_width(ui_UniversalRemoteSelect, lv_pct(97));
    lv_obj_set_y(ui_UniversalRemoteSelect, 11);
    lv_obj_set_x(ui_UniversalRemoteSelect, lv_pct(0));
    lv_obj_set_align(ui_UniversalRemoteSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UniversalRemoteSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_UniversalRemoteSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_UniversalRemoteSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_UniversalRemoteSelect, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UniversalRemoteSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_UniversalRemoteSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_UniversalRemoteSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_UniversalRemoteSelect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_UniversalRemoteSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UniversalRemoteSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_UniversalRemoteSelect, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_UniversalRemoteSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_UniversalRemoteSelect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_UniversalRemoteSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label50 = lv_label_create(ui_UniversalRemoteSelect);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label50, -11);
    lv_obj_set_y(ui_Label50, 0);
    lv_obj_set_align(ui_Label50, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label50, "UNIVERSAL REMOTE");
    lv_obj_set_style_text_font(ui_Label50, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label50, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label50, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LearnSignalSelect = lv_btn_create(ui_IRMenu);
    lv_obj_set_height(ui_LearnSignalSelect, 24);
    lv_obj_set_width(ui_LearnSignalSelect, lv_pct(97));
    lv_obj_set_y(ui_LearnSignalSelect, 46);
    lv_obj_set_x(ui_LearnSignalSelect, lv_pct(0));
    lv_obj_set_align(ui_LearnSignalSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LearnSignalSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LearnSignalSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LearnSignalSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LearnSignalSelect, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LearnSignalSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LearnSignalSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LearnSignalSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LearnSignalSelect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LearnSignalSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LearnSignalSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LearnSignalSelect, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_LearnSignalSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_LearnSignalSelect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_LearnSignalSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label51 = lv_label_create(ui_LearnSignalSelect);
    lv_obj_set_width(ui_Label51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label51, -11);
    lv_obj_set_y(ui_Label51, 0);
    lv_obj_set_align(ui_Label51, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label51, "LEARN SIGNAL");
    lv_obj_set_style_text_font(ui_Label51, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label51, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label51, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SavedRemotesSelect = lv_btn_create(ui_IRMenu);
    lv_obj_set_height(ui_SavedRemotesSelect, 24);
    lv_obj_set_width(ui_SavedRemotesSelect, lv_pct(97));
    lv_obj_set_y(ui_SavedRemotesSelect, 82);
    lv_obj_set_x(ui_SavedRemotesSelect, lv_pct(0));
    lv_obj_set_align(ui_SavedRemotesSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SavedRemotesSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SavedRemotesSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SavedRemotesSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SavedRemotesSelect, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SavedRemotesSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SavedRemotesSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SavedRemotesSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SavedRemotesSelect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SavedRemotesSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SavedRemotesSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SavedRemotesSelect, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_SavedRemotesSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_SavedRemotesSelect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SavedRemotesSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label52 = lv_label_create(ui_SavedRemotesSelect);
    lv_obj_set_width(ui_Label52, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label52, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label52, -11);
    lv_obj_set_y(ui_Label52, 0);
    lv_obj_set_align(ui_Label52, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label52, "SAVED REMOTES");
    lv_obj_set_style_text_font(ui_Label52, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label52, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label52, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_BackToMainMenu5, ui_event_BackToMainMenu5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_UniversalRemoteSelect, ui_event_UniversalRemoteSelect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LearnSignalSelect, ui_event_LearnSignalSelect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SavedRemotesSelect, ui_event_SavedRemotesSelect, LV_EVENT_ALL, NULL);

}

void ui_IRMenu_screen_destroy(void)
{
    if(ui_IRMenu) lv_obj_del(ui_IRMenu);

    // NULL screen variables
    ui_IRMenu = NULL;
    ui_BackToMainMenu5 = NULL;
    ui_Label49 = NULL;
    ui_UniversalRemoteSelect = NULL;
    ui_Label50 = NULL;
    ui_LearnSignalSelect = NULL;
    ui_Label51 = NULL;
    ui_SavedRemotesSelect = NULL;
    ui_Label52 = NULL;

}
