// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_INJECTPAYLOAD_H
#define UI_INJECTPAYLOAD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_InjectPayload
extern void ui_InjectPayload_screen_init(void);
extern void ui_InjectPayload_screen_destroy(void);
extern lv_obj_t * ui_InjectPayload;
extern void ui_event_BACKToNRFAction(lv_event_t * e);
extern lv_obj_t * ui_BACKToNRFAction;
extern lv_obj_t * ui_Label110;
extern lv_obj_t * ui_Label272;
extern lv_obj_t * ui_InjectPayloadPayload;
extern lv_obj_t * ui_Label274;
extern lv_obj_t * ui_InjectPayloadSTATUS;
extern lv_obj_t * ui_STARTIRAttackUni5;
extern lv_obj_t * ui_InjectPayloadSTOP;
extern void ui_event_InjectPayloadCHOOSE(lv_event_t * e);
extern lv_obj_t * ui_InjectPayloadCHOOSE;
extern lv_obj_t * ui_Label285;
extern lv_obj_t * ui_Label286;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

