// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_InjectPayload = NULL;
lv_obj_t * ui_BACKToNRFAction = NULL;
lv_obj_t * ui_Label110 = NULL;
lv_obj_t * ui_Label272 = NULL;
lv_obj_t * ui_InjectPayloadPayload = NULL;
lv_obj_t * ui_Label274 = NULL;
lv_obj_t * ui_InjectPayloadSTATUS = NULL;
lv_obj_t * ui_STARTIRAttackUni5 = NULL;
lv_obj_t * ui_InjectPayloadSTOP = NULL;
lv_obj_t * ui_InjectPayloadCHOOSE = NULL;
lv_obj_t * ui_Label285 = NULL;
lv_obj_t * ui_Label286 = NULL;
// event funtions
void ui_event_BACKToNRFAction(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_NrfAction, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_NrfAction_screen_init);
    }
}

void ui_event_InjectPayloadCHOOSE(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SavedPayloads, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SavedPayloads_screen_init);
    }
}

// build funtions

void ui_InjectPayload_screen_init(void)
{
    ui_InjectPayload = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_InjectPayload, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_InjectPayload, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InjectPayload, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACKToNRFAction = lv_btn_create(ui_InjectPayload);
    lv_obj_set_width(ui_BACKToNRFAction, 69);
    lv_obj_set_height(ui_BACKToNRFAction, 25);
    lv_obj_set_y(ui_BACKToNRFAction, -100);
    lv_obj_set_x(ui_BACKToNRFAction, lv_pct(-37));
    lv_obj_set_align(ui_BACKToNRFAction, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACKToNRFAction, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACKToNRFAction, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACKToNRFAction, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACKToNRFAction, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACKToNRFAction, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACKToNRFAction, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BACKToNRFAction, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BACKToNRFAction, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BACKToNRFAction, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BACKToNRFAction, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BACKToNRFAction, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BACKToNRFAction, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BACKToNRFAction, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BACKToNRFAction, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BACKToNRFAction, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label110 = lv_label_create(ui_BACKToNRFAction);
    lv_obj_set_width(ui_Label110, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label110, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label110, 0);
    lv_obj_set_y(ui_Label110, 1);
    lv_obj_set_align(ui_Label110, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label110, "BACK");
    lv_obj_set_style_text_font(ui_Label110, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label110, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label110, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label272 = lv_label_create(ui_InjectPayload);
    lv_obj_set_width(ui_Label272, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label272, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label272, 5);
    lv_obj_set_y(ui_Label272, -60);
    lv_obj_set_align(ui_Label272, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label272, "Payload:");
    lv_obj_set_style_text_color(ui_Label272, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label272, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label272, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label272, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label272, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_InjectPayloadPayload = lv_label_create(ui_InjectPayload);
    lv_obj_set_width(ui_InjectPayloadPayload, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InjectPayloadPayload, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InjectPayloadPayload, 92);
    lv_obj_set_y(ui_InjectPayloadPayload, -59);
    lv_obj_set_align(ui_InjectPayloadPayload, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_InjectPayloadPayload, "Garaz.sub");
    lv_obj_set_style_text_color(ui_InjectPayloadPayload, lv_color_hex(0xFFB200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_InjectPayloadPayload, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_InjectPayloadPayload, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_InjectPayloadPayload, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_InjectPayloadPayload, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label274 = lv_label_create(ui_InjectPayload);
    lv_obj_set_width(ui_Label274, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label274, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label274, 9);
    lv_obj_set_y(ui_Label274, -34);
    lv_obj_set_align(ui_Label274, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label274, "STATUS:");
    lv_obj_set_style_text_color(ui_Label274, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label274, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label274, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label274, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label274, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_InjectPayloadSTATUS = lv_label_create(ui_InjectPayload);
    lv_obj_set_width(ui_InjectPayloadSTATUS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InjectPayloadSTATUS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InjectPayloadSTATUS, 92);
    lv_obj_set_y(ui_InjectPayloadSTATUS, -34);
    lv_obj_set_align(ui_InjectPayloadSTATUS, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_InjectPayloadSTATUS, "TRANSMITTING...");
    lv_obj_set_style_text_color(ui_InjectPayloadSTATUS, lv_color_hex(0xFFB200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_InjectPayloadSTATUS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_InjectPayloadSTATUS, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_InjectPayloadSTATUS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_InjectPayloadSTATUS, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_STARTIRAttackUni5 = lv_btn_create(ui_InjectPayload);
    lv_obj_set_height(ui_STARTIRAttackUni5, 61);
    lv_obj_set_width(ui_STARTIRAttackUni5, lv_pct(57));
    lv_obj_set_y(ui_STARTIRAttackUni5, 51);
    lv_obj_set_x(ui_STARTIRAttackUni5, lv_pct(-1));
    lv_obj_set_align(ui_STARTIRAttackUni5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_STARTIRAttackUni5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_STARTIRAttackUni5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_STARTIRAttackUni5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_STARTIRAttackUni5, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_STARTIRAttackUni5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_STARTIRAttackUni5, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_STARTIRAttackUni5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_STARTIRAttackUni5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_STARTIRAttackUni5, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_STARTIRAttackUni5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_STARTIRAttackUni5, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_STARTIRAttackUni5, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_STARTIRAttackUni5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_STARTIRAttackUni5, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_InjectPayloadSTOP = lv_label_create(ui_STARTIRAttackUni5);
    lv_obj_set_width(ui_InjectPayloadSTOP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InjectPayloadSTOP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InjectPayloadSTOP, 0);
    lv_obj_set_y(ui_InjectPayloadSTOP, -1);
    lv_obj_set_align(ui_InjectPayloadSTOP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_InjectPayloadSTOP, "STOP");
    lv_obj_set_style_text_font(ui_InjectPayloadSTOP, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_InjectPayloadSTOP, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_InjectPayloadSTOP, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_InjectPayloadCHOOSE = lv_btn_create(ui_InjectPayload);
    lv_obj_set_width(ui_InjectPayloadCHOOSE, 194);
    lv_obj_set_height(ui_InjectPayloadCHOOSE, 25);
    lv_obj_set_y(ui_InjectPayloadCHOOSE, -101);
    lv_obj_set_x(ui_InjectPayloadCHOOSE, lv_pct(14));
    lv_obj_set_align(ui_InjectPayloadCHOOSE, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_InjectPayloadCHOOSE, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_InjectPayloadCHOOSE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_InjectPayloadCHOOSE, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InjectPayloadCHOOSE, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_InjectPayloadCHOOSE, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_InjectPayloadCHOOSE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_InjectPayloadCHOOSE, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_InjectPayloadCHOOSE, lv_color_hex(0xE90000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_InjectPayloadCHOOSE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_InjectPayloadCHOOSE, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_InjectPayloadCHOOSE, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_InjectPayloadCHOOSE, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_InjectPayloadCHOOSE, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label285 = lv_label_create(ui_InjectPayloadCHOOSE);
    lv_obj_set_width(ui_Label285, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label285, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label285, -62);
    lv_obj_set_y(ui_Label285, 0);
    lv_obj_set_align(ui_Label285, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label285, "PAYLD:");
    lv_obj_set_style_text_color(ui_Label285, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label285, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label285, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label285, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label285, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label286 = lv_label_create(ui_InjectPayloadCHOOSE);
    lv_obj_set_width(ui_Label286, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label286, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label286, 52);
    lv_obj_set_y(ui_Label286, 0);
    lv_obj_set_align(ui_Label286, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_Label286, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_Label286, "NONE");
    lv_obj_set_style_text_font(ui_Label286, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label286, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label286, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_BACKToNRFAction, ui_event_BACKToNRFAction, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_InjectPayloadCHOOSE, ui_event_InjectPayloadCHOOSE, LV_EVENT_ALL, NULL);

}

void ui_InjectPayload_screen_destroy(void)
{
    if(ui_InjectPayload) lv_obj_del(ui_InjectPayload);

    // NULL screen variables
    ui_InjectPayload = NULL;
    ui_BACKToNRFAction = NULL;
    ui_Label110 = NULL;
    ui_Label272 = NULL;
    ui_InjectPayloadPayload = NULL;
    ui_Label274 = NULL;
    ui_InjectPayloadSTATUS = NULL;
    ui_STARTIRAttackUni5 = NULL;
    ui_InjectPayloadSTOP = NULL;
    ui_InjectPayloadCHOOSE = NULL;
    ui_Label285 = NULL;
    ui_Label286 = NULL;

}
