// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_NrfAction = NULL;
lv_obj_t * ui_BACKToSavedPayloadsNRF = NULL;
lv_obj_t * ui_Label277 = NULL;
lv_obj_t * ui_NRFActionINJECT = NULL;
lv_obj_t * ui_Label278 = NULL;
lv_obj_t * ui_NRFActionDELETE = NULL;
lv_obj_t * ui_Label279 = NULL;
// event funtions
void ui_event_BACKToSavedPayloadsNRF(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SavedPayloads, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SavedPayloads_screen_init);
    }
}

// build funtions

void ui_NrfAction_screen_init(void)
{
    ui_NrfAction = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_NrfAction, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_NrfAction, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NrfAction, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACKToSavedPayloadsNRF = lv_btn_create(ui_NrfAction);
    lv_obj_set_width(ui_BACKToSavedPayloadsNRF, 69);
    lv_obj_set_height(ui_BACKToSavedPayloadsNRF, 25);
    lv_obj_set_y(ui_BACKToSavedPayloadsNRF, -100);
    lv_obj_set_x(ui_BACKToSavedPayloadsNRF, lv_pct(-37));
    lv_obj_set_align(ui_BACKToSavedPayloadsNRF, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACKToSavedPayloadsNRF, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACKToSavedPayloadsNRF, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACKToSavedPayloadsNRF, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACKToSavedPayloadsNRF, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACKToSavedPayloadsNRF, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACKToSavedPayloadsNRF, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BACKToSavedPayloadsNRF, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BACKToSavedPayloadsNRF, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BACKToSavedPayloadsNRF, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BACKToSavedPayloadsNRF, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BACKToSavedPayloadsNRF, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BACKToSavedPayloadsNRF, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BACKToSavedPayloadsNRF, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BACKToSavedPayloadsNRF, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BACKToSavedPayloadsNRF, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label277 = lv_label_create(ui_BACKToSavedPayloadsNRF);
    lv_obj_set_width(ui_Label277, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label277, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label277, 0);
    lv_obj_set_y(ui_Label277, 1);
    lv_obj_set_align(ui_Label277, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label277, "BACK");
    lv_obj_set_style_text_font(ui_Label277, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label277, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label277, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_NRFActionINJECT = lv_btn_create(ui_NrfAction);
    lv_obj_set_height(ui_NRFActionINJECT, 31);
    lv_obj_set_width(ui_NRFActionINJECT, lv_pct(40));
    lv_obj_set_y(ui_NRFActionINJECT, -16);
    lv_obj_set_x(ui_NRFActionINJECT, lv_pct(-2));
    lv_obj_set_align(ui_NRFActionINJECT, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NRFActionINJECT, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_NRFActionINJECT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NRFActionINJECT, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NRFActionINJECT, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NRFActionINJECT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_NRFActionINJECT, lv_color_hex(0x00FF48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NRFActionINJECT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NRFActionINJECT, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_NRFActionINJECT, lv_color_hex(0x94FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NRFActionINJECT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NRFActionINJECT, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_NRFActionINJECT, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_NRFActionINJECT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_NRFActionINJECT, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label278 = lv_label_create(ui_NRFActionINJECT);
    lv_obj_set_width(ui_Label278, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label278, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label278, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label278, "INJECT");
    lv_obj_set_style_text_font(ui_Label278, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label278, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label278, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_NRFActionDELETE = lv_btn_create(ui_NrfAction);
    lv_obj_set_height(ui_NRFActionDELETE, 31);
    lv_obj_set_width(ui_NRFActionDELETE, lv_pct(40));
    lv_obj_set_y(ui_NRFActionDELETE, 63);
    lv_obj_set_x(ui_NRFActionDELETE, lv_pct(-2));
    lv_obj_set_align(ui_NRFActionDELETE, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NRFActionDELETE, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_NRFActionDELETE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NRFActionDELETE, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NRFActionDELETE, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NRFActionDELETE, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_NRFActionDELETE, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NRFActionDELETE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NRFActionDELETE, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_NRFActionDELETE, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NRFActionDELETE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NRFActionDELETE, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_NRFActionDELETE, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_NRFActionDELETE, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_NRFActionDELETE, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label279 = lv_label_create(ui_NRFActionDELETE);
    lv_obj_set_width(ui_Label279, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label279, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label279, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label279, "DELETE");
    lv_obj_set_style_text_font(ui_Label279, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label279, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label279, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_BACKToSavedPayloadsNRF, ui_event_BACKToSavedPayloadsNRF, LV_EVENT_ALL, NULL);

}

void ui_NrfAction_screen_destroy(void)
{
    if(ui_NrfAction) lv_obj_del(ui_NrfAction);

    // NULL screen variables
    ui_NrfAction = NULL;
    ui_BACKToSavedPayloadsNRF = NULL;
    ui_Label277 = NULL;
    ui_NRFActionINJECT = NULL;
    ui_Label278 = NULL;
    ui_NRFActionDELETE = NULL;
    ui_Label279 = NULL;

}
