// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_PCAPSCREEN_H
#define UI_PCAPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PCAPScreen
extern void ui_PCAPScreen_screen_init(void);
extern void ui_PCAPScreen_screen_destroy(void);
extern lv_obj_t * ui_PCAPScreen;
extern void ui_event_BACKWifi8(lv_event_t * e);
extern lv_obj_t * ui_BACKWifi8;
extern lv_obj_t * ui_Label343;
extern lv_obj_t * ui_Dropdown3;
extern lv_obj_t * ui_Label356;
extern lv_obj_t * ui_Label357;
extern lv_obj_t * ui_Label358;
extern lv_obj_t * ui_Label359;
extern lv_obj_t * ui_Label360;
extern lv_obj_t * ui_Label361;
extern lv_obj_t * ui_Label362;
extern lv_obj_t * ui_STARTSTOPDeauth12;
extern lv_obj_t * ui_Label363;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

