// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_PROBESNIFFING_H
#define UI_PROBESNIFFING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ProbeSniffing
extern void ui_ProbeSniffing_screen_init(void);
extern void ui_ProbeSniffing_screen_destroy(void);
extern lv_obj_t * ui_ProbeSniffing;
extern void ui_event_BACKToSniffMenu(lv_event_t * e);
extern lv_obj_t * ui_BACKToSniffMenu;
extern lv_obj_t * ui_Label103;
extern lv_obj_t * ui_ProbeSniffingSTATUS;
extern lv_obj_t * ui_Label314;
extern lv_obj_t * ui_ProbeSniffingDevices;
extern lv_obj_t * ui_ProbeSniffingTEXTAREA;
extern lv_obj_t * ui_ProbeSniffingSTART;
extern lv_obj_t * ui_Label316;
extern lv_obj_t * ui_ProbeSniffingCLEAR;
extern lv_obj_t * ui_Label317;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

