// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_PCAPACTION_H
#define UI_PCAPACTION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PcapAction
extern void ui_PcapAction_screen_init(void);
extern void ui_PcapAction_screen_destroy(void);
extern lv_obj_t * ui_PcapAction;
extern void ui_event_BACKToSD4(lv_event_t * e);
extern lv_obj_t * ui_BACKToSD4;
extern lv_obj_t * ui_Label222;
extern lv_obj_t * ui_Label223;
extern lv_obj_t * ui_PcapActionFile;
extern lv_obj_t * ui_Label225;
extern lv_obj_t * ui_PcapActionSIZE;
extern lv_obj_t * ui_PcapActionDELETE;
extern lv_obj_t * ui_Label227;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

