// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_ReadTag = NULL;
lv_obj_t * ui_BACKToRfid = NULL;
lv_obj_t * ui_Label105 = NULL;
lv_obj_t * ui_Label244 = NULL;
lv_obj_t * ui_ReadTagStatus = NULL;
lv_obj_t * ui_ReadTagUIDLabel = NULL;
lv_obj_t * ui_ReadTagUID1 = NULL;
lv_obj_t * ui_Label248 = NULL;
lv_obj_t * ui_ReadTagSAK = NULL;
lv_obj_t * ui_Label250 = NULL;
lv_obj_t * ui_ReadTagType = NULL;
lv_obj_t * ui_ReadTagRESCAN = NULL;
lv_obj_t * ui_Label252 = NULL;
lv_obj_t * ui_ReadTagSAVE = NULL;
lv_obj_t * ui_Label253 = NULL;
// event funtions
void ui_event_BACKToRfid(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainMenu_screen_init);
    }
}

// build funtions

void ui_ReadTag_screen_init(void)
{
    ui_ReadTag = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ReadTag, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ReadTag, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReadTag, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACKToRfid = lv_btn_create(ui_ReadTag);
    lv_obj_set_width(ui_BACKToRfid, 69);
    lv_obj_set_height(ui_BACKToRfid, 25);
    lv_obj_set_y(ui_BACKToRfid, -100);
    lv_obj_set_x(ui_BACKToRfid, lv_pct(-37));
    lv_obj_set_align(ui_BACKToRfid, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACKToRfid, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACKToRfid, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACKToRfid, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACKToRfid, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACKToRfid, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACKToRfid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BACKToRfid, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BACKToRfid, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BACKToRfid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BACKToRfid, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BACKToRfid, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BACKToRfid, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BACKToRfid, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BACKToRfid, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BACKToRfid, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label105 = lv_label_create(ui_BACKToRfid);
    lv_obj_set_width(ui_Label105, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label105, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label105, 0);
    lv_obj_set_y(ui_Label105, 1);
    lv_obj_set_align(ui_Label105, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label105, "BACK");
    lv_obj_set_style_text_font(ui_Label105, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label105, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label105, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label244 = lv_label_create(ui_ReadTag);
    lv_obj_set_width(ui_Label244, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label244, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label244, 5);
    lv_obj_set_y(ui_Label244, -60);
    lv_obj_set_align(ui_Label244, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label244, "STATUS:");
    lv_obj_set_style_text_color(ui_Label244, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label244, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label244, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label244, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label244, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_ReadTagStatus = lv_label_create(ui_ReadTag);
    lv_obj_set_width(ui_ReadTagStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReadTagStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ReadTagStatus, 92);
    lv_obj_set_y(ui_ReadTagStatus, -59);
    lv_obj_set_align(ui_ReadTagStatus, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ReadTagStatus, "APPROACH CARD");
    lv_obj_set_style_text_color(ui_ReadTagStatus, lv_color_hex(0xFFB200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ReadTagStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ReadTagStatus, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ReadTagStatus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_ReadTagStatus, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_ReadTagUIDLabel = lv_label_create(ui_ReadTag);
    lv_obj_set_width(ui_ReadTagUIDLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReadTagUIDLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ReadTagUIDLabel, 5);
    lv_obj_set_y(ui_ReadTagUIDLabel, -32);
    lv_obj_set_align(ui_ReadTagUIDLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ReadTagUIDLabel, "UID:");
    lv_obj_set_style_text_color(ui_ReadTagUIDLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ReadTagUIDLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ReadTagUIDLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ReadTagUIDLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_ReadTagUIDLabel, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_ReadTagUID1 = lv_label_create(ui_ReadTag);
    lv_obj_set_width(ui_ReadTagUID1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReadTagUID1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ReadTagUID1, 51);
    lv_obj_set_y(ui_ReadTagUID1, -31);
    lv_obj_set_align(ui_ReadTagUID1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ReadTagUID1, " -- : -- : -- : --");
    lv_obj_set_style_text_color(ui_ReadTagUID1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ReadTagUID1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ReadTagUID1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ReadTagUID1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_ReadTagUID1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label248 = lv_label_create(ui_ReadTag);
    lv_obj_set_width(ui_Label248, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label248, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label248, 5);
    lv_obj_set_y(ui_Label248, -10);
    lv_obj_set_align(ui_Label248, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label248, "SAK:");
    lv_obj_set_style_text_color(ui_Label248, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label248, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label248, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label248, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label248, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_ReadTagSAK = lv_label_create(ui_ReadTag);
    lv_obj_set_width(ui_ReadTagSAK, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReadTagSAK, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ReadTagSAK, 53);
    lv_obj_set_y(ui_ReadTagSAK, -8);
    lv_obj_set_align(ui_ReadTagSAK, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ReadTagSAK, "0x--");
    lv_obj_set_style_text_color(ui_ReadTagSAK, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ReadTagSAK, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ReadTagSAK, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ReadTagSAK, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_ReadTagSAK, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label250 = lv_label_create(ui_ReadTag);
    lv_obj_set_width(ui_Label250, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label250, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label250, 5);
    lv_obj_set_y(ui_Label250, 12);
    lv_obj_set_align(ui_Label250, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label250, "Type:");
    lv_obj_set_style_text_color(ui_Label250, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label250, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label250, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label250, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label250, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_ReadTagType = lv_label_create(ui_ReadTag);
    lv_obj_set_width(ui_ReadTagType, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReadTagType, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ReadTagType, 60);
    lv_obj_set_y(ui_ReadTagType, 14);
    lv_obj_set_align(ui_ReadTagType, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ReadTagType, "---");
    lv_obj_set_style_text_color(ui_ReadTagType, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ReadTagType, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ReadTagType, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ReadTagType, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_ReadTagType, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_ReadTagRESCAN = lv_btn_create(ui_ReadTag);
    lv_obj_set_height(ui_ReadTagRESCAN, 31);
    lv_obj_set_width(ui_ReadTagRESCAN, lv_pct(40));
    lv_obj_set_y(ui_ReadTagRESCAN, 44);
    lv_obj_set_x(ui_ReadTagRESCAN, lv_pct(0));
    lv_obj_set_align(ui_ReadTagRESCAN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ReadTagRESCAN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ReadTagRESCAN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ReadTagRESCAN, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReadTagRESCAN, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReadTagRESCAN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ReadTagRESCAN, lv_color_hex(0x00FF48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ReadTagRESCAN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ReadTagRESCAN, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ReadTagRESCAN, lv_color_hex(0x94FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ReadTagRESCAN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReadTagRESCAN, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_ReadTagRESCAN, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_ReadTagRESCAN, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_ReadTagRESCAN, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label252 = lv_label_create(ui_ReadTagRESCAN);
    lv_obj_set_width(ui_Label252, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label252, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label252, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label252, "RESCAN");
    lv_obj_set_style_text_font(ui_Label252, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label252, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label252, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_ReadTagSAVE = lv_btn_create(ui_ReadTag);
    lv_obj_set_height(ui_ReadTagSAVE, 31);
    lv_obj_set_width(ui_ReadTagSAVE, lv_pct(40));
    lv_obj_set_y(ui_ReadTagSAVE, 90);
    lv_obj_set_x(ui_ReadTagSAVE, lv_pct(0));
    lv_obj_set_align(ui_ReadTagSAVE, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ReadTagSAVE, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ReadTagSAVE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ReadTagSAVE, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReadTagSAVE, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReadTagSAVE, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ReadTagSAVE, lv_color_hex(0x00FF48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ReadTagSAVE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ReadTagSAVE, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ReadTagSAVE, lv_color_hex(0x94FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ReadTagSAVE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReadTagSAVE, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_ReadTagSAVE, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_ReadTagSAVE, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_ReadTagSAVE, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label253 = lv_label_create(ui_ReadTagSAVE);
    lv_obj_set_width(ui_Label253, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label253, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label253, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label253, "SAVE");
    lv_obj_set_style_text_font(ui_Label253, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label253, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label253, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_BACKToRfid, ui_event_BACKToRfid, LV_EVENT_ALL, NULL);

}

void ui_ReadTag_screen_destroy(void)
{
    if(ui_ReadTag) lv_obj_del(ui_ReadTag);

    // NULL screen variables
    ui_ReadTag = NULL;
    ui_BACKToRfid = NULL;
    ui_Label105 = NULL;
    ui_Label244 = NULL;
    ui_ReadTagStatus = NULL;
    ui_ReadTagUIDLabel = NULL;
    ui_ReadTagUID1 = NULL;
    ui_Label248 = NULL;
    ui_ReadTagSAK = NULL;
    ui_Label250 = NULL;
    ui_ReadTagType = NULL;
    ui_ReadTagRESCAN = NULL;
    ui_Label252 = NULL;
    ui_ReadTagSAVE = NULL;
    ui_Label253 = NULL;

}
