// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_READSIGNAL_H
#define UI_READSIGNAL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ReadSignal
extern void ui_ReadSignal_screen_init(void);
extern void ui_ReadSignal_screen_destroy(void);
extern lv_obj_t * ui_ReadSignal;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_ReadSignalSTATUS;
extern lv_obj_t * ui_Label91;
extern lv_obj_t * ui_Label90;
extern lv_obj_t * ui_Label92;
extern lv_obj_t * ui_Label93;
extern void ui_event_BackToSubGHzMenu4(lv_event_t * e);
extern lv_obj_t * ui_BackToSubGHzMenu4;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_ReadSignalSEND;
extern lv_obj_t * ui_Label94;
extern lv_obj_t * ui_ReadSignalSAVE;
extern lv_obj_t * ui_Label95;
extern lv_obj_t * ui_ReadSignalCLEAR;
extern lv_obj_t * ui_Label96;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

