// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_RfidMenu = NULL;
lv_obj_t * ui_BackToMainMenu3 = NULL;
lv_obj_t * ui_Label37 = NULL;
lv_obj_t * ui_ReadTagSelect = NULL;
lv_obj_t * ui_Label38 = NULL;
lv_obj_t * ui_EmulateTagSelect = NULL;
lv_obj_t * ui_Label39 = NULL;
lv_obj_t * ui_WriteCloneSelect = NULL;
lv_obj_t * ui_Label40 = NULL;
lv_obj_t * ui_SavedTagsSelect = NULL;
lv_obj_t * ui_Label41 = NULL;
// event funtions
void ui_event_BackToMainMenu3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainMenu_screen_init);
    }
}

void ui_event_ReadTagSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ReadTag, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ReadTag_screen_init);
    }
}

void ui_event_EmulateTagSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_EmulateTag, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_EmulateTag_screen_init);
    }
}

void ui_event_WriteCloneSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WriteClone, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WriteClone_screen_init);
    }
}

void ui_event_SavedTagsSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SavedTags, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SavedTags_screen_init);
    }
}

// build funtions

void ui_RfidMenu_screen_init(void)
{
    ui_RfidMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_RfidMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RfidMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RfidMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackToMainMenu3 = lv_btn_create(ui_RfidMenu);
    lv_obj_set_width(ui_BackToMainMenu3, 69);
    lv_obj_set_height(ui_BackToMainMenu3, 25);
    lv_obj_set_y(ui_BackToMainMenu3, -100);
    lv_obj_set_x(ui_BackToMainMenu3, lv_pct(-37));
    lv_obj_set_align(ui_BackToMainMenu3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackToMainMenu3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackToMainMenu3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackToMainMenu3, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackToMainMenu3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BackToMainMenu3, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BackToMainMenu3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BackToMainMenu3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BackToMainMenu3, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackToMainMenu3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackToMainMenu3, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BackToMainMenu3, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BackToMainMenu3, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BackToMainMenu3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BackToMainMenu3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BackToMainMenu3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label37 = lv_label_create(ui_BackToMainMenu3);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, 0);
    lv_obj_set_y(ui_Label37, 1);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "BACK");
    lv_obj_set_style_text_font(ui_Label37, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label37, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label37, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_ReadTagSelect = lv_btn_create(ui_RfidMenu);
    lv_obj_set_height(ui_ReadTagSelect, 24);
    lv_obj_set_width(ui_ReadTagSelect, lv_pct(97));
    lv_obj_set_y(ui_ReadTagSelect, -8);
    lv_obj_set_x(ui_ReadTagSelect, lv_pct(0));
    lv_obj_set_align(ui_ReadTagSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ReadTagSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ReadTagSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ReadTagSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReadTagSelect, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReadTagSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ReadTagSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ReadTagSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ReadTagSelect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ReadTagSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ReadTagSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReadTagSelect, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_ReadTagSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_ReadTagSelect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_ReadTagSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label38 = lv_label_create(ui_ReadTagSelect);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, -11);
    lv_obj_set_y(ui_Label38, 0);
    lv_obj_set_align(ui_Label38, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label38, "READ TAG");
    lv_obj_set_style_text_font(ui_Label38, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label38, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label38, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_EmulateTagSelect = lv_btn_create(ui_RfidMenu);
    lv_obj_set_height(ui_EmulateTagSelect, 24);
    lv_obj_set_width(ui_EmulateTagSelect, lv_pct(97));
    lv_obj_set_y(ui_EmulateTagSelect, 26);
    lv_obj_set_x(ui_EmulateTagSelect, lv_pct(0));
    lv_obj_set_align(ui_EmulateTagSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EmulateTagSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_EmulateTagSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_EmulateTagSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_EmulateTagSelect, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EmulateTagSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_EmulateTagSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EmulateTagSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_EmulateTagSelect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_EmulateTagSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EmulateTagSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_EmulateTagSelect, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_EmulateTagSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_EmulateTagSelect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_EmulateTagSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label39 = lv_label_create(ui_EmulateTagSelect);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, -11);
    lv_obj_set_y(ui_Label39, 0);
    lv_obj_set_align(ui_Label39, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label39, "EMULATE TAG");
    lv_obj_set_style_text_font(ui_Label39, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label39, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label39, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_WriteCloneSelect = lv_btn_create(ui_RfidMenu);
    lv_obj_set_height(ui_WriteCloneSelect, 24);
    lv_obj_set_width(ui_WriteCloneSelect, lv_pct(97));
    lv_obj_set_y(ui_WriteCloneSelect, 60);
    lv_obj_set_x(ui_WriteCloneSelect, lv_pct(0));
    lv_obj_set_align(ui_WriteCloneSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WriteCloneSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WriteCloneSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WriteCloneSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WriteCloneSelect, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WriteCloneSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WriteCloneSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WriteCloneSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WriteCloneSelect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_WriteCloneSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WriteCloneSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WriteCloneSelect, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_WriteCloneSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_WriteCloneSelect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_WriteCloneSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label40 = lv_label_create(ui_WriteCloneSelect);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, -11);
    lv_obj_set_y(ui_Label40, 0);
    lv_obj_set_align(ui_Label40, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label40, "WRITE / CLONE");
    lv_obj_set_style_text_font(ui_Label40, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label40, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label40, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SavedTagsSelect = lv_btn_create(ui_RfidMenu);
    lv_obj_set_height(ui_SavedTagsSelect, 24);
    lv_obj_set_width(ui_SavedTagsSelect, lv_pct(97));
    lv_obj_set_y(ui_SavedTagsSelect, 93);
    lv_obj_set_x(ui_SavedTagsSelect, lv_pct(0));
    lv_obj_set_align(ui_SavedTagsSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SavedTagsSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SavedTagsSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SavedTagsSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SavedTagsSelect, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SavedTagsSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SavedTagsSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SavedTagsSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SavedTagsSelect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SavedTagsSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SavedTagsSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SavedTagsSelect, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_SavedTagsSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_SavedTagsSelect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SavedTagsSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label41 = lv_label_create(ui_SavedTagsSelect);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, -11);
    lv_obj_set_y(ui_Label41, 0);
    lv_obj_set_align(ui_Label41, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label41, "SAVED TAGS");
    lv_obj_set_style_text_font(ui_Label41, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label41, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_BackToMainMenu3, ui_event_BackToMainMenu3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ReadTagSelect, ui_event_ReadTagSelect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_EmulateTagSelect, ui_event_EmulateTagSelect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WriteCloneSelect, ui_event_WriteCloneSelect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SavedTagsSelect, ui_event_SavedTagsSelect, LV_EVENT_ALL, NULL);

}

void ui_RfidMenu_screen_destroy(void)
{
    if(ui_RfidMenu) lv_obj_del(ui_RfidMenu);

    // NULL screen variables
    ui_RfidMenu = NULL;
    ui_BackToMainMenu3 = NULL;
    ui_Label37 = NULL;
    ui_ReadTagSelect = NULL;
    ui_Label38 = NULL;
    ui_EmulateTagSelect = NULL;
    ui_Label39 = NULL;
    ui_WriteCloneSelect = NULL;
    ui_Label40 = NULL;
    ui_SavedTagsSelect = NULL;
    ui_Label41 = NULL;

}
