// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_READTAG_H
#define UI_READTAG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ReadTag
extern void ui_ReadTag_screen_init(void);
extern void ui_ReadTag_screen_destroy(void);
extern lv_obj_t * ui_ReadTag;
extern void ui_event_BACKToRfid(lv_event_t * e);
extern lv_obj_t * ui_BACKToRfid;
extern lv_obj_t * ui_Label105;
extern lv_obj_t * ui_Label244;
extern lv_obj_t * ui_ReadTagStatus;
extern lv_obj_t * ui_ReadTagUIDLabel;
extern lv_obj_t * ui_ReadTagUID1;
extern lv_obj_t * ui_Label248;
extern lv_obj_t * ui_ReadTagSAK;
extern lv_obj_t * ui_Label250;
extern lv_obj_t * ui_ReadTagType;
extern lv_obj_t * ui_ReadTagRESCAN;
extern lv_obj_t * ui_Label252;
extern lv_obj_t * ui_ReadTagSAVE;
extern lv_obj_t * ui_Label253;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

