// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_SNIFFMENU_H
#define UI_SNIFFMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SniffMenu
extern void ui_SniffMenu_screen_init(void);
extern void ui_SniffMenu_screen_destroy(void);
extern lv_obj_t * ui_SniffMenu;
extern void ui_event_BACKToWifi5(lv_event_t * e);
extern lv_obj_t * ui_BACKToWifi5;
extern lv_obj_t * ui_Label104;
extern void ui_event_ProbeSniffingSelect(lv_event_t * e);
extern lv_obj_t * ui_ProbeSniffingSelect;
extern lv_obj_t * ui_Label113;
extern void ui_event_EAPOLHandshakesSelect(lv_event_t * e);
extern lv_obj_t * ui_EAPOLHandshakesSelect;
extern lv_obj_t * ui_Label14;
extern void ui_event_BeaconSniffingSelect(lv_event_t * e);
extern lv_obj_t * ui_BeaconSniffingSelect;
extern lv_obj_t * ui_Label116;
extern void ui_event_RAWPcapSelect(lv_event_t * e);
extern lv_obj_t * ui_RAWPcapSelect;
extern lv_obj_t * ui_Label117;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

