// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_SavedTagsRemote = NULL;
lv_obj_t * ui_BACKToRfid4 = NULL;
lv_obj_t * ui_Label255 = NULL;
lv_obj_t * ui_SavedTagsRemoteEMULATE = NULL;
lv_obj_t * ui_Label254 = NULL;
lv_obj_t * ui_SavedTagsRemoteWRITE = NULL;
lv_obj_t * ui_Label256 = NULL;
lv_obj_t * ui_SavedTagsRemoteDELETE = NULL;
lv_obj_t * ui_Label257 = NULL;
lv_obj_t * ui_Label258 = NULL;
lv_obj_t * ui_SavedTagsRemoteTag = NULL;
// event funtions
void ui_event_BACKToRfid4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainMenu_screen_init);
    }
}

// build funtions

void ui_SavedTagsRemote_screen_init(void)
{
    ui_SavedTagsRemote = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SavedTagsRemote, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SavedTagsRemote, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SavedTagsRemote, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACKToRfid4 = lv_btn_create(ui_SavedTagsRemote);
    lv_obj_set_width(ui_BACKToRfid4, 69);
    lv_obj_set_height(ui_BACKToRfid4, 25);
    lv_obj_set_y(ui_BACKToRfid4, -100);
    lv_obj_set_x(ui_BACKToRfid4, lv_pct(-37));
    lv_obj_set_align(ui_BACKToRfid4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACKToRfid4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACKToRfid4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACKToRfid4, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACKToRfid4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACKToRfid4, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACKToRfid4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BACKToRfid4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BACKToRfid4, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BACKToRfid4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BACKToRfid4, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BACKToRfid4, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BACKToRfid4, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BACKToRfid4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BACKToRfid4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BACKToRfid4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label255 = lv_label_create(ui_BACKToRfid4);
    lv_obj_set_width(ui_Label255, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label255, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label255, 0);
    lv_obj_set_y(ui_Label255, 1);
    lv_obj_set_align(ui_Label255, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label255, "BACK");
    lv_obj_set_style_text_font(ui_Label255, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label255, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label255, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SavedTagsRemoteEMULATE = lv_btn_create(ui_SavedTagsRemote);
    lv_obj_set_height(ui_SavedTagsRemoteEMULATE, 31);
    lv_obj_set_width(ui_SavedTagsRemoteEMULATE, lv_pct(40));
    lv_obj_set_y(ui_SavedTagsRemoteEMULATE, -12);
    lv_obj_set_x(ui_SavedTagsRemoteEMULATE, lv_pct(-1));
    lv_obj_set_align(ui_SavedTagsRemoteEMULATE, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SavedTagsRemoteEMULATE, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SavedTagsRemoteEMULATE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SavedTagsRemoteEMULATE, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SavedTagsRemoteEMULATE, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SavedTagsRemoteEMULATE, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SavedTagsRemoteEMULATE, lv_color_hex(0x00FF48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SavedTagsRemoteEMULATE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SavedTagsRemoteEMULATE, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SavedTagsRemoteEMULATE, lv_color_hex(0x94FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SavedTagsRemoteEMULATE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SavedTagsRemoteEMULATE, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_SavedTagsRemoteEMULATE, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_SavedTagsRemoteEMULATE, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SavedTagsRemoteEMULATE, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label254 = lv_label_create(ui_SavedTagsRemoteEMULATE);
    lv_obj_set_width(ui_Label254, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label254, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label254, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label254, "EMULATE");
    lv_obj_set_style_text_font(ui_Label254, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label254, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label254, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SavedTagsRemoteWRITE = lv_btn_create(ui_SavedTagsRemote);
    lv_obj_set_height(ui_SavedTagsRemoteWRITE, 31);
    lv_obj_set_width(ui_SavedTagsRemoteWRITE, lv_pct(40));
    lv_obj_set_y(ui_SavedTagsRemoteWRITE, 34);
    lv_obj_set_x(ui_SavedTagsRemoteWRITE, lv_pct(-1));
    lv_obj_set_align(ui_SavedTagsRemoteWRITE, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SavedTagsRemoteWRITE, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SavedTagsRemoteWRITE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SavedTagsRemoteWRITE, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SavedTagsRemoteWRITE, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SavedTagsRemoteWRITE, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SavedTagsRemoteWRITE, lv_color_hex(0x00FF48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SavedTagsRemoteWRITE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SavedTagsRemoteWRITE, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SavedTagsRemoteWRITE, lv_color_hex(0x94FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SavedTagsRemoteWRITE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SavedTagsRemoteWRITE, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_SavedTagsRemoteWRITE, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_SavedTagsRemoteWRITE, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SavedTagsRemoteWRITE, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label256 = lv_label_create(ui_SavedTagsRemoteWRITE);
    lv_obj_set_width(ui_Label256, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label256, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label256, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label256, "WRITE");
    lv_obj_set_style_text_font(ui_Label256, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label256, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label256, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SavedTagsRemoteDELETE = lv_btn_create(ui_SavedTagsRemote);
    lv_obj_set_height(ui_SavedTagsRemoteDELETE, 31);
    lv_obj_set_width(ui_SavedTagsRemoteDELETE, lv_pct(40));
    lv_obj_set_y(ui_SavedTagsRemoteDELETE, 83);
    lv_obj_set_x(ui_SavedTagsRemoteDELETE, lv_pct(-1));
    lv_obj_set_align(ui_SavedTagsRemoteDELETE, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SavedTagsRemoteDELETE, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SavedTagsRemoteDELETE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SavedTagsRemoteDELETE, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SavedTagsRemoteDELETE, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SavedTagsRemoteDELETE, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SavedTagsRemoteDELETE, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SavedTagsRemoteDELETE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SavedTagsRemoteDELETE, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SavedTagsRemoteDELETE, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SavedTagsRemoteDELETE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SavedTagsRemoteDELETE, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_SavedTagsRemoteDELETE, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_SavedTagsRemoteDELETE, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SavedTagsRemoteDELETE, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label257 = lv_label_create(ui_SavedTagsRemoteDELETE);
    lv_obj_set_width(ui_Label257, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label257, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label257, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label257, "DELETE");
    lv_obj_set_style_text_font(ui_Label257, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label257, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label257, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label258 = lv_label_create(ui_SavedTagsRemote);
    lv_obj_set_width(ui_Label258, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label258, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label258, 5);
    lv_obj_set_y(ui_Label258, -60);
    lv_obj_set_align(ui_Label258, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label258, "TAG:");
    lv_obj_set_style_text_color(ui_Label258, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label258, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label258, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label258, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label258, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SavedTagsRemoteTag = lv_label_create(ui_SavedTagsRemote);
    lv_obj_set_width(ui_SavedTagsRemoteTag, 225);
    lv_obj_set_height(ui_SavedTagsRemoteTag, 24);
    lv_obj_set_x(ui_SavedTagsRemoteTag, 50);
    lv_obj_set_y(ui_SavedTagsRemoteTag, -58);
    lv_obj_set_align(ui_SavedTagsRemoteTag, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_SavedTagsRemoteTag, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_SavedTagsRemoteTag, "Doma.nfc");
    lv_obj_set_style_text_color(ui_SavedTagsRemoteTag, lv_color_hex(0xFFAA00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SavedTagsRemoteTag, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SavedTagsRemoteTag, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SavedTagsRemoteTag, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SavedTagsRemoteTag, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_BACKToRfid4, ui_event_BACKToRfid4, LV_EVENT_ALL, NULL);

}

void ui_SavedTagsRemote_screen_destroy(void)
{
    if(ui_SavedTagsRemote) lv_obj_del(ui_SavedTagsRemote);

    // NULL screen variables
    ui_SavedTagsRemote = NULL;
    ui_BACKToRfid4 = NULL;
    ui_Label255 = NULL;
    ui_SavedTagsRemoteEMULATE = NULL;
    ui_Label254 = NULL;
    ui_SavedTagsRemoteWRITE = NULL;
    ui_Label256 = NULL;
    ui_SavedTagsRemoteDELETE = NULL;
    ui_Label257 = NULL;
    ui_Label258 = NULL;
    ui_SavedTagsRemoteTag = NULL;

}
