// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_SourApple = NULL;
lv_obj_t * ui_BACKToBLE2 = NULL;
lv_obj_t * ui_Label230 = NULL;
lv_obj_t * ui_Label231 = NULL;
lv_obj_t * ui_SourAppleSTATUS = NULL;
lv_obj_t * ui_SourAppleBUTTON = NULL;
lv_obj_t * ui_Label233 = NULL;
lv_obj_t * ui_Label234 = NULL;
lv_obj_t * ui_SourAppleTarget = NULL;
// event funtions
void ui_event_BACKToBLE2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Bluetooth, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Bluetooth_screen_init);
    }
}

// build funtions

void ui_SourApple_screen_init(void)
{
    ui_SourApple = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SourApple, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SourApple, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SourApple, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SourApple, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_SourApple, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BACKToBLE2 = lv_btn_create(ui_SourApple);
    lv_obj_set_width(ui_BACKToBLE2, 69);
    lv_obj_set_height(ui_BACKToBLE2, 25);
    lv_obj_set_y(ui_BACKToBLE2, -100);
    lv_obj_set_x(ui_BACKToBLE2, lv_pct(-37));
    lv_obj_set_align(ui_BACKToBLE2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACKToBLE2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACKToBLE2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACKToBLE2, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACKToBLE2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACKToBLE2, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACKToBLE2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BACKToBLE2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BACKToBLE2, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BACKToBLE2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BACKToBLE2, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BACKToBLE2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BACKToBLE2, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BACKToBLE2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BACKToBLE2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BACKToBLE2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label230 = lv_label_create(ui_BACKToBLE2);
    lv_obj_set_width(ui_Label230, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label230, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label230, -1);
    lv_obj_set_y(ui_Label230, 1);
    lv_obj_set_align(ui_Label230, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label230, "BACK");
    lv_obj_set_style_text_font(ui_Label230, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label230, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label230, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label231 = lv_label_create(ui_SourApple);
    lv_obj_set_width(ui_Label231, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label231, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label231, 5);
    lv_obj_set_y(ui_Label231, -60);
    lv_obj_set_align(ui_Label231, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label231, "STATUS:");
    lv_obj_set_style_text_color(ui_Label231, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label231, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label231, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label231, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label231, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SourAppleSTATUS = lv_label_create(ui_SourApple);
    lv_obj_set_width(ui_SourAppleSTATUS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SourAppleSTATUS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SourAppleSTATUS, 84);
    lv_obj_set_y(ui_SourAppleSTATUS, -60);
    lv_obj_set_align(ui_SourAppleSTATUS, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_SourAppleSTATUS, "READY");
    lv_obj_set_style_text_color(ui_SourAppleSTATUS, lv_color_hex(0xFF9E00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SourAppleSTATUS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SourAppleSTATUS, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SourAppleSTATUS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SourAppleSTATUS, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SourAppleBUTTON = lv_btn_create(ui_SourApple);
    lv_obj_set_height(ui_SourAppleBUTTON, 61);
    lv_obj_set_width(ui_SourAppleBUTTON, lv_pct(88));
    lv_obj_set_y(ui_SourAppleBUTTON, 57);
    lv_obj_set_x(ui_SourAppleBUTTON, lv_pct(-1));
    lv_obj_set_align(ui_SourAppleBUTTON, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SourAppleBUTTON, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SourAppleBUTTON, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SourAppleBUTTON, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SourAppleBUTTON, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SourAppleBUTTON, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SourAppleBUTTON, lv_color_hex(0x00FF48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SourAppleBUTTON, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SourAppleBUTTON, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SourAppleBUTTON, lv_color_hex(0x94FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SourAppleBUTTON, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SourAppleBUTTON, lv_color_hex(0x36FF00), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_SourAppleBUTTON, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_SourAppleBUTTON, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SourAppleBUTTON, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_SourAppleBUTTON, lv_color_hex(0xFF0000),
                              LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_SourAppleBUTTON, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_SourAppleBUTTON, lv_color_hex(0xFF0000),
                                  LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_SourAppleBUTTON, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_SourAppleBUTTON, lv_color_hex(0x4FFF00),
                              LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_SourAppleBUTTON, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    ui_Label233 = lv_label_create(ui_SourAppleBUTTON);
    lv_obj_set_width(ui_Label233, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label233, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label233, 0);
    lv_obj_set_y(ui_Label233, -1);
    lv_obj_set_align(ui_Label233, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label233, "START SPAM");
    lv_obj_set_style_text_font(ui_Label233, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label233, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label233, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label234 = lv_label_create(ui_SourApple);
    lv_obj_set_width(ui_Label234, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label234, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label234, 5);
    lv_obj_set_y(ui_Label234, -26);
    lv_obj_set_align(ui_Label234, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label234, "TARGET:");
    lv_obj_set_style_text_color(ui_Label234, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label234, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label234, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label234, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label234, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SourAppleTarget = lv_label_create(ui_SourApple);
    lv_obj_set_width(ui_SourAppleTarget, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SourAppleTarget, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SourAppleTarget, 85);
    lv_obj_set_y(ui_SourAppleTarget, -25);
    lv_obj_set_align(ui_SourAppleTarget, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_SourAppleTarget, "iOS Devices");
    lv_obj_set_style_text_color(ui_SourAppleTarget, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SourAppleTarget, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SourAppleTarget, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SourAppleTarget, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SourAppleTarget, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_BACKToBLE2, ui_event_BACKToBLE2, LV_EVENT_ALL, NULL);

}

void ui_SourApple_screen_destroy(void)
{
    if(ui_SourApple) lv_obj_del(ui_SourApple);

    // NULL screen variables
    ui_SourApple = NULL;
    ui_BACKToBLE2 = NULL;
    ui_Label230 = NULL;
    ui_Label231 = NULL;
    ui_SourAppleSTATUS = NULL;
    ui_SourAppleBUTTON = NULL;
    ui_Label233 = NULL;
    ui_Label234 = NULL;
    ui_SourAppleTarget = NULL;

}
