// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_SelectTargetBeacon = NULL;
lv_obj_t * ui_BACKBeaconModes1 = NULL;
lv_obj_t * ui_Label327 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label328 = NULL;
lv_obj_t * ui_SelectTargetBeaconSSID = NULL;
lv_obj_t * ui_WIFINetworks1 = NULL;
lv_obj_t * ui_Network6 = NULL;
lv_obj_t * ui_SSID25 = NULL;
lv_obj_t * ui_SCANAPsButton1 = NULL;
lv_obj_t * ui_Label341 = NULL;
lv_obj_t * ui_FoundAPsPanel1 = NULL;
lv_obj_t * ui_APsFound1 = NULL;
lv_obj_t * ui_Label342 = NULL;
// event funtions
void ui_event_BACKBeaconModes1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_BeaconModes, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_BeaconModes_screen_init);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScanAPs, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScanAPs_screen_init);
    }
}

// build funtions

void ui_SelectTargetBeacon_screen_init(void)
{
    ui_SelectTargetBeacon = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SelectTargetBeacon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SelectTargetBeacon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SelectTargetBeacon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACKBeaconModes1 = lv_btn_create(ui_SelectTargetBeacon);
    lv_obj_set_width(ui_BACKBeaconModes1, 69);
    lv_obj_set_height(ui_BACKBeaconModes1, 25);
    lv_obj_set_y(ui_BACKBeaconModes1, -100);
    lv_obj_set_x(ui_BACKBeaconModes1, lv_pct(-37));
    lv_obj_set_align(ui_BACKBeaconModes1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACKBeaconModes1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACKBeaconModes1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACKBeaconModes1, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACKBeaconModes1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACKBeaconModes1, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACKBeaconModes1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BACKBeaconModes1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BACKBeaconModes1, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BACKBeaconModes1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BACKBeaconModes1, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BACKBeaconModes1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BACKBeaconModes1, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BACKBeaconModes1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BACKBeaconModes1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BACKBeaconModes1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label327 = lv_label_create(ui_BACKBeaconModes1);
    lv_obj_set_width(ui_Label327, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label327, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label327, 0);
    lv_obj_set_y(ui_Label327, 1);
    lv_obj_set_align(ui_Label327, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label327, "BACK");
    lv_obj_set_style_text_font(ui_Label327, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label327, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label327, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Button2 = lv_btn_create(ui_SelectTargetBeacon);
    lv_obj_set_width(ui_Button2, 194);
    lv_obj_set_height(ui_Button2, 25);
    lv_obj_set_y(ui_Button2, -101);
    lv_obj_set_x(ui_Button2, lv_pct(13));
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button2, lv_color_hex(0xB0FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button2, lv_color_hex(0xB900E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label328 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label328, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label328, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label328, -69);
    lv_obj_set_y(ui_Label328, 0);
    lv_obj_set_align(ui_Label328, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label328, "SSID:");
    lv_obj_set_style_text_color(ui_Label328, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label328, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label328, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label328, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label328, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SelectTargetBeaconSSID = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_SelectTargetBeaconSSID, 115);
    lv_obj_set_height(ui_SelectTargetBeaconSSID, 13);
    lv_obj_set_x(ui_SelectTargetBeaconSSID, 40);
    lv_obj_set_y(ui_SelectTargetBeaconSSID, -4);
    lv_obj_set_align(ui_SelectTargetBeaconSSID, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_SelectTargetBeaconSSID, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_SelectTargetBeaconSSID, "NONE");
    lv_obj_set_style_text_font(ui_SelectTargetBeaconSSID, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SelectTargetBeaconSSID, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SelectTargetBeaconSSID, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_WIFINetworks1 = lv_obj_create(ui_SelectTargetBeacon);
    lv_obj_set_width(ui_WIFINetworks1, 267);
    lv_obj_set_height(ui_WIFINetworks1, 159);
    lv_obj_set_x(ui_WIFINetworks1, 7);
    lv_obj_set_y(ui_WIFINetworks1, -5);
    lv_obj_set_align(ui_WIFINetworks1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_WIFINetworks1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_WIFINetworks1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_scrollbar_mode(ui_WIFINetworks1, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_WIFINetworks1, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_WIFINetworks1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WIFINetworks1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WIFINetworks1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WIFINetworks1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_WIFINetworks1, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WIFINetworks1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Network6 = lv_btn_create(ui_WIFINetworks1);
    lv_obj_set_width(ui_Network6, lv_pct(103));
    lv_obj_set_height(ui_Network6, lv_pct(19));
    lv_obj_set_x(ui_Network6, -494);
    lv_obj_set_y(ui_Network6, -39);
    lv_obj_set_align(ui_Network6, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Network6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Network6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Network6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Network6, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Network6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Network6, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Network6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Network6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Network6, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Network6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Network6, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Network6, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Network6, lv_color_hex(0x8C3EF9), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Network6, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_Network6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Network6, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SSID25 = lv_label_create(ui_Network6);
    lv_obj_set_width(ui_SSID25, 230);
    lv_obj_set_height(ui_SSID25, 15);
    lv_obj_set_x(ui_SSID25, -10);
    lv_obj_set_y(ui_SSID25, -1);
    lv_obj_set_align(ui_SSID25, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_SSID25, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_SSID25, "Cafe5655055555");
    lv_obj_set_style_text_color(ui_SSID25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SSID25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SSID25, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SSID25, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_SSID25, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_SSID25, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SCANAPsButton1 = lv_btn_create(ui_SelectTargetBeacon);
    lv_obj_set_height(ui_SCANAPsButton1, 24);
    lv_obj_set_width(ui_SCANAPsButton1, lv_pct(40));
    lv_obj_set_y(ui_SCANAPsButton1, -67);
    lv_obj_set_x(ui_SCANAPsButton1, lv_pct(-29));
    lv_obj_set_align(ui_SCANAPsButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SCANAPsButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SCANAPsButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SCANAPsButton1, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SCANAPsButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SCANAPsButton1, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SCANAPsButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SCANAPsButton1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SCANAPsButton1, lv_color_hex(0xFF4CB7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SCANAPsButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SCANAPsButton1, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_SCANAPsButton1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_SCANAPsButton1, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_SCANAPsButton1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_SCANAPsButton1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SCANAPsButton1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label341 = lv_label_create(ui_SCANAPsButton1);
    lv_obj_set_width(ui_Label341, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label341, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label341, -2);
    lv_obj_set_y(ui_Label341, 0);
    lv_obj_set_align(ui_Label341, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label341, "SCAN");
    lv_obj_set_style_text_font(ui_Label341, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label341, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label341, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_FoundAPsPanel1 = lv_obj_create(ui_SelectTargetBeacon);
    lv_obj_set_height(ui_FoundAPsPanel1, 24);
    lv_obj_set_width(ui_FoundAPsPanel1, lv_pct(57));
    lv_obj_set_x(ui_FoundAPsPanel1, 56);
    lv_obj_set_y(ui_FoundAPsPanel1, -67);
    lv_obj_set_align(ui_FoundAPsPanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_FoundAPsPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_APsFound1 = lv_label_create(ui_FoundAPsPanel1);
    lv_obj_set_width(ui_APsFound1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_APsFound1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_APsFound1, -12);
    lv_obj_set_y(ui_APsFound1, 0);
    lv_obj_set_align(ui_APsFound1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_APsFound1, "0");
    lv_obj_set_style_text_font(ui_APsFound1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_APsFound1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_APsFound1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label342 = lv_label_create(ui_FoundAPsPanel1);
    lv_obj_set_width(ui_Label342, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label342, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label342, 53);
    lv_obj_set_y(ui_Label342, 0);
    lv_obj_set_align(ui_Label342, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label342, "Found");
    lv_obj_set_style_text_font(ui_Label342, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label342, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label342, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_BACKBeaconModes1, ui_event_BACKBeaconModes1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);

}

void ui_SelectTargetBeacon_screen_destroy(void)
{
    if(ui_SelectTargetBeacon) lv_obj_del(ui_SelectTargetBeacon);

    // NULL screen variables
    ui_SelectTargetBeacon = NULL;
    ui_BACKBeaconModes1 = NULL;
    ui_Label327 = NULL;
    ui_Button2 = NULL;
    ui_Label328 = NULL;
    ui_SelectTargetBeaconSSID = NULL;
    ui_WIFINetworks1 = NULL;
    ui_Network6 = NULL;
    ui_SSID25 = NULL;
    ui_SCANAPsButton1 = NULL;
    ui_Label341 = NULL;
    ui_FoundAPsPanel1 = NULL;
    ui_APsFound1 = NULL;
    ui_Label342 = NULL;

}
