// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_SpectrumAnalyzer = NULL;
lv_obj_t * ui_BACKToNRF2 = NULL;
lv_obj_t * ui_Label111 = NULL;
lv_obj_t * ui_SpectrumAnalyzerCHART = NULL;
lv_obj_t * ui_Label280 = NULL;
lv_obj_t * ui_Label281 = NULL;
lv_obj_t * ui_SpectrumAnalyzerCENTERFREQ = NULL;
lv_obj_t * ui_Label283 = NULL;
lv_obj_t * ui_SpectrumAnalyzerPEAK = NULL;
// event funtions
void ui_event_BACKToNRF2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_NrfMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_NrfMenu_screen_init);
    }
}

// build funtions

void ui_SpectrumAnalyzer_screen_init(void)
{
    ui_SpectrumAnalyzer = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SpectrumAnalyzer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SpectrumAnalyzer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpectrumAnalyzer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACKToNRF2 = lv_btn_create(ui_SpectrumAnalyzer);
    lv_obj_set_width(ui_BACKToNRF2, 69);
    lv_obj_set_height(ui_BACKToNRF2, 25);
    lv_obj_set_y(ui_BACKToNRF2, -100);
    lv_obj_set_x(ui_BACKToNRF2, lv_pct(-37));
    lv_obj_set_align(ui_BACKToNRF2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACKToNRF2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACKToNRF2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACKToNRF2, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACKToNRF2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACKToNRF2, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACKToNRF2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BACKToNRF2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BACKToNRF2, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BACKToNRF2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BACKToNRF2, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BACKToNRF2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BACKToNRF2, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BACKToNRF2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BACKToNRF2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BACKToNRF2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label111 = lv_label_create(ui_BACKToNRF2);
    lv_obj_set_width(ui_Label111, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label111, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label111, 0);
    lv_obj_set_y(ui_Label111, 1);
    lv_obj_set_align(ui_Label111, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label111, "BACK");
    lv_obj_set_style_text_font(ui_Label111, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label111, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label111, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SpectrumAnalyzerCHART = lv_chart_create(ui_SpectrumAnalyzer);
    lv_obj_set_width(ui_SpectrumAnalyzerCHART, 207);
    lv_obj_set_height(ui_SpectrumAnalyzerCHART, 121);
    lv_obj_set_x(ui_SpectrumAnalyzerCHART, 0);
    lv_obj_set_y(ui_SpectrumAnalyzerCHART, 31);
    lv_obj_set_align(ui_SpectrumAnalyzerCHART, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_SpectrumAnalyzerCHART, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_SpectrumAnalyzerCHART, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_SpectrumAnalyzerCHART, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_SpectrumAnalyzerCHART, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_SpectrumAnalyzerCHART_series_1 = lv_chart_add_series(ui_SpectrumAnalyzerCHART,
                                                                                lv_color_hex(0xFFB200), LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_SpectrumAnalyzerCHART_series_1_array[] = { 0, 10, 20, 60, 80, 80, 40, 20, 100 };
    lv_chart_set_ext_y_array(ui_SpectrumAnalyzerCHART, ui_SpectrumAnalyzerCHART_series_1,
                             ui_SpectrumAnalyzerCHART_series_1_array);
    lv_obj_set_style_bg_color(ui_SpectrumAnalyzerCHART, lv_color_hex(0x000DFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpectrumAnalyzerCHART, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SpectrumAnalyzerCHART, lv_color_hex(0x2400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SpectrumAnalyzerCHART, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_color(ui_SpectrumAnalyzerCHART, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SpectrumAnalyzerCHART, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SpectrumAnalyzerCHART, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SpectrumAnalyzerCHART, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_SpectrumAnalyzerCHART, lv_color_hex(0x40FF42), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_SpectrumAnalyzerCHART, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SpectrumAnalyzerCHART, lv_color_hex(0xE6FF00), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpectrumAnalyzerCHART, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Label280 = lv_label_create(ui_SpectrumAnalyzer);
    lv_obj_set_width(ui_Label280, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label280, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label280, 84);
    lv_obj_set_y(ui_Label280, -99);
    lv_obj_set_align(ui_Label280, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label280, "Spectrum Analyzer");
    lv_obj_set_style_text_color(ui_Label280, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label280, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label280, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label280, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label280, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label281 = lv_label_create(ui_SpectrumAnalyzer);
    lv_obj_set_width(ui_Label281, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label281, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label281, 8);
    lv_obj_set_y(ui_Label281, -69);
    lv_obj_set_align(ui_Label281, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label281, "Center Freq:");
    lv_obj_set_style_text_color(ui_Label281, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label281, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label281, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label281, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label281, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SpectrumAnalyzerCENTERFREQ = lv_label_create(ui_SpectrumAnalyzer);
    lv_obj_set_width(ui_SpectrumAnalyzerCENTERFREQ, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpectrumAnalyzerCENTERFREQ, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpectrumAnalyzerCENTERFREQ, 125);
    lv_obj_set_y(ui_SpectrumAnalyzerCENTERFREQ, -69);
    lv_obj_set_align(ui_SpectrumAnalyzerCENTERFREQ, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_SpectrumAnalyzerCENTERFREQ, "433.92MHz");
    lv_obj_set_style_text_color(ui_SpectrumAnalyzerCENTERFREQ, lv_color_hex(0x00FF0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpectrumAnalyzerCENTERFREQ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpectrumAnalyzerCENTERFREQ, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SpectrumAnalyzerCENTERFREQ, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SpectrumAnalyzerCENTERFREQ, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label283 = lv_label_create(ui_SpectrumAnalyzer);
    lv_obj_set_width(ui_Label283, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label283, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label283, 8);
    lv_obj_set_y(ui_Label283, -46);
    lv_obj_set_align(ui_Label283, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label283, "Peak:");
    lv_obj_set_style_text_color(ui_Label283, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label283, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label283, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label283, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label283, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SpectrumAnalyzerPEAK = lv_label_create(ui_SpectrumAnalyzer);
    lv_obj_set_width(ui_SpectrumAnalyzerPEAK, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpectrumAnalyzerPEAK, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpectrumAnalyzerPEAK, 132);
    lv_obj_set_y(ui_SpectrumAnalyzerPEAK, -46);
    lv_obj_set_align(ui_SpectrumAnalyzerPEAK, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_SpectrumAnalyzerPEAK, "-70dBm");
    lv_obj_set_style_text_color(ui_SpectrumAnalyzerPEAK, lv_color_hex(0x08FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpectrumAnalyzerPEAK, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpectrumAnalyzerPEAK, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SpectrumAnalyzerPEAK, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SpectrumAnalyzerPEAK, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_BACKToNRF2, ui_event_BACKToNRF2, LV_EVENT_ALL, NULL);

}

void ui_SpectrumAnalyzer_screen_destroy(void)
{
    if(ui_SpectrumAnalyzer) lv_obj_del(ui_SpectrumAnalyzer);

    // NULL screen variables
    ui_SpectrumAnalyzer = NULL;
    ui_BACKToNRF2 = NULL;
    ui_Label111 = NULL;
    ui_SpectrumAnalyzerCHART = NULL;
    ui_Label280 = NULL;
    ui_Label281 = NULL;
    ui_SpectrumAnalyzerCENTERFREQ = NULL;
    ui_Label283 = NULL;
    ui_SpectrumAnalyzerPEAK = NULL;

}
