// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_STARTWARDRIVING_H
#define UI_STARTWARDRIVING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_StartWardriving
extern void ui_StartWardriving_screen_init(void);
extern void ui_StartWardriving_screen_destroy(void);
extern lv_obj_t * ui_StartWardriving;
extern void ui_event_BACKToGPS(lv_event_t * e);
extern lv_obj_t * ui_BACKToGPS;
extern lv_obj_t * ui_Label137;
extern lv_obj_t * ui_STARTSTOPWardriving;
extern lv_obj_t * ui_Label173;
extern lv_obj_t * ui_Label174;
extern lv_obj_t * ui_Label175;
extern lv_obj_t * ui_NetworksFound;
extern lv_obj_t * ui_NetworksFound1;
extern lv_obj_t * ui_NetworksFound2;
extern lv_obj_t * ui_NetworksFound3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

