// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_SAVEDPAYLOADS_H
#define UI_SAVEDPAYLOADS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SavedPayloads
extern void ui_SavedPayloads_screen_init(void);
extern void ui_SavedPayloads_screen_destroy(void);
extern lv_obj_t * ui_SavedPayloads;
extern void ui_event_BACKToNRF3(lv_event_t * e);
extern lv_obj_t * ui_BACKToNRF3;
extern lv_obj_t * ui_Label112;
extern lv_obj_t * ui_SavedPayloadsRoller;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

