// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_STORAGEINFO_H
#define UI_STORAGEINFO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_StorageInfo
extern void ui_StorageInfo_screen_init(void);
extern void ui_StorageInfo_screen_destroy(void);
extern lv_obj_t * ui_StorageInfo;
extern void ui_event_BACKToSD1(lv_event_t * e);
extern lv_obj_t * ui_BACKToSD1;
extern lv_obj_t * ui_Label135;
extern lv_obj_t * ui_Label207;
extern lv_obj_t * ui_StorageInfoCardType;
extern lv_obj_t * ui_Label210;
extern lv_obj_t * ui_StorageTotalSpace;
extern lv_obj_t * ui_Label212;
extern lv_obj_t * ui_StorageUsedSpace;
extern lv_obj_t * ui_Label214;
extern lv_obj_t * ui_StorageFreeSpace;
extern lv_obj_t * ui_StorageBar;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

