// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_SAVEDSIGNALS_H
#define UI_SAVEDSIGNALS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SavedSignals
extern void ui_SavedSignals_screen_init(void);
extern void ui_SavedSignals_screen_destroy(void);
extern lv_obj_t * ui_SavedSignals;
extern void ui_event_BackToSubGHzMenu3(lv_event_t * e);
extern lv_obj_t * ui_BackToSubGHzMenu3;
extern lv_obj_t * ui_Label97;
extern lv_obj_t * ui_SavedSignalsRoller;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

