// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_StartWardriving = NULL;
lv_obj_t * ui_BACKToGPS = NULL;
lv_obj_t * ui_Label137 = NULL;
lv_obj_t * ui_STARTSTOPWardriving = NULL;
lv_obj_t * ui_Label173 = NULL;
lv_obj_t * ui_Label174 = NULL;
lv_obj_t * ui_Label175 = NULL;
lv_obj_t * ui_NetworksFound = NULL;
lv_obj_t * ui_NetworksFound1 = NULL;
lv_obj_t * ui_NetworksFound2 = NULL;
lv_obj_t * ui_NetworksFound3 = NULL;
// event funtions
void ui_event_BACKToGPS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_GPSMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_GPSMenu_screen_init);
    }
}

// build funtions

void ui_StartWardriving_screen_init(void)
{
    ui_StartWardriving = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_StartWardriving, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StartWardriving, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StartWardriving, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACKToGPS = lv_btn_create(ui_StartWardriving);
    lv_obj_set_width(ui_BACKToGPS, 69);
    lv_obj_set_height(ui_BACKToGPS, 25);
    lv_obj_set_y(ui_BACKToGPS, -100);
    lv_obj_set_x(ui_BACKToGPS, lv_pct(-37));
    lv_obj_set_align(ui_BACKToGPS, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACKToGPS, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACKToGPS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACKToGPS, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACKToGPS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACKToGPS, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACKToGPS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BACKToGPS, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BACKToGPS, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BACKToGPS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BACKToGPS, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BACKToGPS, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BACKToGPS, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BACKToGPS, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BACKToGPS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BACKToGPS, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label137 = lv_label_create(ui_BACKToGPS);
    lv_obj_set_width(ui_Label137, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label137, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label137, -1);
    lv_obj_set_y(ui_Label137, 1);
    lv_obj_set_align(ui_Label137, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label137, "BACK");
    lv_obj_set_style_text_font(ui_Label137, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label137, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label137, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_STARTSTOPWardriving = lv_btn_create(ui_StartWardriving);
    lv_obj_set_height(ui_STARTSTOPWardriving, 31);
    lv_obj_set_width(ui_STARTSTOPWardriving, lv_pct(40));
    lv_obj_set_y(ui_STARTSTOPWardriving, 83);
    lv_obj_set_x(ui_STARTSTOPWardriving, lv_pct(-1));
    lv_obj_set_align(ui_STARTSTOPWardriving, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_STARTSTOPWardriving, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_STARTSTOPWardriving, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_STARTSTOPWardriving, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_STARTSTOPWardriving, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_STARTSTOPWardriving, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_STARTSTOPWardriving, lv_color_hex(0x00FF48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_STARTSTOPWardriving, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_STARTSTOPWardriving, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_STARTSTOPWardriving, lv_color_hex(0x94FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_STARTSTOPWardriving, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_STARTSTOPWardriving, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_STARTSTOPWardriving, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_STARTSTOPWardriving, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_STARTSTOPWardriving, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label173 = lv_label_create(ui_STARTSTOPWardriving);
    lv_obj_set_width(ui_Label173, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label173, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label173, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label173, "START");
    lv_obj_set_style_text_font(ui_Label173, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label173, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label173, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label174 = lv_label_create(ui_StartWardriving);
    lv_obj_set_width(ui_Label174, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label174, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label174, 5);
    lv_obj_set_y(ui_Label174, -60);
    lv_obj_set_align(ui_Label174, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label174, "STATUS:");
    lv_obj_set_style_text_color(ui_Label174, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label174, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label174, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label174, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label174, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label175 = lv_label_create(ui_StartWardriving);
    lv_obj_set_width(ui_Label175, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label175, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label175, 87);
    lv_obj_set_y(ui_Label175, -60);
    lv_obj_set_align(ui_Label175, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label175, "WAITING for Fix...");
    lv_obj_set_style_text_color(ui_Label175, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label175, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label175, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label175, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label175, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_NetworksFound = lv_label_create(ui_StartWardriving);
    lv_obj_set_width(ui_NetworksFound, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetworksFound, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NetworksFound, 4);
    lv_obj_set_y(ui_NetworksFound, -34);
    lv_obj_set_align(ui_NetworksFound, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NetworksFound, "Networks Found:");
    lv_obj_set_style_text_color(ui_NetworksFound, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NetworksFound, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NetworksFound, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_NetworksFound, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_NetworksFound, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_NetworksFound1 = lv_label_create(ui_StartWardriving);
    lv_obj_set_width(ui_NetworksFound1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetworksFound1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NetworksFound1, 7);
    lv_obj_set_y(ui_NetworksFound1, -6);
    lv_obj_set_align(ui_NetworksFound1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NetworksFound1, "0");
    lv_obj_set_style_text_color(ui_NetworksFound1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NetworksFound1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NetworksFound1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_NetworksFound1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_NetworksFound1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_NetworksFound2 = lv_label_create(ui_StartWardriving);
    lv_obj_set_width(ui_NetworksFound2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetworksFound2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NetworksFound2, 4);
    lv_obj_set_y(ui_NetworksFound2, 24);
    lv_obj_set_align(ui_NetworksFound2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NetworksFound2, "SD CARD:");
    lv_obj_set_style_text_color(ui_NetworksFound2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NetworksFound2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NetworksFound2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_NetworksFound2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_NetworksFound2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_NetworksFound3 = lv_label_create(ui_StartWardriving);
    lv_obj_set_width(ui_NetworksFound3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetworksFound3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NetworksFound3, 99);
    lv_obj_set_y(ui_NetworksFound3, 24);
    lv_obj_set_align(ui_NetworksFound3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NetworksFound3, "Logging...");
    lv_obj_set_style_text_color(ui_NetworksFound3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NetworksFound3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NetworksFound3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_NetworksFound3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_NetworksFound3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_BACKToGPS, ui_event_BACKToGPS, LV_EVENT_ALL, NULL);

}

void ui_StartWardriving_screen_destroy(void)
{
    if(ui_StartWardriving) lv_obj_del(ui_StartWardriving);

    // NULL screen variables
    ui_StartWardriving = NULL;
    ui_BACKToGPS = NULL;
    ui_Label137 = NULL;
    ui_STARTSTOPWardriving = NULL;
    ui_Label173 = NULL;
    ui_Label174 = NULL;
    ui_Label175 = NULL;
    ui_NetworksFound = NULL;
    ui_NetworksFound1 = NULL;
    ui_NetworksFound2 = NULL;
    ui_NetworksFound3 = NULL;

}
