// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_SUBGHZMENU_H
#define UI_SUBGHZMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SubGhzMenu
extern void ui_SubGhzMenu_screen_init(void);
extern void ui_SubGhzMenu_screen_destroy(void);
extern lv_obj_t * ui_SubGhzMenu;
extern void ui_event_BackToMainMenu2(lv_event_t * e);
extern lv_obj_t * ui_BackToMainMenu2;
extern lv_obj_t * ui_Label3;
extern void ui_event_ReadSignalSelect(lv_event_t * e);
extern lv_obj_t * ui_ReadSignalSelect;
extern lv_obj_t * ui_Label4;
extern void ui_event_SavedSignalsSelect(lv_event_t * e);
extern lv_obj_t * ui_SavedSignalsSelect;
extern lv_obj_t * ui_Label5;
extern void ui_event_FreqAnalyzerSelect(lv_event_t * e);
extern lv_obj_t * ui_FreqAnalyzerSelect;
extern lv_obj_t * ui_Label7;
extern void ui_event_RadioConfigSelect(lv_event_t * e);
extern lv_obj_t * ui_RadioConfigSelect;
extern lv_obj_t * ui_Label8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

