// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_SavedHandshakes = NULL;
lv_obj_t * ui_BACKWifi6 = NULL;
lv_obj_t * ui_Label331 = NULL;
lv_obj_t * ui_SavedHandshakesRoller = NULL;
// event funtions
void ui_event_BACKWifi6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SniffMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SniffMenu_screen_init);
    }
}

// build funtions

void ui_SavedHandshakes_screen_init(void)
{
    ui_SavedHandshakes = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SavedHandshakes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SavedHandshakes, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SavedHandshakes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACKWifi6 = lv_btn_create(ui_SavedHandshakes);
    lv_obj_set_width(ui_BACKWifi6, 69);
    lv_obj_set_height(ui_BACKWifi6, 25);
    lv_obj_set_y(ui_BACKWifi6, -100);
    lv_obj_set_x(ui_BACKWifi6, lv_pct(-37));
    lv_obj_set_align(ui_BACKWifi6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACKWifi6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACKWifi6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACKWifi6, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACKWifi6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACKWifi6, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACKWifi6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BACKWifi6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BACKWifi6, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BACKWifi6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BACKWifi6, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BACKWifi6, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BACKWifi6, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BACKWifi6, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BACKWifi6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BACKWifi6, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label331 = lv_label_create(ui_BACKWifi6);
    lv_obj_set_width(ui_Label331, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label331, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label331, 0);
    lv_obj_set_y(ui_Label331, 1);
    lv_obj_set_align(ui_Label331, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label331, "BACK");
    lv_obj_set_style_text_font(ui_Label331, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label331, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label331, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SavedHandshakesRoller = lv_roller_create(ui_SavedHandshakes);
    lv_roller_set_options(ui_SavedHandshakesRoller, "garaz_doma.sub\nzovora_kostel.sub\nopen_calc.txt\nKuchyne.nfc",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_SavedHandshakesRoller, 249);
    lv_obj_set_height(ui_SavedHandshakesRoller, lv_pct(72));
    lv_obj_set_x(ui_SavedHandshakesRoller, 2);
    lv_obj_set_y(ui_SavedHandshakesRoller, -17);
    lv_obj_set_align(ui_SavedHandshakesRoller, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_text_color(ui_SavedHandshakesRoller, lv_color_hex(0x6D00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SavedHandshakesRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SavedHandshakesRoller, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SavedHandshakesRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SavedHandshakesRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SavedHandshakesRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SavedHandshakesRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SavedHandshakesRoller, lv_color_hex(0x0700FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SavedHandshakesRoller, 440, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SavedHandshakesRoller, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_SavedHandshakesRoller, 255, LV_PART_SELECTED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_SavedHandshakesRoller, lv_color_hex(0xB026FF), LV_PART_SELECTED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_SavedHandshakesRoller, 255, LV_PART_SELECTED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_SavedHandshakesRoller, lv_color_hex(0xB026FF),
                              LV_PART_SELECTED | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_SavedHandshakesRoller, 255, LV_PART_SELECTED | LV_STATE_CHECKED | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_BACKWifi6, ui_event_BACKWifi6, LV_EVENT_ALL, NULL);

}

void ui_SavedHandshakes_screen_destroy(void)
{
    if(ui_SavedHandshakes) lv_obj_del(ui_SavedHandshakes);

    // NULL screen variables
    ui_SavedHandshakes = NULL;
    ui_BACKWifi6 = NULL;
    ui_Label331 = NULL;
    ui_SavedHandshakesRoller = NULL;

}
