// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_ScanAPs = NULL;
lv_obj_t * ui_WifiTargetSelect2 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_WIFIMenuTarget1 = NULL;
lv_obj_t * ui_BACKWifi = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_SCANAPsButton = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_FoundAPsPanel = NULL;
lv_obj_t * ui_APsFound = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_WIFINetworks = NULL;
lv_obj_t * ui_Network1 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_PWR = NULL;
lv_obj_t * ui_CH1 = NULL;
lv_obj_t * ui_SSID = NULL;
lv_obj_t * ui_Network2 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_PWR1 = NULL;
lv_obj_t * ui_CH2 = NULL;
lv_obj_t * ui_SSID1 = NULL;
lv_obj_t * ui_Network3 = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_PWR2 = NULL;
lv_obj_t * ui_CH3 = NULL;
lv_obj_t * ui_SSID2 = NULL;
lv_obj_t * ui_Network4 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_PWR3 = NULL;
lv_obj_t * ui_CH4 = NULL;
lv_obj_t * ui_SSID3 = NULL;
lv_obj_t * ui_Network5 = NULL;
lv_obj_t * ui_Label33 = NULL;
lv_obj_t * ui_Label34 = NULL;
lv_obj_t * ui_PWR4 = NULL;
lv_obj_t * ui_CH5 = NULL;
lv_obj_t * ui_SSID4 = NULL;
// event funtions
void ui_event_BACKWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WiFiMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WiFiMenu_screen_init);
    }
}

void ui_event_SCANAPsButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScanAPs, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScanAPs_screen_init);
    }
}

void ui_event_Network1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WIFIDetails, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WIFIDetails_screen_init);
    }
}

// build funtions

void ui_ScanAPs_screen_init(void)
{
    ui_ScanAPs = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScanAPs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScanAPs, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScanAPs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiTargetSelect2 = lv_btn_create(ui_ScanAPs);
    lv_obj_set_width(ui_WifiTargetSelect2, 194);
    lv_obj_set_height(ui_WifiTargetSelect2, 25);
    lv_obj_set_y(ui_WifiTargetSelect2, -101);
    lv_obj_set_x(ui_WifiTargetSelect2, lv_pct(14));
    lv_obj_set_align(ui_WifiTargetSelect2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiTargetSelect2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WifiTargetSelect2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiTargetSelect2, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiTargetSelect2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WifiTargetSelect2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WifiTargetSelect2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WifiTargetSelect2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_WifiTargetSelect2, lv_color_hex(0xE90000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiTargetSelect2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiTargetSelect2, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_WifiTargetSelect2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_WifiTargetSelect2, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_WifiTargetSelect2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_WifiTargetSelect2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_WifiTargetSelect2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label18 = lv_label_create(ui_WifiTargetSelect2);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -53);
    lv_obj_set_y(ui_Label18, 0);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "TARGET: ");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_WIFIMenuTarget1 = lv_label_create(ui_WifiTargetSelect2);
    lv_obj_set_width(ui_WIFIMenuTarget1, 106);
    lv_obj_set_height(ui_WIFIMenuTarget1, 13);
    lv_obj_set_x(ui_WIFIMenuTarget1, 65);
    lv_obj_set_y(ui_WIFIMenuTarget1, -4);
    lv_obj_set_align(ui_WIFIMenuTarget1, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_WIFIMenuTarget1, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_WIFIMenuTarget1, "NONE");
    lv_obj_set_style_text_font(ui_WIFIMenuTarget1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_WIFIMenuTarget1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_WIFIMenuTarget1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BACKWifi = lv_btn_create(ui_ScanAPs);
    lv_obj_set_width(ui_BACKWifi, 69);
    lv_obj_set_height(ui_BACKWifi, 25);
    lv_obj_set_y(ui_BACKWifi, -100);
    lv_obj_set_x(ui_BACKWifi, lv_pct(-37));
    lv_obj_set_align(ui_BACKWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACKWifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACKWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACKWifi, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACKWifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACKWifi, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACKWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BACKWifi, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BACKWifi, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BACKWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BACKWifi, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BACKWifi, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BACKWifi, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BACKWifi, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BACKWifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BACKWifi, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label20 = lv_label_create(ui_BACKWifi);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 0);
    lv_obj_set_y(ui_Label20, 1);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "BACK");
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SCANAPsButton = lv_btn_create(ui_ScanAPs);
    lv_obj_set_height(ui_SCANAPsButton, 24);
    lv_obj_set_width(ui_SCANAPsButton, lv_pct(40));
    lv_obj_set_y(ui_SCANAPsButton, -67);
    lv_obj_set_x(ui_SCANAPsButton, lv_pct(-29));
    lv_obj_set_align(ui_SCANAPsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SCANAPsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SCANAPsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SCANAPsButton, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SCANAPsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SCANAPsButton, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SCANAPsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SCANAPsButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SCANAPsButton, lv_color_hex(0xFF4CB7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SCANAPsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SCANAPsButton, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_SCANAPsButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_SCANAPsButton, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_SCANAPsButton, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_SCANAPsButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SCANAPsButton, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label21 = lv_label_create(ui_SCANAPsButton);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -2);
    lv_obj_set_y(ui_Label21, 0);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "SCAN");
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_FoundAPsPanel = lv_obj_create(ui_ScanAPs);
    lv_obj_set_height(ui_FoundAPsPanel, 24);
    lv_obj_set_width(ui_FoundAPsPanel, lv_pct(57));
    lv_obj_set_x(ui_FoundAPsPanel, 56);
    lv_obj_set_y(ui_FoundAPsPanel, -67);
    lv_obj_set_align(ui_FoundAPsPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_FoundAPsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_APsFound = lv_label_create(ui_FoundAPsPanel);
    lv_obj_set_width(ui_APsFound, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_APsFound, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_APsFound, -12);
    lv_obj_set_y(ui_APsFound, 0);
    lv_obj_set_align(ui_APsFound, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_APsFound, "0");
    lv_obj_set_style_text_font(ui_APsFound, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_APsFound, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_APsFound, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label23 = lv_label_create(ui_FoundAPsPanel);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 53);
    lv_obj_set_y(ui_Label23, 0);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Found");
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_WIFINetworks = lv_obj_create(ui_ScanAPs);
    lv_obj_set_width(ui_WIFINetworks, 267);
    lv_obj_set_height(ui_WIFINetworks, 159);
    lv_obj_set_x(ui_WIFINetworks, 7);
    lv_obj_set_y(ui_WIFINetworks, -5);
    lv_obj_set_align(ui_WIFINetworks, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_WIFINetworks, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_WIFINetworks, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_scrollbar_mode(ui_WIFINetworks, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_WIFINetworks, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_WIFINetworks, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WIFINetworks, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WIFINetworks, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WIFINetworks, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_WIFINetworks, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WIFINetworks, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Network1 = lv_btn_create(ui_WIFINetworks);
    lv_obj_set_width(ui_Network1, lv_pct(103));
    lv_obj_set_height(ui_Network1, lv_pct(19));
    lv_obj_set_x(ui_Network1, -494);
    lv_obj_set_y(ui_Network1, -39);
    lv_obj_set_align(ui_Network1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Network1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Network1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Network1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Network1, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Network1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Network1, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Network1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Network1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Network1, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Network1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Network1, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Network1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Network1, lv_color_hex(0x8C3EF9), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Network1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_Network1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Network1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label26 = lv_label_create(ui_Network1);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, 22);
    lv_obj_set_y(ui_Label26, 1);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "CH:");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Label26, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label27 = lv_label_create(ui_Network1);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 74);
    lv_obj_set_y(ui_Label27, 1);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "PWR:");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Label27, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_PWR = lv_label_create(ui_Network1);
    lv_obj_set_width(ui_PWR, 23);
    lv_obj_set_height(ui_PWR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PWR, 202);
    lv_obj_set_y(ui_PWR, 1);
    lv_obj_set_align(ui_PWR, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_PWR, "-70");
    lv_obj_set_style_text_color(ui_PWR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PWR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_PWR, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_PWR, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_PWR, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PWR, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_CH1 = lv_label_create(ui_Network1);
    lv_obj_set_width(ui_CH1, 20);
    lv_obj_set_height(ui_CH1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CH1, 144);
    lv_obj_set_y(ui_CH1, 1);
    lv_obj_set_align(ui_CH1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_CH1, "26");
    lv_obj_set_style_text_color(ui_CH1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CH1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_CH1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_CH1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_CH1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_CH1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SSID = lv_label_create(ui_Network1);
    lv_obj_set_width(ui_SSID, 130);
    lv_obj_set_height(ui_SSID, 15);
    lv_obj_set_x(ui_SSID, -11);
    lv_obj_set_y(ui_SSID, 0);
    lv_obj_set_align(ui_SSID, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_SSID, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_SSID, "Cafe56550555555555");
    lv_obj_set_style_text_color(ui_SSID, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SSID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SSID, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SSID, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_SSID, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_SSID, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Network2 = lv_btn_create(ui_WIFINetworks);
    lv_obj_set_width(ui_Network2, lv_pct(103));
    lv_obj_set_height(ui_Network2, lv_pct(19));
    lv_obj_set_x(ui_Network2, -494);
    lv_obj_set_y(ui_Network2, -39);
    lv_obj_set_align(ui_Network2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Network2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Network2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Network2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Network2, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Network2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Network2, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Network2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Network2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Network2, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Network2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Network2, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Network2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Network2, lv_color_hex(0x8C3EF9), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Network2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_Network2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Network2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label24 = lv_label_create(ui_Network2);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 22);
    lv_obj_set_y(ui_Label24, 1);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "CH:");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Label24, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label28 = lv_label_create(ui_Network2);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, 74);
    lv_obj_set_y(ui_Label28, 1);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "PWR:");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Label28, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_PWR1 = lv_label_create(ui_Network2);
    lv_obj_set_width(ui_PWR1, 23);
    lv_obj_set_height(ui_PWR1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PWR1, 202);
    lv_obj_set_y(ui_PWR1, 1);
    lv_obj_set_align(ui_PWR1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_PWR1, "-70");
    lv_obj_set_style_text_color(ui_PWR1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PWR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_PWR1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_PWR1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_PWR1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PWR1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_CH2 = lv_label_create(ui_Network2);
    lv_obj_set_width(ui_CH2, 20);
    lv_obj_set_height(ui_CH2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CH2, 144);
    lv_obj_set_y(ui_CH2, 1);
    lv_obj_set_align(ui_CH2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_CH2, "26");
    lv_obj_set_style_text_color(ui_CH2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CH2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_CH2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_CH2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_CH2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_CH2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SSID1 = lv_label_create(ui_Network2);
    lv_obj_set_width(ui_SSID1, 130);
    lv_obj_set_height(ui_SSID1, 15);
    lv_obj_set_x(ui_SSID1, -11);
    lv_obj_set_y(ui_SSID1, 0);
    lv_obj_set_align(ui_SSID1, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_SSID1, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_SSID1, "Cafe56550555555555");
    lv_obj_set_style_text_color(ui_SSID1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SSID1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SSID1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SSID1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_SSID1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_SSID1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Network3 = lv_btn_create(ui_WIFINetworks);
    lv_obj_set_width(ui_Network3, lv_pct(103));
    lv_obj_set_height(ui_Network3, lv_pct(19));
    lv_obj_set_x(ui_Network3, -494);
    lv_obj_set_y(ui_Network3, -39);
    lv_obj_set_align(ui_Network3, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Network3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Network3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Network3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Network3, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Network3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Network3, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Network3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Network3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Network3, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Network3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Network3, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Network3, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Network3, lv_color_hex(0x8C3EF9), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Network3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_Network3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Network3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label29 = lv_label_create(ui_Network3);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 22);
    lv_obj_set_y(ui_Label29, 1);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "CH:");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Label29, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label30 = lv_label_create(ui_Network3);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, 74);
    lv_obj_set_y(ui_Label30, 1);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "PWR:");
    lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Label30, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Label30, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_PWR2 = lv_label_create(ui_Network3);
    lv_obj_set_width(ui_PWR2, 23);
    lv_obj_set_height(ui_PWR2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PWR2, 202);
    lv_obj_set_y(ui_PWR2, 1);
    lv_obj_set_align(ui_PWR2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_PWR2, "-70");
    lv_obj_set_style_text_color(ui_PWR2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PWR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_PWR2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_PWR2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_PWR2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PWR2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_CH3 = lv_label_create(ui_Network3);
    lv_obj_set_width(ui_CH3, 20);
    lv_obj_set_height(ui_CH3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CH3, 144);
    lv_obj_set_y(ui_CH3, 1);
    lv_obj_set_align(ui_CH3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_CH3, "26");
    lv_obj_set_style_text_color(ui_CH3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CH3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_CH3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_CH3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_CH3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_CH3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SSID2 = lv_label_create(ui_Network3);
    lv_obj_set_width(ui_SSID2, 130);
    lv_obj_set_height(ui_SSID2, 15);
    lv_obj_set_x(ui_SSID2, -11);
    lv_obj_set_y(ui_SSID2, 0);
    lv_obj_set_align(ui_SSID2, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_SSID2, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_SSID2, "Cafe56550555555555");
    lv_obj_set_style_text_color(ui_SSID2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SSID2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SSID2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SSID2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_SSID2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_SSID2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Network4 = lv_btn_create(ui_WIFINetworks);
    lv_obj_set_width(ui_Network4, lv_pct(103));
    lv_obj_set_height(ui_Network4, lv_pct(19));
    lv_obj_set_x(ui_Network4, -494);
    lv_obj_set_y(ui_Network4, -39);
    lv_obj_set_align(ui_Network4, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Network4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Network4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Network4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Network4, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Network4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Network4, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Network4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Network4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Network4, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Network4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Network4, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Network4, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Network4, lv_color_hex(0x8C3EF9), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Network4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_Network4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Network4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label31 = lv_label_create(ui_Network4);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, 22);
    lv_obj_set_y(ui_Label31, 1);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "CH:");
    lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Label31, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label32 = lv_label_create(ui_Network4);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, 74);
    lv_obj_set_y(ui_Label32, 1);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "PWR:");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Label32, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_PWR3 = lv_label_create(ui_Network4);
    lv_obj_set_width(ui_PWR3, 23);
    lv_obj_set_height(ui_PWR3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PWR3, 202);
    lv_obj_set_y(ui_PWR3, 1);
    lv_obj_set_align(ui_PWR3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_PWR3, "-70");
    lv_obj_set_style_text_color(ui_PWR3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PWR3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_PWR3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_PWR3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_PWR3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PWR3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_CH4 = lv_label_create(ui_Network4);
    lv_obj_set_width(ui_CH4, 20);
    lv_obj_set_height(ui_CH4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CH4, 144);
    lv_obj_set_y(ui_CH4, 1);
    lv_obj_set_align(ui_CH4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_CH4, "26");
    lv_obj_set_style_text_color(ui_CH4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CH4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_CH4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_CH4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_CH4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_CH4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SSID3 = lv_label_create(ui_Network4);
    lv_obj_set_width(ui_SSID3, 130);
    lv_obj_set_height(ui_SSID3, 15);
    lv_obj_set_x(ui_SSID3, -11);
    lv_obj_set_y(ui_SSID3, 0);
    lv_obj_set_align(ui_SSID3, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_SSID3, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_SSID3, "Cafe56550555555555");
    lv_obj_set_style_text_color(ui_SSID3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SSID3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SSID3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SSID3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_SSID3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_SSID3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Network5 = lv_btn_create(ui_WIFINetworks);
    lv_obj_set_width(ui_Network5, lv_pct(103));
    lv_obj_set_height(ui_Network5, lv_pct(19));
    lv_obj_set_x(ui_Network5, -494);
    lv_obj_set_y(ui_Network5, -39);
    lv_obj_set_align(ui_Network5, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Network5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Network5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Network5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Network5, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Network5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Network5, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Network5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Network5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Network5, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Network5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Network5, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Network5, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Network5, lv_color_hex(0x8C3EF9), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Network5, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_Network5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Network5, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label33 = lv_label_create(ui_Network5);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, 22);
    lv_obj_set_y(ui_Label33, 1);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "CH:");
    lv_obj_set_style_text_color(ui_Label33, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label33, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Label33, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Label33, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label34 = lv_label_create(ui_Network5);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, 74);
    lv_obj_set_y(ui_Label34, 1);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "PWR:");
    lv_obj_set_style_text_color(ui_Label34, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label34, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Label34, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Label34, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_PWR4 = lv_label_create(ui_Network5);
    lv_obj_set_width(ui_PWR4, 23);
    lv_obj_set_height(ui_PWR4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PWR4, 202);
    lv_obj_set_y(ui_PWR4, 1);
    lv_obj_set_align(ui_PWR4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_PWR4, "-70");
    lv_obj_set_style_text_color(ui_PWR4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PWR4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_PWR4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_PWR4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_PWR4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PWR4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_CH5 = lv_label_create(ui_Network5);
    lv_obj_set_width(ui_CH5, 20);
    lv_obj_set_height(ui_CH5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CH5, 144);
    lv_obj_set_y(ui_CH5, 1);
    lv_obj_set_align(ui_CH5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_CH5, "26");
    lv_obj_set_style_text_color(ui_CH5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CH5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_CH5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_CH5, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_CH5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_CH5, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SSID4 = lv_label_create(ui_Network5);
    lv_obj_set_width(ui_SSID4, 130);
    lv_obj_set_height(ui_SSID4, 15);
    lv_obj_set_x(ui_SSID4, -11);
    lv_obj_set_y(ui_SSID4, 0);
    lv_obj_set_align(ui_SSID4, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_SSID4, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_SSID4, "Cafe56550555555555");
    lv_obj_set_style_text_color(ui_SSID4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SSID4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SSID4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SSID4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_SSID4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_SSID4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_BACKWifi, ui_event_BACKWifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SCANAPsButton, ui_event_SCANAPsButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Network1, ui_event_Network1, LV_EVENT_ALL, NULL);

}

void ui_ScanAPs_screen_destroy(void)
{
    if(ui_ScanAPs) lv_obj_del(ui_ScanAPs);

    // NULL screen variables
    ui_ScanAPs = NULL;
    ui_WifiTargetSelect2 = NULL;
    ui_Label18 = NULL;
    ui_WIFIMenuTarget1 = NULL;
    ui_BACKWifi = NULL;
    ui_Label20 = NULL;
    ui_SCANAPsButton = NULL;
    ui_Label21 = NULL;
    ui_FoundAPsPanel = NULL;
    ui_APsFound = NULL;
    ui_Label23 = NULL;
    ui_WIFINetworks = NULL;
    ui_Network1 = NULL;
    ui_Label26 = NULL;
    ui_Label27 = NULL;
    ui_PWR = NULL;
    ui_CH1 = NULL;
    ui_SSID = NULL;
    ui_Network2 = NULL;
    ui_Label24 = NULL;
    ui_Label28 = NULL;
    ui_PWR1 = NULL;
    ui_CH2 = NULL;
    ui_SSID1 = NULL;
    ui_Network3 = NULL;
    ui_Label29 = NULL;
    ui_Label30 = NULL;
    ui_PWR2 = NULL;
    ui_CH3 = NULL;
    ui_SSID2 = NULL;
    ui_Network4 = NULL;
    ui_Label31 = NULL;
    ui_Label32 = NULL;
    ui_PWR3 = NULL;
    ui_CH4 = NULL;
    ui_SSID3 = NULL;
    ui_Network5 = NULL;
    ui_Label33 = NULL;
    ui_Label34 = NULL;
    ui_PWR4 = NULL;
    ui_CH5 = NULL;
    ui_SSID4 = NULL;

}
