// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_SOURAPPLE_H
#define UI_SOURAPPLE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SourApple
extern void ui_SourApple_screen_init(void);
extern void ui_SourApple_screen_destroy(void);
extern lv_obj_t * ui_SourApple;
extern void ui_event_BACKToBLE2(lv_event_t * e);
extern lv_obj_t * ui_BACKToBLE2;
extern lv_obj_t * ui_Label230;
extern lv_obj_t * ui_Label231;
extern lv_obj_t * ui_SourAppleSTATUS;
extern lv_obj_t * ui_SourAppleBUTTON;
extern lv_obj_t * ui_Label233;
extern lv_obj_t * ui_Label234;
extern lv_obj_t * ui_SourAppleTarget;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

