// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_UNIVERSALIRATTACK_H
#define UI_UNIVERSALIRATTACK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_UniversalIRAttack
extern void ui_UniversalIRAttack_screen_init(void);
extern void ui_UniversalIRAttack_screen_destroy(void);
extern lv_obj_t * ui_UniversalIRAttack;
extern void ui_event_BackToIR3(lv_event_t * e);
extern lv_obj_t * ui_BackToIR3;
extern lv_obj_t * ui_Label206;
extern lv_obj_t * ui_TARGETIR;
extern lv_obj_t * ui_STARTIRAttackUni;
extern lv_obj_t * ui_Label208;
extern lv_obj_t * ui_attackprogress;
extern lv_obj_t * ui_UniversalIRAttackTarget;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

