// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_WIFIDetails = NULL;
lv_obj_t * ui_BackToScanAPs = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_WifiTargetSelect3 = NULL;
lv_obj_t * ui_Label35 = NULL;
lv_obj_t * ui_WIFIMenuTarget2 = NULL;
lv_obj_t * ui_SSID5 = NULL;
lv_obj_t * ui_SSIDDetails = NULL;
lv_obj_t * ui_SSID7 = NULL;
lv_obj_t * ui_BSSIDDetails = NULL;
lv_obj_t * ui_SSID9 = NULL;
lv_obj_t * ui_SSID10 = NULL;
lv_obj_t * ui_SSID11 = NULL;
lv_obj_t * ui_ChannelDetails = NULL;
lv_obj_t * ui_EncryptionDetails = NULL;
lv_obj_t * ui_BeaconsDetails = NULL;
lv_obj_t * ui_SSID15 = NULL;
lv_obj_t * ui_RSSIDetails = NULL;
lv_obj_t * ui_SSID17 = NULL;
lv_obj_t * ui_WPSDetails = NULL;
lv_obj_t * ui_SSID19 = NULL;
lv_obj_t * ui_HiddenDetails = NULL;
lv_obj_t * ui_SSID21 = NULL;
lv_obj_t * ui_ClientsDetails = NULL;
lv_obj_t * ui_SSID23 = NULL;
lv_obj_t * ui_DATAPKTSDetails = NULL;
// event funtions
void ui_event_BackToScanAPs(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScanAPs, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScanAPs_screen_init);
    }
}

// build funtions

void ui_WIFIDetails_screen_init(void)
{
    ui_WIFIDetails = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WIFIDetails, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WIFIDetails, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WIFIDetails, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackToScanAPs = lv_btn_create(ui_WIFIDetails);
    lv_obj_set_width(ui_BackToScanAPs, 69);
    lv_obj_set_height(ui_BackToScanAPs, 25);
    lv_obj_set_y(ui_BackToScanAPs, -100);
    lv_obj_set_x(ui_BackToScanAPs, lv_pct(-37));
    lv_obj_set_align(ui_BackToScanAPs, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackToScanAPs, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackToScanAPs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackToScanAPs, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackToScanAPs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BackToScanAPs, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BackToScanAPs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BackToScanAPs, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BackToScanAPs, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackToScanAPs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackToScanAPs, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BackToScanAPs, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BackToScanAPs, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BackToScanAPs, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BackToScanAPs, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BackToScanAPs, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label25 = lv_label_create(ui_BackToScanAPs);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -1);
    lv_obj_set_y(ui_Label25, 1);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "BACK");
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_WifiTargetSelect3 = lv_btn_create(ui_WIFIDetails);
    lv_obj_set_width(ui_WifiTargetSelect3, 194);
    lv_obj_set_height(ui_WifiTargetSelect3, 25);
    lv_obj_set_y(ui_WifiTargetSelect3, -101);
    lv_obj_set_x(ui_WifiTargetSelect3, lv_pct(14));
    lv_obj_set_align(ui_WifiTargetSelect3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiTargetSelect3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WifiTargetSelect3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiTargetSelect3, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiTargetSelect3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WifiTargetSelect3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WifiTargetSelect3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WifiTargetSelect3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_WifiTargetSelect3, lv_color_hex(0xE90000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiTargetSelect3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiTargetSelect3, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_WifiTargetSelect3, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_WifiTargetSelect3, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_WifiTargetSelect3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_WifiTargetSelect3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_WifiTargetSelect3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label35 = lv_label_create(ui_WifiTargetSelect3);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, -53);
    lv_obj_set_y(ui_Label35, 0);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "TARGET: ");
    lv_obj_set_style_text_color(ui_Label35, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label35, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label35, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label35, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_WIFIMenuTarget2 = lv_label_create(ui_WifiTargetSelect3);
    lv_obj_set_width(ui_WIFIMenuTarget2, 106);
    lv_obj_set_height(ui_WIFIMenuTarget2, 14);
    lv_obj_set_x(ui_WIFIMenuTarget2, 64);
    lv_obj_set_y(ui_WIFIMenuTarget2, -2);
    lv_obj_set_align(ui_WIFIMenuTarget2, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_WIFIMenuTarget2, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_WIFIMenuTarget2, "NONE");
    lv_obj_set_style_text_font(ui_WIFIMenuTarget2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_WIFIMenuTarget2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_WIFIMenuTarget2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SSID5 = lv_label_create(ui_WIFIDetails);
    lv_obj_set_width(ui_SSID5, 130);
    lv_obj_set_height(ui_SSID5, 15);
    lv_obj_set_x(ui_SSID5, 8);
    lv_obj_set_y(ui_SSID5, -70);
    lv_obj_set_align(ui_SSID5, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_SSID5, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_SSID5, "SSID:");
    lv_obj_set_style_text_color(ui_SSID5, lv_color_hex(0x3100B6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SSID5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SSID5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SSID5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SSID5, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_SSID5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_SSID5, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SSIDDetails = lv_label_create(ui_WIFIDetails);
    lv_obj_set_width(ui_SSIDDetails, 221);
    lv_obj_set_height(ui_SSIDDetails, 18);
    lv_obj_set_x(ui_SSIDDetails, 48);
    lv_obj_set_y(ui_SSIDDetails, -69);
    lv_obj_set_align(ui_SSIDDetails, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_SSIDDetails, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_SSIDDetails, "Tp_link_9281729178_sebastITKLJ");
    lv_obj_set_style_text_color(ui_SSIDDetails, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SSIDDetails, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SSIDDetails, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SSIDDetails, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SSIDDetails, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_SSIDDetails, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_SSIDDetails, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SSID7 = lv_label_create(ui_WIFIDetails);
    lv_obj_set_width(ui_SSID7, 130);
    lv_obj_set_height(ui_SSID7, 15);
    lv_obj_set_x(ui_SSID7, 8);
    lv_obj_set_y(ui_SSID7, -53);
    lv_obj_set_align(ui_SSID7, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_SSID7, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_SSID7, "BSSID:");
    lv_obj_set_style_text_color(ui_SSID7, lv_color_hex(0x3100B6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SSID7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SSID7, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SSID7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SSID7, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_SSID7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_SSID7, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BSSIDDetails = lv_label_create(ui_WIFIDetails);
    lv_obj_set_width(ui_BSSIDDetails, 210);
    lv_obj_set_height(ui_BSSIDDetails, 16);
    lv_obj_set_x(ui_BSSIDDetails, 61);
    lv_obj_set_y(ui_BSSIDDetails, -52);
    lv_obj_set_align(ui_BSSIDDetails, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_BSSIDDetails, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_BSSIDDetails, "00:1A:2B:3C:4D:5E");
    lv_obj_set_style_text_color(ui_BSSIDDetails, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BSSIDDetails, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BSSIDDetails, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BSSIDDetails, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BSSIDDetails, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_BSSIDDetails, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_BSSIDDetails, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SSID9 = lv_label_create(ui_WIFIDetails);
    lv_obj_set_width(ui_SSID9, 130);
    lv_obj_set_height(ui_SSID9, 15);
    lv_obj_set_x(ui_SSID9, 8);
    lv_obj_set_y(ui_SSID9, -34);
    lv_obj_set_align(ui_SSID9, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_SSID9, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_SSID9, "CHANNEL:");
    lv_obj_set_style_text_color(ui_SSID9, lv_color_hex(0x3100B6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SSID9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SSID9, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SSID9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SSID9, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_SSID9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_SSID9, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SSID10 = lv_label_create(ui_WIFIDetails);
    lv_obj_set_width(ui_SSID10, 100);
    lv_obj_set_height(ui_SSID10, 15);
    lv_obj_set_x(ui_SSID10, 8);
    lv_obj_set_y(ui_SSID10, -13);
    lv_obj_set_align(ui_SSID10, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_SSID10, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_SSID10, "ENCRYPTION:");
    lv_obj_set_style_text_color(ui_SSID10, lv_color_hex(0x3100B6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SSID10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SSID10, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SSID10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SSID10, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_SSID10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_SSID10, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SSID11 = lv_label_create(ui_WIFIDetails);
    lv_obj_set_width(ui_SSID11, 75);
    lv_obj_set_height(ui_SSID11, 15);
    lv_obj_set_x(ui_SSID11, 8);
    lv_obj_set_y(ui_SSID11, 7);
    lv_obj_set_align(ui_SSID11, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_SSID11, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_SSID11, "BEACONS:");
    lv_obj_set_style_text_color(ui_SSID11, lv_color_hex(0x3100B6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SSID11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SSID11, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SSID11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SSID11, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_SSID11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_SSID11, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_ChannelDetails = lv_label_create(ui_WIFIDetails);
    lv_obj_set_width(ui_ChannelDetails, 125);
    lv_obj_set_height(ui_ChannelDetails, 17);
    lv_obj_set_x(ui_ChannelDetails, 91);
    lv_obj_set_y(ui_ChannelDetails, -33);
    lv_obj_set_align(ui_ChannelDetails, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_ChannelDetails, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_ChannelDetails, "11");
    lv_obj_set_style_text_color(ui_ChannelDetails, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChannelDetails, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChannelDetails, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ChannelDetails, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_ChannelDetails, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_ChannelDetails, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_ChannelDetails, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_EncryptionDetails = lv_label_create(ui_WIFIDetails);
    lv_obj_set_width(ui_EncryptionDetails, 125);
    lv_obj_set_height(ui_EncryptionDetails, 17);
    lv_obj_set_x(ui_EncryptionDetails, 111);
    lv_obj_set_y(ui_EncryptionDetails, -12);
    lv_obj_set_align(ui_EncryptionDetails, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_EncryptionDetails, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_EncryptionDetails, "WPA2-PSK");
    lv_obj_set_style_text_color(ui_EncryptionDetails, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EncryptionDetails, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EncryptionDetails, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_EncryptionDetails, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_EncryptionDetails, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_EncryptionDetails, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_EncryptionDetails, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BeaconsDetails = lv_label_create(ui_WIFIDetails);
    lv_obj_set_width(ui_BeaconsDetails, 182);
    lv_obj_set_height(ui_BeaconsDetails, 17);
    lv_obj_set_x(ui_BeaconsDetails, 88);
    lv_obj_set_y(ui_BeaconsDetails, 8);
    lv_obj_set_align(ui_BeaconsDetails, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_BeaconsDetails, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_BeaconsDetails, "1452");
    lv_obj_set_style_text_color(ui_BeaconsDetails, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BeaconsDetails, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BeaconsDetails, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BeaconsDetails, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BeaconsDetails, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_BeaconsDetails, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_BeaconsDetails, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SSID15 = lv_label_create(ui_WIFIDetails);
    lv_obj_set_width(ui_SSID15, 35);
    lv_obj_set_height(ui_SSID15, 15);
    lv_obj_set_x(ui_SSID15, 8);
    lv_obj_set_y(ui_SSID15, 29);
    lv_obj_set_align(ui_SSID15, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_SSID15, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_SSID15, "RSSI:");
    lv_obj_set_style_text_color(ui_SSID15, lv_color_hex(0x3100B6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SSID15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SSID15, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SSID15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SSID15, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_SSID15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_SSID15, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_RSSIDetails = lv_label_create(ui_WIFIDetails);
    lv_obj_set_width(ui_RSSIDetails, 182);
    lv_obj_set_height(ui_RSSIDetails, 17);
    lv_obj_set_x(ui_RSSIDetails, 47);
    lv_obj_set_y(ui_RSSIDetails, 30);
    lv_obj_set_align(ui_RSSIDetails, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_RSSIDetails, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_RSSIDetails, "-65 dBm");
    lv_obj_set_style_text_color(ui_RSSIDetails, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RSSIDetails, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RSSIDetails, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_RSSIDetails, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_RSSIDetails, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_RSSIDetails, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_RSSIDetails, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SSID17 = lv_label_create(ui_WIFIDetails);
    lv_obj_set_width(ui_SSID17, 39);
    lv_obj_set_height(ui_SSID17, 15);
    lv_obj_set_x(ui_SSID17, 8);
    lv_obj_set_y(ui_SSID17, 49);
    lv_obj_set_align(ui_SSID17, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_SSID17, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_SSID17, "WPS:");
    lv_obj_set_style_text_color(ui_SSID17, lv_color_hex(0x3100B6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SSID17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SSID17, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SSID17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SSID17, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_SSID17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_SSID17, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_WPSDetails = lv_label_create(ui_WIFIDetails);
    lv_obj_set_width(ui_WPSDetails, 182);
    lv_obj_set_height(ui_WPSDetails, 17);
    lv_obj_set_x(ui_WPSDetails, 51);
    lv_obj_set_y(ui_WPSDetails, 49);
    lv_obj_set_align(ui_WPSDetails, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_WPSDetails, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_WPSDetails, "ENABLED");
    lv_obj_set_style_text_color(ui_WPSDetails, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WPSDetails, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WPSDetails, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_WPSDetails, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_WPSDetails, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_WPSDetails, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_WPSDetails, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SSID19 = lv_label_create(ui_WIFIDetails);
    lv_obj_set_width(ui_SSID19, 64);
    lv_obj_set_height(ui_SSID19, 15);
    lv_obj_set_x(ui_SSID19, 8);
    lv_obj_set_y(ui_SSID19, 68);
    lv_obj_set_align(ui_SSID19, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_SSID19, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_SSID19, "HIDDEN:");
    lv_obj_set_style_text_color(ui_SSID19, lv_color_hex(0x3100B6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SSID19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SSID19, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SSID19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SSID19, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_SSID19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_SSID19, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_HiddenDetails = lv_label_create(ui_WIFIDetails);
    lv_obj_set_width(ui_HiddenDetails, 182);
    lv_obj_set_height(ui_HiddenDetails, 17);
    lv_obj_set_x(ui_HiddenDetails, 76);
    lv_obj_set_y(ui_HiddenDetails, 69);
    lv_obj_set_align(ui_HiddenDetails, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_HiddenDetails, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_HiddenDetails, "NO");
    lv_obj_set_style_text_color(ui_HiddenDetails, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HiddenDetails, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HiddenDetails, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_HiddenDetails, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_HiddenDetails, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_HiddenDetails, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_HiddenDetails, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SSID21 = lv_label_create(ui_WIFIDetails);
    lv_obj_set_width(ui_SSID21, 64);
    lv_obj_set_height(ui_SSID21, 15);
    lv_obj_set_x(ui_SSID21, 8);
    lv_obj_set_y(ui_SSID21, 88);
    lv_obj_set_align(ui_SSID21, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_SSID21, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_SSID21, "CLIENTS:");
    lv_obj_set_style_text_color(ui_SSID21, lv_color_hex(0x3100B6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SSID21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SSID21, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SSID21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SSID21, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_SSID21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_SSID21, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_ClientsDetails = lv_label_create(ui_WIFIDetails);
    lv_obj_set_width(ui_ClientsDetails, 182);
    lv_obj_set_height(ui_ClientsDetails, 17);
    lv_obj_set_x(ui_ClientsDetails, 76);
    lv_obj_set_y(ui_ClientsDetails, 89);
    lv_obj_set_align(ui_ClientsDetails, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_ClientsDetails, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_ClientsDetails, "3");
    lv_obj_set_style_text_color(ui_ClientsDetails, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ClientsDetails, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ClientsDetails, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ClientsDetails, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_ClientsDetails, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_ClientsDetails, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_ClientsDetails, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SSID23 = lv_label_create(ui_WIFIDetails);
    lv_obj_set_width(ui_SSID23, 84);
    lv_obj_set_height(ui_SSID23, 15);
    lv_obj_set_x(ui_SSID23, 7);
    lv_obj_set_y(ui_SSID23, 105);
    lv_obj_set_align(ui_SSID23, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_SSID23, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_SSID23, "DATA PKTS:");
    lv_obj_set_style_text_color(ui_SSID23, lv_color_hex(0x3100B6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SSID23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SSID23, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SSID23, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SSID23, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_SSID23, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_SSID23, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_DATAPKTSDetails = lv_label_create(ui_WIFIDetails);
    lv_obj_set_width(ui_DATAPKTSDetails, 178);
    lv_obj_set_height(ui_DATAPKTSDetails, 17);
    lv_obj_set_x(ui_DATAPKTSDetails, 97);
    lv_obj_set_y(ui_DATAPKTSDetails, 107);
    lv_obj_set_align(ui_DATAPKTSDetails, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_DATAPKTSDetails, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_DATAPKTSDetails, "342");
    lv_obj_set_style_text_color(ui_DATAPKTSDetails, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DATAPKTSDetails, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DATAPKTSDetails, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_DATAPKTSDetails, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_DATAPKTSDetails, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_DATAPKTSDetails, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_DATAPKTSDetails, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_BackToScanAPs, ui_event_BackToScanAPs, LV_EVENT_ALL, NULL);

}

void ui_WIFIDetails_screen_destroy(void)
{
    if(ui_WIFIDetails) lv_obj_del(ui_WIFIDetails);

    // NULL screen variables
    ui_WIFIDetails = NULL;
    ui_BackToScanAPs = NULL;
    ui_Label25 = NULL;
    ui_WifiTargetSelect3 = NULL;
    ui_Label35 = NULL;
    ui_WIFIMenuTarget2 = NULL;
    ui_SSID5 = NULL;
    ui_SSIDDetails = NULL;
    ui_SSID7 = NULL;
    ui_BSSIDDetails = NULL;
    ui_SSID9 = NULL;
    ui_SSID10 = NULL;
    ui_SSID11 = NULL;
    ui_ChannelDetails = NULL;
    ui_EncryptionDetails = NULL;
    ui_BeaconsDetails = NULL;
    ui_SSID15 = NULL;
    ui_RSSIDetails = NULL;
    ui_SSID17 = NULL;
    ui_WPSDetails = NULL;
    ui_SSID19 = NULL;
    ui_HiddenDetails = NULL;
    ui_SSID21 = NULL;
    ui_ClientsDetails = NULL;
    ui_SSID23 = NULL;
    ui_DATAPKTSDetails = NULL;

}
