// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#include "../ui.h"

lv_obj_t * ui_WiFiMenu = NULL;
lv_obj_t * ui_BackToMainMenu1 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_ScanAPsSelect = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_DeauthAttackSelect = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_BeaconSpamSelect = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_EvilTwinSelect = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_SniffMenuSelect = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_WifiTargetSelect1 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_WIFIMenuTarget = NULL;
lv_obj_t * ui_WardrivingWifi = NULL;
lv_obj_t * ui_WardrivingWifiLabel = NULL;
lv_obj_t * ui_Label115 = NULL;
// event funtions
void ui_event_BackToMainMenu1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainMenu_screen_init);
    }
}

void ui_event_ScanAPsSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScanAPs, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScanAPs_screen_init);
    }
}

void ui_event_DeauthAttackSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DeauthAttack, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_DeauthAttack_screen_init);
    }
}

void ui_event_BeaconSpamSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_BeaconSpam, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_BeaconSpam_screen_init);
    }
}

void ui_event_EvilTwinSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_EvilTwin, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_EvilTwin_screen_init);
    }
}

void ui_event_SniffMenuSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SniffMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SniffMenu_screen_init);
    }
}

void ui_event_WifiTargetSelect1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScanAPs, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScanAPs_screen_init);
    }
}

// build funtions

void ui_WiFiMenu_screen_init(void)
{
    ui_WiFiMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WiFiMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WiFiMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackToMainMenu1 = lv_btn_create(ui_WiFiMenu);
    lv_obj_set_width(ui_BackToMainMenu1, 69);
    lv_obj_set_height(ui_BackToMainMenu1, 25);
    lv_obj_set_y(ui_BackToMainMenu1, -100);
    lv_obj_set_x(ui_BackToMainMenu1, lv_pct(-37));
    lv_obj_set_align(ui_BackToMainMenu1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackToMainMenu1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackToMainMenu1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackToMainMenu1, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackToMainMenu1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BackToMainMenu1, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BackToMainMenu1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BackToMainMenu1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BackToMainMenu1, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackToMainMenu1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackToMainMenu1, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BackToMainMenu1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BackToMainMenu1, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BackToMainMenu1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BackToMainMenu1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BackToMainMenu1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label6 = lv_label_create(ui_BackToMainMenu1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 1);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "BACK");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_ScanAPsSelect = lv_btn_create(ui_WiFiMenu);
    lv_obj_set_height(ui_ScanAPsSelect, 24);
    lv_obj_set_width(ui_ScanAPsSelect, lv_pct(100));
    lv_obj_set_y(ui_ScanAPsSelect, -24);
    lv_obj_set_x(ui_ScanAPsSelect, lv_pct(0));
    lv_obj_set_align(ui_ScanAPsSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScanAPsSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ScanAPsSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScanAPsSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScanAPsSelect, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScanAPsSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ScanAPsSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScanAPsSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScanAPsSelect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ScanAPsSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScanAPsSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScanAPsSelect, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ScanAPsSelect, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_ScanAPsSelect, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_ScanAPsSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_ScanAPsSelect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_ScanAPsSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label10 = lv_label_create(ui_ScanAPsSelect);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -85);
    lv_obj_set_y(ui_Label10, 0);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "SCAN APs");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_DeauthAttackSelect = lv_btn_create(ui_WiFiMenu);
    lv_obj_set_width(ui_DeauthAttackSelect, lv_pct(100));
    lv_obj_set_height(ui_DeauthAttackSelect, lv_pct(10));
    lv_obj_set_x(ui_DeauthAttackSelect, lv_pct(0));
    lv_obj_set_y(ui_DeauthAttackSelect, lv_pct(3));
    lv_obj_set_align(ui_DeauthAttackSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DeauthAttackSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DeauthAttackSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DeauthAttackSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DeauthAttackSelect, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DeauthAttackSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DeauthAttackSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DeauthAttackSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DeauthAttackSelect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_DeauthAttackSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DeauthAttackSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DeauthAttackSelect, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_DeauthAttackSelect, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_DeauthAttackSelect, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_DeauthAttackSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_DeauthAttackSelect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_DeauthAttackSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label11 = lv_label_create(ui_DeauthAttackSelect);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -51);
    lv_obj_set_y(ui_Label11, 1);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "DEAUTH ATTACK");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BeaconSpamSelect = lv_btn_create(ui_WiFiMenu);
    lv_obj_set_width(ui_BeaconSpamSelect, lv_pct(100));
    lv_obj_set_height(ui_BeaconSpamSelect, lv_pct(10));
    lv_obj_set_x(ui_BeaconSpamSelect, lv_pct(0));
    lv_obj_set_y(ui_BeaconSpamSelect, lv_pct(16));
    lv_obj_set_align(ui_BeaconSpamSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BeaconSpamSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BeaconSpamSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BeaconSpamSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BeaconSpamSelect, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BeaconSpamSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BeaconSpamSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BeaconSpamSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BeaconSpamSelect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BeaconSpamSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BeaconSpamSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BeaconSpamSelect, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BeaconSpamSelect, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BeaconSpamSelect, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_BeaconSpamSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_BeaconSpamSelect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_BeaconSpamSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label12 = lv_label_create(ui_BeaconSpamSelect);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -59);
    lv_obj_set_y(ui_Label12, 1);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "BEACON SPAM");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_EvilTwinSelect = lv_btn_create(ui_WiFiMenu);
    lv_obj_set_width(ui_EvilTwinSelect, lv_pct(100));
    lv_obj_set_height(ui_EvilTwinSelect, lv_pct(10));
    lv_obj_set_x(ui_EvilTwinSelect, lv_pct(0));
    lv_obj_set_y(ui_EvilTwinSelect, lv_pct(29));
    lv_obj_set_align(ui_EvilTwinSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EvilTwinSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_EvilTwinSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_EvilTwinSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_EvilTwinSelect, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EvilTwinSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_EvilTwinSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EvilTwinSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_EvilTwinSelect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_EvilTwinSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EvilTwinSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_EvilTwinSelect, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_EvilTwinSelect, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_EvilTwinSelect, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_EvilTwinSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_EvilTwinSelect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_EvilTwinSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label13 = lv_label_create(ui_EvilTwinSelect);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -83);
    lv_obj_set_y(ui_Label13, 0);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "EVIL TWIN");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SniffMenuSelect = lv_btn_create(ui_WiFiMenu);
    lv_obj_set_width(ui_SniffMenuSelect, lv_pct(100));
    lv_obj_set_height(ui_SniffMenuSelect, lv_pct(10));
    lv_obj_set_x(ui_SniffMenuSelect, lv_pct(0));
    lv_obj_set_y(ui_SniffMenuSelect, lv_pct(42));
    lv_obj_set_align(ui_SniffMenuSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SniffMenuSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SniffMenuSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SniffMenuSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SniffMenuSelect, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SniffMenuSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SniffMenuSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SniffMenuSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SniffMenuSelect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SniffMenuSelect, lv_color_hex(0x4400E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SniffMenuSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SniffMenuSelect, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_SniffMenuSelect, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_SniffMenuSelect, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_SniffMenuSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_SniffMenuSelect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_SniffMenuSelect, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label15 = lv_label_create(ui_SniffMenuSelect);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -10);
    lv_obj_set_y(ui_Label15, 1);
    lv_obj_set_align(ui_Label15, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label15, "SNIFF MENU");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_WifiTargetSelect1 = lv_btn_create(ui_WiFiMenu);
    lv_obj_set_width(ui_WifiTargetSelect1, 194);
    lv_obj_set_height(ui_WifiTargetSelect1, 25);
    lv_obj_set_y(ui_WifiTargetSelect1, -101);
    lv_obj_set_x(ui_WifiTargetSelect1, lv_pct(13));
    lv_obj_set_align(ui_WifiTargetSelect1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiTargetSelect1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WifiTargetSelect1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiTargetSelect1, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiTargetSelect1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WifiTargetSelect1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WifiTargetSelect1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WifiTargetSelect1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_WifiTargetSelect1, lv_color_hex(0xE90000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiTargetSelect1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiTargetSelect1, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_WifiTargetSelect1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_WifiTargetSelect1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_WifiTargetSelect1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label16 = lv_label_create(ui_WifiTargetSelect1);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -53);
    lv_obj_set_y(ui_Label16, 0);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "TARGET: ");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_WIFIMenuTarget = lv_label_create(ui_WifiTargetSelect1);
    lv_obj_set_width(ui_WIFIMenuTarget, 106);
    lv_obj_set_height(ui_WIFIMenuTarget, 17);
    lv_obj_set_x(ui_WIFIMenuTarget, 64);
    lv_obj_set_y(ui_WIFIMenuTarget, -2);
    lv_obj_set_align(ui_WIFIMenuTarget, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_WIFIMenuTarget, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_WIFIMenuTarget, "NONE");
    lv_obj_set_style_text_font(ui_WIFIMenuTarget, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_WIFIMenuTarget, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_WIFIMenuTarget, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_WardrivingWifi = lv_btn_create(ui_WiFiMenu);
    lv_obj_set_height(ui_WardrivingWifi, 31);
    lv_obj_set_width(ui_WardrivingWifi, lv_pct(18));
    lv_obj_set_y(ui_WardrivingWifi, -60);
    lv_obj_set_x(ui_WardrivingWifi, lv_pct(-1));
    lv_obj_set_align(ui_WardrivingWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WardrivingWifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WardrivingWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WardrivingWifi, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WardrivingWifi, lv_color_hex(0x4400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WardrivingWifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WardrivingWifi, lv_color_hex(0xB20D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WardrivingWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WardrivingWifi, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_WardrivingWifi, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WardrivingWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WardrivingWifi, lv_color_hex(0x0000D4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_WardrivingWifi, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_WardrivingWifi, lv_color_hex(0xB026FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_WardrivingWifi, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_WardrivingWifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_WardrivingWifi, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_WardrivingWifiLabel = lv_label_create(ui_WardrivingWifi);
    lv_obj_set_width(ui_WardrivingWifiLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WardrivingWifiLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WardrivingWifiLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WardrivingWifiLabel, "OFF");
    lv_obj_set_style_text_font(ui_WardrivingWifiLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_WardrivingWifiLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_WardrivingWifiLabel, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label115 = lv_label_create(ui_WiFiMenu);
    lv_obj_set_width(ui_Label115, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label115, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label115, -85);
    lv_obj_set_y(ui_Label115, -58);
    lv_obj_set_align(ui_Label115, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label115, "WARDRIVING:");
    lv_obj_set_style_text_color(ui_Label115, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label115, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BackToMainMenu1, ui_event_BackToMainMenu1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScanAPsSelect, ui_event_ScanAPsSelect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DeauthAttackSelect, ui_event_DeauthAttackSelect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BeaconSpamSelect, ui_event_BeaconSpamSelect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_EvilTwinSelect, ui_event_EvilTwinSelect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SniffMenuSelect, ui_event_SniffMenuSelect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiTargetSelect1, ui_event_WifiTargetSelect1, LV_EVENT_ALL, NULL);

}

void ui_WiFiMenu_screen_destroy(void)
{
    if(ui_WiFiMenu) lv_obj_del(ui_WiFiMenu);

    // NULL screen variables
    ui_WiFiMenu = NULL;
    ui_BackToMainMenu1 = NULL;
    ui_Label6 = NULL;
    ui_ScanAPsSelect = NULL;
    ui_Label10 = NULL;
    ui_DeauthAttackSelect = NULL;
    ui_Label11 = NULL;
    ui_BeaconSpamSelect = NULL;
    ui_Label12 = NULL;
    ui_EvilTwinSelect = NULL;
    ui_Label13 = NULL;
    ui_SniffMenuSelect = NULL;
    ui_Label15 = NULL;
    ui_WifiTargetSelect1 = NULL;
    ui_Label16 = NULL;
    ui_WIFIMenuTarget = NULL;
    ui_WardrivingWifi = NULL;
    ui_WardrivingWifiLabel = NULL;
    ui_Label115 = NULL;

}
