// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: FliphackGUI

#ifndef UI_WIFIDETAILS_H
#define UI_WIFIDETAILS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WIFIDetails
extern void ui_WIFIDetails_screen_init(void);
extern void ui_WIFIDetails_screen_destroy(void);
extern lv_obj_t * ui_WIFIDetails;
extern void ui_event_BackToScanAPs(lv_event_t * e);
extern lv_obj_t * ui_BackToScanAPs;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_WifiTargetSelect3;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_WIFIMenuTarget2;
extern lv_obj_t * ui_SSID5;
extern lv_obj_t * ui_SSIDDetails;
extern lv_obj_t * ui_SSID7;
extern lv_obj_t * ui_BSSIDDetails;
extern lv_obj_t * ui_SSID9;
extern lv_obj_t * ui_SSID10;
extern lv_obj_t * ui_SSID11;
extern lv_obj_t * ui_ChannelDetails;
extern lv_obj_t * ui_EncryptionDetails;
extern lv_obj_t * ui_BeaconsDetails;
extern lv_obj_t * ui_SSID15;
extern lv_obj_t * ui_RSSIDetails;
extern lv_obj_t * ui_SSID17;
extern lv_obj_t * ui_WPSDetails;
extern lv_obj_t * ui_SSID19;
extern lv_obj_t * ui_HiddenDetails;
extern lv_obj_t * ui_SSID21;
extern lv_obj_t * ui_ClientsDetails;
extern lv_obj_t * ui_SSID23;
extern lv_obj_t * ui_DATAPKTSDetails;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

